### PR TITLE
Online Food Delivery Preferences

### PR DESCRIPTION
**Pull request by Pratzybha**
# Pull Request for DL-Simplified 💡

## Issue Title :  Online Food Delivery Preferences

- **Info about the related issue (Aim of the project)** : The project focuses on two primary objectives:

Predict whether customers will place future orders using CNN, RNN, and a hybrid RNN+LSTM model based on demographic data such as age, occupation, monthly income, and family size.
Perform sentiment analysis on customer reviews to better understand customer experiences, using DNN, LSTM, and GRU models to classify the reviews as positive or negative.

- **Name:**  Pratibha Gajanan Balgi
- **GitHub ID:**  Pratzybha
- **Email ID:**  pratibhagajananbalgi.201ee240@nitk.edu.in
- **Idenitfy yourself: (Mention in which program you are contributing in. Eg. For a JWOC 2022 participant it's, `JWOC Participant`)**  GSSOC '24-EXT

Closes: #793

### Describe the add-ons or changes you've made 📃

1) Data Preprocessing:
-Removed missing and irrelevant data (e.g., 'Nil' reviews).
-Tokenized reviews and converted them into sequences suitable for deep learning models.

2) Exploratory Data Analysis (EDA):
-Analyzed the distribution of customer demographics such as age, income, family size etc.
-Created visualizations like bar charts and word clouds for reviews to understand sentiment polarity.

3) Model Implementation for Prediction:
-Built CNN, RNN, and RNN+LSTM models to predict customer reordering behavior.
-Experimented with different architectures to capture patterns in structured data.

4) Model Implementation for Sentiment Analysis:
-Developed DNN, LSTM, and GRU models for customer review analysis.
-These models were optimized to handle varying text lengths and interpret user sentiment effectively.

5) Evaluation and Comparison:
-Compared models using accuracy, precision, recall, and F1-score.
-Identified the most accurate models for each task.

## Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? ⚙️

Model Evaluation: After training, each model is evaluated on the test dataset (X_test and y_test). The evaluation returns the test loss and accuracy, which are printed. This provides an overall accuracy metric for the model on unseen data.

Prediction and Thresholding: Each model makes predictions on X_test, which are then thresholded at 0.5 (converting probabilities to binary predictions, i.e., 0 or 1).

Performance Metrics: 
1) Accuracy and Loss Curves: Plots of accuracy and loss over the training and validation sets are created to visualize the model's performance over epochs.
2)Classification Report: A classification report (precision, recall, and F1-score) is generated using classification_report(y_test, y_pred), where y_pred is the thresholded predictions.

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by Pratzybha** [comment]
@abhisheks008 I tried to do pull request many times today. I received some or the other error every time. My files were not loading only. Can you go through these uploaded files once and let me know if I have to make any major changes?

**Comment by Pratzybha** [comment]
@abhisheks008 I made the required changes.

**Comment by abhisheks008** [comment]
Time Factor image is not visible. Please check once!

**Comment by Pratzybha** [comment]
@abhisheks008 completed.

**Review by abhisheks008 — APPROVED** [review]
Approved!
@Pratzybha

**Pull request merged**
