### PR TITLE
Created Brain Tumor Detection Model using CNN

### PR DESCRIPTION
**Pull request by Satyawan7**
# Pull Request for DL-Simplified 💡

Brain Tumor Detection

- Aim: To create a model for Brain Tumor Detection using CNN
- Name: Satyawan Bhuyan
- GitHub ID: Satyawan7
- Email ID: bhuyansaku19it@student.mes.ac.in
- **Idenitfy yourself: (Mention in which program you are contributing in. Eg. For a JWOC 2022 participant it's, `JWOC Participant`)** 

Closes: 77

### Describe the add-ons or changes you've made 📃

Made a new model for  Brain Tumor Detection from Scratch

Example how to mark a checkbox:-
- [x] My code follows the code style of this project.
-->
- [ x] My code follows the guidelines of this project.
- [ x] I have performed a self-review of my own code.
- [ x] I have commented my code, particularly wherever it was hard to understand.
- [ x] I have made corresponding changes to the documentation.
- [ x] My changes generate no new warnings.
- [ x] I have added things that prove my fix is effective or that my feature works.
- [ x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
Please follow the project structure and put your project files accordingly.

**Comment by Satyawan7** [comment]
@abhisheks008  I will make changes soon.

**Comment by abhisheks008** [comment]
@Satyawan7 please do the required changes otherwise this will not be counted towards the contribution to this project repository.

**Comment by abhisheks008** [comment]
Closing the PR due to inactivity.

**Pull request closed without merging**
