### PR TITLE
High Throughput Algae Cell Detection #421

### PR DESCRIPTION
**Pull request by ARPIT2128**
# Pull Request for DL-Simplified 💡

## Issue Title : #417 

- **Info about the related issue (Aim of the project)** :  The aim of this project is to detect high throughput Algae cell using Deep Learning and OpenCV methods.
- **Name:** ARPIT SHARMA
- **GitHub ID:** [My Github](https://github.com/ARPIT2128)
- **Email ID:** arpitsharma2128@gmail.com
- **denitfy yourself:** `SWOC 2024 Participant`

Closes: #issue number that will be closed through this PR

### Describe the add-ons or changes you've made 📃

- Created a template based on the information provided in #417 

## Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## How Has This Been Tested? ⚙️

Describe how it has been tested
Describe how have you verified the changes made

Implemented on synced fork from [here](https://github.com/ARPIT2128/DL-Simplified) so less chance to cause issues for main branch of this repo.

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by ARPIT2128** [comment]
Updated the PR as per request @abhisheks008

**Comment by abhisheks008** [comment]
Follow the README template and update it. I liked the emojified version but it is missing out some important documentation points.

README template, https://github.com/abhisheks008/DL-Simplified/blob/main/.github/readme_template.md

Project to watch out for documentation, https://github.com/abhisheks008/ML-Crate/tree/main/Nurse%20Stress%20Prediction

@ARPIT2128

**Comment by ARPIT2128** [comment]
@abhisheks008 sure, i will look into it

**Review by abhisheks008 — APPROVED** [review]
Super satisfied.

Approved @ARPIT2128

**Pull request merged**
