### PR TITLE
Tripadvisor Reviews Classification using NLP

### PR DESCRIPTION
**Pull request by aindree-2005**
# Pull Request for DL-Simplified 💡

## Issue Title : 
TripAdvisor Reviews Analysis
- **Info about the related issue (Aim of the project)** : TripAdvisor Reviews Analysis using Glove+GRU vs Tfidf and  Logistic Regression
- **Name:**  Aindree Chatterjee
- **GitHub ID:** aindree-2005
- **Email ID:**  aindree2005@gmail.com
- **Idenitfy yourself:**  `Codepeak Participant`

Closes: #266 

### Describe the add-ons or changes you've made 📃
Added files following template

Give a clear description of what have you added or modifications made

## Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? ⚙️

Describe how it has been tested
Describe how have you verified the changes made

Used Kaggle to run 
## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by aindree-2005** [comment]
@abhisheks008 submitted PR

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
1. Prepare some EDA of the dataset before implementing the models.
2. Add the EDA visualizations in the `README.md` file for better understanding.
3. The project folder name should be same as the issue name. Please update that too.

@aindree-2005

**Comment by aindree-2005** [comment]
@abhisheks008 submitted changes. Added the EDA notebook to models too. Changed file name

**Review by abhisheks008 — APPROVED** [review]
Looks good to me. Your PR is approved and ready to be merged.
@aindree-2005

**Pull request merged**
