### PR TITLE
Spam email detection

### PR DESCRIPTION
**Pull request by aindree-2005**
# Pull Request for DL-Simplified 💡

## Issue Title : 
Issue #340 Email Spam Detection using DL
- **Info about the related issue (Aim of the project)** : 
- **Name:** Aindree Chatterjee
- **GitHub ID:** aindree-2005
- **Email ID:** aindree2005@gmail.com
- **Idenitfy yourself: `Codepeak Participant`)** 

Closes: #340 

### Describe the add-ons or changes you've made 📃
Approach for this Project :
**LSTM**
Long Short-Term Memory (LSTM) is a type of recurrent neural network (RNN) designed for processing and predicting sequences. To detect spam, LSTM can analyze patterns in email or text sequences, identifying suspicious content based on contextual relationships and learning from sequential data to make accurate predictions about the likelihood of spam.
**BERT**
BERT (Bidirectional Encoder Representations from Transformers) is a pre-trained natural language processing model. To detect spam, fine-tune BERT on labeled spam/ham data. Use the trained model to predict whether new messages are spam based on their language context, achieving more accurate spam detection compared to traditional methods

## Type of change ☑️

What sort of change have you made:

Example how to mark a checkbox:-
- [x] My code follows the code style of this project.
-->
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? ⚙️

Describe how it has been tested
Describe how have you verified the changes made
Used Kaggle to run the model.There were no errors
## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
Please follow the project structure maintained by other contributors. You can go through the projects to have an idea on this.
@aindree-2005

**Comment by aindree-2005** [comment]
@abhisheks008 I have made the folders as needed now

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
Everything looks really good to me. I'd suggest a small change to make the project complete. Please create a folder named as `Images` and put the EDA generated images into it. Also add the visualization results in the `README.md` file under the Visualization section.

@aindree-2005

**Comment by aindree-2005** [comment]
> Everything looks really good to me. I'd suggest a small change to make the project complete. Please create a folder named as `Images` and put the EDA generated images into it. Also add the visualization results in the `README.md` file under the Visualization section.
> 
> @aindree-2005

@abhisheks008 Added the EDA images into Images. Added the results to readme

**Review by abhisheks008 — APPROVED** [review]
Great one. You PR is approved and upgraded to `Hard` category.
@aindree-2005

**Pull request merged**
