### PR TITLE
Skin Disease Classification using Deep Learning Models

### PR DESCRIPTION
**Pull request by pacificrm**
# Pull Request for DL-Simplified 💡

## Issue Title : Skin Disease Classification using Deep Learning Models

- **Info about the related issue (Aim of the project)** : To build a model to classify various Skin diseases
- **Name:** Prashant Kumar Mishra
- **GitHub ID:**  pacificrm
- **Email ID:** ur.pm.ru@gmail.com
- **Idenitfy yourself: (Mention in which program you are contributing in. Eg. For a JWOC 2022 participant it's, `JWOC Participant`)**  GSSOC-EXT and Hacktoberfest

Closes: #945 

### Describe the add-ons or changes you've made 📃

Give a clear description of what have you added or modifications made
-  I have visualized and done EDA on the image data.
-  I have build 10 different models for skin disease classification in different ways.
-  I have  plotted appropriate graph to compare the  model's performance

## Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? ⚙️

Describe how it has been tested
Describe how have you verified the changes made

Everything is visible inside Model/Readme.md or can be verified by running jupyter Notebook.

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by pacificrm** [comment]
@abhisheks008 Kindly review this and let me know if any changes are required. Thank you.

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
1. Update the file name inside the Dataset folder. It should be renamed as `README.md` instead of `datasetLink.txt`.
2. Update the Model/Readme.md file name to `README.md`.

@pacificrm

**Comment by pacificrm** [comment]
@abhisheks008 The requested changes have been addressed. Please check.

**Review by abhisheks008 — APPROVED** [review]
Approved and level upgraded!
@pacificrm

**Pull request merged**
