### PR TITLE
Laptop price predictor

### PR DESCRIPTION
**Pull request by onkar-1432**
# Pull Request for DL-Simplified 💡

## Issue Title : Laptop Price Predictor 

- **Info about the related issue (Aim of the project)** : This project is about the analysis of a dataset containing data about laptops.
- **Name:** Onkar Viralekar
- **GitHub ID:** onkar-1432
- **Email ID:** onkarviralekar.143@gmail.com
- **Idenitfy yourself: SWOC S4

Closes: ##334

### Describe the add-ons or changes you've made 📃
**Approach to the problem statement** :
- Data Cleaning and Exploration: Exploring the dataset, handling missing values, and creating new features based on the existing ones.The use of Seaborn and Matplotlib for data visualization is great, and it helps in understanding the distribution of data.
- Encoding:Applied label encoding and handled categorical variables well.
- Machine Learning Models: Implemented several regression models, such as Linear Regression, Decision Tree Regressor, Gradient Boosting Regressor, and XGB Regressor.The evaluation metrics, including Mean Squared Error (MSE), Mean Absolute Error (MAE), and R-squared (R2) Score, provide a comprehensive view of model performance.

Give a clear description of what have you added or modifications made

## Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? ⚙️

Describe how it has been tested
Describe how have you verified the changes made

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by abhisheks008** [comment]
As this project repository mainly focuses on deep learning projects, you need to use deep learning methods for this dataset.

**Comment by onkar-1432** [comment]
@abhisheks008  added neural network based approach. Please check and let me if any  changes are required.

**Comment by abhisheks008** [comment]
What deep learning method/model you have used?

**Comment by onkar-1432** [comment]
The code above uses a basic feedforward neural network.

**Comment by abhisheks008** [comment]
Can you use ResNet, MobileNet, VGG and similar kind of deep learning methods for this project?

**Comment by onkar-1432** [comment]
Ok I will try

**Comment by abhisheks008** [comment]
Closing this PR due to inactivity.

**Pull request closed without merging**
