### PR TITLE
Issue #79 Blood Disease Detection

### PR DESCRIPTION
**Pull request by Uttkarsh09**
# Pull Request for DL-Simplified 💡

## Issue Title : 

- **Info about the related issue (Aim of the project)** : 
- **Name:** Uttkarsh Patel
- **GitHub ID:** [Uttkarsh09](https://github.com/Uttkarsh09)
- **Email ID:** uttkarshpatel9@gmail.com
- **Idenitfy yourself: SSOC 22

Closes: #79 

### Describe the add-ons or changes you've made 📃

Made a CNN with various optimizers to compare their accuracy.

## Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? ⚙️

Describe how it has been tested
Describe how have you verified the changes made

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by Uttkarsh09** [comment]
Accuracy and Validation images in the table do not match the logs, will replace the images and their corresponding TensorBoard links once my colab session renews.
Are there any other changes needed?

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
1. Remove the `.gitignore` file.
2. Remove the `Blood Disease Detection/README.md` file, as this is an empty file.
3. Update the tensorboard stuff.

Otherwise everything looks good for me.
@Uttkarsh09

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
Outputs of the jupyter notebook cells are not visible. Kindly look into it. @Uttkarsh09

**Review by abhisheks008 — APPROVED** [review]
Nice representation of the project, keep going with deep learning 🚀 
@Uttkarsh09

**Pull request merged**
