### PR TITLE
Issue 50: First Draft on Glass bangle Defect Detection

### PR DESCRIPTION
**Pull request by guptaaryan16**
# Pull Request for DL-Simplified 💡

- **Info about the related issue (Aim of the project)** : 
- **Name:** Aryan Gupta
- **GitHub ID:** guptaaryan16
- **Email ID:** guptaaryan16

Closes: #50 

### Describe the add-ons or changes you've made 📃
I have made all the changes as per the review and have completed the final draft.

## Type of change ☑️

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## How Has This Been Tested? ⚙️

Describe how it has been tested
Describe how have you verified the changes made

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
1. Create a folder as `Dataset`, and inside it you need to add the dataset that you are using for this project. If the dataset is too huge to get uploaded in GitHub, then create a `README.md` file inside the `Dataset` folder and provide the URL there, from where you have fetched the dataset.
2. You have not visualize the data properly, try to go through an EDA before creating the models.
3. You have created only one model, then how would you provide a comparison which one is the better one. Try to implement more models (atleast 3) to get a comparison which model is the better fit for this dataset.
4. Your jupyter notebook file name should be as, `glass-bangle-defect-detection.ipynb`.

For reference purposes you can check up the other projects those have been already done by the fellow contributors.
@guptaaryan16

**Comment by guptaaryan16** [comment]
ok I will try to complete the changes. Thanks for the review

**Comment by guptaaryan16** [comment]
I have completed all the required tasks. I apologise for the delay as I was busy with my practicals. Please review

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
Remove the Monkeypox Detection folder changes and WCE Curated Colon Disease folder changes, these are the changes we don't need.

@guptaaryan16

**Comment by guptaaryan16** [comment]
hey I have reverted the changes

**Review by abhisheks008 — APPROVED** [review]
Approved your changes @guptaaryan16 

Your PR is approved and merged ✅

**Pull request merged**
