### PR TITLE
Celebrity Faces Detection Model

### PR DESCRIPTION
**Pull request by Avdhesh-Varshney**
# Pull Request for DL-Simplified 💡

## Issue Title : Celebrity Faces Detection using Image Processing

- **Info about the related issue (Aim of the project)** : The aim of this project is to detect the faces of the celebs based on the dataset.
- **Name:** Avdhesh Varshney
- **GitHub ID:** https://github.com/Avdhesh-Varshney
- **Email ID:** avdheshvarshney786@gmail.com
- **Idenitfy yourself: SWOC S4 Contributor

Closes: #461 

### Describe the add-ons or changes you've made 📃

* First I imported all the required libraries and dataset for this project.
* Perfoming the EDA on the whole dataset.
* Chosing 1 target feature i.e., Attractiveness.
* Converting all -1 values into 0 values as negative instances.
* Visualizing the dataset distribution in univariate and bivariate with target feature.
* Splitting the dataset into training, validation and testing set as given in `list_eval_partition.csv` file.
* Due to high amount of dataset and uniform distribution of dataset for training, i will chose small amount from it for training, validation and testing purpose.
* Pre-processing the images i.e., Data augmentation so that model will able to predict easily on any dimension of image like inverted, or at any angle of rotation, etc.
* Finally, build a inceptionv3 model and import the weights already present on kaggle for training and freeze the starting some of the layers of the model and finally creating fully connected layer by own for training the model.
* Train the model and plot the accuracy and loss of the model on test dataset.

## Type of change ☑️

What sort of change have you made:

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested? ⚙️
- I have made this notebook on my kaggle account.

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by Avdhesh-Varshney** [comment]
@abhisheks008 please review this pull request and requested to merge this under SWOC S4

**Comment by abhisheks008** [comment]
Can you try out another model for this project? @Avdhesh-Varshney

**Comment by Avdhesh-Varshney** [comment]
@abhisheks008 i have done it today but the accuracy is not improved. I am still learning it.
Res Net 50 - 50% accuracy
Resnet 101 - 56% accuracy

**Comment by abhisheks008** [comment]
> @abhisheks008 i have done it today but the accuracy is not improved. I am still learning it. Res Net 50 - 50% accuracy Resnet 101 - 56% accuracy

Push the models in the Jupyter file.

**Comment by Avdhesh-Varshney** [comment]
@abhisheks008 again review the pr

**Review by abhisheks008 — APPROVED** [review]
Approved under SWOC S4 @Avdhesh-Varshney

**Pull request merged**
