### PR TITLE
Sea Animal Detection using Neural Networks

### PR DESCRIPTION
**Pull request by aindree-2005**
# Pull Request for DL-Simplified 💡

## Issue Title : 

- **Info about the related issue (Aim of the project)** : 
- **Name:**Aindree
- **GitHub ID:** aindree-2005
- **Email ID:** aindree2005@gmail.com
- **Idenitfy yourself: (Mention in which program you are contributing in. Eg. For a JWOC 2022 participant it's, `JWOC Participant`)** CodePeak 2023

Closes: #349 

### Describe the add-ons or changes you've made 📃
Analysed using CNN, 90% accuracy

## Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? ⚙️

Describe how it has been tested
Describe how have you verified the changes made
Kaggle notebook 

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

 Couldn't dataset zip due to too large file size @abhisheks008

### CODE REVIEW

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
Need some more EDA outputs for the Images folder.
@aindree-2005

**Comment by aindree-2005** [comment]
> Need some more EDA outputs for the Images folder. @aindree-2005

On it now! Will add the EDA Notebook too then

**Comment by aindree-2005** [comment]
@abhisheks008 added other eda plots

**Review by abhisheks008 — APPROVED** [review]
Your PR is approved and ready to be merged.
@aindree-2005

**Pull request merged**
