### PR TITLE
[README Enhancement]: Concrete Compressive Strength Prediction Using Deep Learning

### PR DESCRIPTION
**Pull request by Shravya016**
# Pull Request for DL-Simplified 💡

## Issue Title :  [README Enhancement]: Concrete Compressive Strength Prediction Using Deep Learning #528]

- **Info about the related issue (Aim of the project)** : To update the readme file of  concrete compressive strength to make user to read easily 
- **Name:** shravya pamu
- **GitHub ID:** https://github.com/Shravya016
- **Email ID:** ss9599@srmist.edu.in
- **Idenitfy yourself: ** Contributing for gssoc'24

Closes: #528
### Describe the add-ons or changes you've made 📃

I have added the emojis and made is more readable for the user to read and also I had used the template which was  been provided and I have added key points so that it was easy to read and more eye pleasing

## Type of change ☑️

What sort of change have you made:

- [ ] This change requires a documentation update was been updated

## How Has This Been Tested? ⚙️

I have checked the preview after writing the readme file to see if it was okay

## Checklist: ☑️

- [ ] added emojis to the template.
- [ ] made it more easier and eye pleasing for the user
- [ ] added bullet points so the user could get direct information

### CODE REVIEW

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
Please add the EDA results/visualization images inside the README file.
@Shravya016

**Comment by Shravya016** [comment]
Sure I will add it

**Review by abhisheks008 — APPROVED** [review]
Looks good to me. Your PR is approved and ready to be merged.
@Shravya016

**Comment by Shravya016** [comment]
Okay can I work on other issues or should I wait until this was been reviewed

**Comment by abhisheks008** [comment]
Hi @Shravya016 I am in office right now that's why can't merge your PR. Will merge this by EOD. You can comment out on another issue of your choice.

**Comment by Shravya016** [comment]
Okay thank you so much

**Pull request merged**
