### PR TITLE
Add polyp segmentation

### PR DESCRIPTION
**Pull request by Kaushal-11**
This project implements polyp segmentation in colonoscopy images using three different deep learning architectures: UNet, ResUNet, and DeepLabV3+.

Key Features :-
Image Preprocessing: Resizing images to 256x256, normalizing pixel values.
Training: Uses accuracy, recall, and precision as metrics, logging progress and metrics to a CSV file.
Thresholding: Applies a 0.5 threshold to convert probabilities to binary masks.
Evaluation: Calculates metrics like Accuracy, F1 Score, Jaccard Index (IoU), Recall, and Precision.
Visualization: Displays original images, ground truth masks, and predicted masks side-by-side.

### CODE REVIEW

**Comment by abhisheks008** [comment]
Please follow the project structure and reduce the number of files.

**Comment by Kaushal-11** [comment]
I've attempted to consolidate files, but I've encountered some challenges related to model compatibility. Specifically, integrating certain components into fewer files has resulted in issues with the models not functioning as expected.

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
image

Why you have changed files from every project folder?

**Comment by abhisheks008** [comment]
Closing this pull request as not working.

**Pull request closed without merging**
