### PR TITLE
[Project Addition]: Butterfly Classification using DL - with Web App

### PR DESCRIPTION
**Pull request by ishaanv1709**
# Pull Request for DL-Simplified 💡

## Issue Title : [Project Addition]: Butterfly Classification using DL - with Web App

- **Info about the related issue (Aim of the project)** : Create a web application to classify between 100 species of butterfly using LENET-5 architecture
- **Name:** Ishaan Verma
- **GitHub ID:** https://github.com/ishaanv1206
- **Email ID:** ishaan007verma@gmail.com
- **Idenitfy yourself: (Mention in which program you are contributing in. Eg. For a JWOC 2022 participant it's, `JWOC Participant`)**  GSSOC 2024

Closes: #558 

### Describe the add-ons or changes you've made 📃

I used Convolutional Neural network to classify with LENET-5 architecture. I created web application for it too.

## Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by ishaanv1206** [comment]
Hi @abhisheks008
I did the changes you requested

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
Hi @ishaanv1206 please follow the project structure. For your reference you check this project, [Brain Tumor Detection](https://github.com/abhisheks008/DL-Simplified/tree/main/Brain%20Tumor%20Detection). 

Here is the project structure for a complete web app based project,
```
Project Dummy
|- Dataset
  |- dataset.csv
  |- README.md
|- Images
  |- img1.png
  |- img2.png
  |- img3.png
|- Model
  |- project_dummy.ipynb
  |- README.md
|- Web App
  |- app.py
  |- templates
  |- demo.mp4
  |- README.md
|- requirements.txt
```

**Comment by ishaanv1206** [comment]
@abhisheks008  which images do i have to add in Images folder i didn't understood

**Comment by abhisheks008** [comment]
> @abhisheks008 which images do i have to add in Images folder i didn't understood

The EDA results, model accuracy checking plots and so on.

**Comment by ishaanv1206** [comment]
I created separate model, dataset and web_app folder and added snapshots in main README.md file.

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
### Changes Required:
1. Please rename the project folder names as, **Butterfly Species Classification using DL** instead of `Butterfly_species_classification`.
2. Inside the `Dataset/README.md`, put a brief about the dataset along with the source of the dataset.
3. In the `Model` folder, use Jupyter Notebook file instead of `.py` files. Please check out the existing projects for your reference.
4. In the Web App folder, put the demonstration video and create a README file to showcase the working of the application. For the web app README template, [click here](https://github.com/abhisheks008/DL-Simplified/blob/main/.github/web-app_readme_template.md)

- For your reference, you can check out this project, [Brain Tumor Detection](https://github.com/abhisheks008/DL-Simplified/tree/main/Brain%20Tumor%20Detection)

@ishaanv1206 please fix these changes.

**Comment by abhisheks008** [comment]
> ### Changes Required:
> 1. Please rename the project folder names as, **Butterfly Species Classification using DL** instead of `Butterfly_species_classification`.
> 2. Inside the `Dataset/README.md`, put a brief about the dataset along with the source of the dataset.
> 3. In the `Model` folder, use Jupyter Notebook file instead of `.py` files. Please check out the existing projects for your reference.
> 4. In the Web App folder, put the demonstration video and create a README file to showcase the working of the application. For the web app README template, [click here](https://github.com/abhisheks008/DL-Simplified/blob/main/.github/web-app_readme_template.md)
> 
> * For your reference, you can check out this project, [Brain Tumor Detection](https://github.com/abhisheks008/DL-Simplified/tree/main/Brain%20Tumor%20Detection)
> 
> @ishaanv1206 please fix these changes.

Please follow the required changes list and  make your changes.

**Pull request closed without merging**
