### PR TITLE
 Yahoo Answers NLP #35 

### PR DESCRIPTION
**Pull request by Aadi71**
# Pull Request for DL-Simplified 💡

## Issue Title:  Yahoo Answers NLP #35 

- **Aim**: The goal of this project is to create a deep learning model to analyze Yahoo Answers.
- **Name:** AADI JAIN
- **GitHub ID:** https://github.com/Aadi71
- **Email ID:** jainaadi7102@gmail.com
- **Social Summer of Code' 22 Participant**

Closes: #35

## Checklist: ☑️

- [ ] My code follows the guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented on my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
Rename the `dataset` folder as `Dataset` and put the dataset link inside the `README.md` file, not in the `.txt` file. Remove the `.txt` file.

**Comment by Aadi71** [comment]
> Rename the `dataset` folder as `Dataset` and put the dataset link inside the `README.md` file, not in the `.txt` file. Remove the `.txt` file.

Made the changes, thanks.

**Review by abhisheks008 — APPROVED** [review]
Kudos to your dedication and enthusiasm towards deep learning projects. Great work and nice representation of the project.

Your PR is approved and merged ✅🎉
@Aadi71

**Comment by Aadi71** [comment]
> Kudos to your dedication and enthusiasm towards deep learning projects. Great work and nice representation of the project.
> 
> Your PR is approved and merged ✅🎉 @Aadi71

Thank you.

**Pull request merged**
