### PR TITLE
Book Recommendation:Project Added

### PR DESCRIPTION
**Pull request by Sanjeev-Kumar78**
# Pull Request for DL-Simplified 💡

## Issue Title : [Project Addition]: AI Based Book Recommendation System

- **Info about the related issue (Aim of the project)** : To develop an AI-based book recommendation system that suggests books of similar type or genre based on the book name provided by the user.
- **Name:** Sanjeev Kumar
- **GitHub ID:** Sanjeev-Kumar78
- **Email ID:** sanjeev-kumar78@outlook.com
- **Idenitfy yourself: (Mention in which program you are contributing in. Eg. For a JWOC 2022 participant it's, `JWOC Participant`)** GSOCC'24 Contributor

Closes: #614 

## Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
If you want to create a web app for the same project then please follow the project structure for the same and update accordingly.
@Sanjeev-Kumar78 

For your reference, https://github.com/abhisheks008/DL-Simplified/tree/main/Brain%20Tumor%20Detection

**Comment by Sanjeev-Kumar78** [comment]
Got it, but what's the problem with using streamlit for a web app?
@abhisheks008

**Comment by abhisheks008** [comment]
> Got it, but what's the problem with using streamlit for a web app? @abhisheks008

No problem with the Streamlit app, I am requesting you follow the project structure.

**Comment by Sanjeev-Kumar78** [comment]
Okay 👍

**Comment by Sanjeev-Kumar78** [comment]
> If you want to create a web app for the same project then please follow the project structure for the same and update accordingly. @Sanjeev-Kumar78
> 
> For your reference, https://github.com/abhisheks008/DL-Simplified/tree/main/Brain%20Tumor%20Detection

Based on the reference, I have made updates to the project structure. Please take another look at it.
@abhisheks008

**Comment by Sanjeev-Kumar78** [comment]
I'm sorry for the confusion earlier. I've made the necessary updates to the dataset model, and it turns out that my project didn't need any images, so I didn't create an images folder.
@abhisheks008

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
Please add the README file inside the Web App folder with proper video demonstration of the working of the app.

Follow this Web App README template, https://github.com/abhisheks008/DL-Simplified/blob/main/.github/web-app_readme_template.md

**Comment by Sanjeev-Kumar78** [comment]
Done. @abhisheks008 Please review.

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
Please understand the changes carefully before implementing them. For your reference I have given you an existing project folder, please go through it and check out the project structure of the same. Implement the same project structure for your project too.

1. Remove the Assets folder, instead put the demonstration video inside the Web App folder.
2. The sub folders names should be, Model, Dataset, Images, Web App like this.
3. Insert Images folder and put the EDA images, accuracy graphs there.
4. Use the inserted images in the README file and showcase the data visualization results.
5. Rename the Web App README file to just `README.md`.
6. Also rename the project README to `README.md`.
7. Remove the datasets from the Model folder, Dataset folder is there to store the datasets, there is no need to put datasets in the Model folder.
8. Rename the `Dataset/link.txt` to `Dataset/README.md`. Link.txt is not visible directly.

Follow the Brain Tumor Detection project folder for your reference.
@Sanjeev-Kumar78

**Comment by abhisheks008** [comment]
Images folder is missing in this project. Please add the EDA results and accuracy graphs inside the Images folder.

**Comment by Sanjeev-Kumar78** [comment]
Please check the `Images` folder. Is everything okay?

**Review by abhisheks008 — APPROVED** [review]
Approved @Sanjeev-Kumar78

**Pull request merged**
