### PR TITLE
[Project Addition]: Real Time Sudoku Solver

### PR DESCRIPTION
**Pull request by abckhush**
# Pull Request for DL-Simplified 💡

## Issue Title : [Project Addition] :Real Time Sudoku Solver Using OpenCV

- **Info about the related issue (Aim of the project)** : 
- **Name:** Khushi Kalra
- **GitHub ID:**<a href="https://github.com/abckhush">abckhush</a>
- **Email ID:** kalra.khushi@outlook.com
- **Idenitfy yourself: (Mention in which program you are contributing in. Eg. For a JWOC 2022 participant it's, `JWOC Participant`)** GSSoC 2024 Contributor

Closes: #774 

### Describe the add-ons or changes you've made 📃
added Real time Sudoku solver.

## Type of change ☑️

What sort of change have you made:

- [X] New feature (non-breaking change which adds functionality

## How Has This Been Tested? ⚙️
Yes, A sample demonstration video is included in the README.md file

## Checklist: ☑️

- [X] My code follows the guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly wherever it was hard to understand.
- [X] I have made corresponding changes to the documentation.
- [X] My changes generate no new warnings.
- [X] I have added things that prove my fix is effective or that my feature works.
- [X] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
Please follow the project structure and put the files as per the project structure.

For your reference check out the existing projects and update the structure of the project.

@abckhush

**Comment by abckhush** [comment]
Hi @abhisheks008. I have made the desired changes. Kindly check.

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
Follow the README template and update the same.

Template: https://github.com/abhisheks008/DL-Simplified/blob/main/.github/readme_template.md

**Comment by abckhush** [comment]
Models Implemented
Exploratory Data Analysis Results
Performance of the Models based on the Accuracy Scores
These do not apply for my project/

**Comment by abhisheks008** [comment]
> Models Implemented Exploratory Data Analysis Results Performance of the Models based on the Accuracy Scores These do not apply for my project/

Brief your project and add the images in the README to demonstrate the process how it works.

**Comment by abckhush** [comment]
I have updated the readme file as per requirements. The images are already present in the Images folder. Do you want me to change anything else?

**Review by abhisheks008 — APPROVED** [review]
Looks good to me! Approved @abckhush

**Pull request merged**
