### PR TITLE
Sudoku Solver added

### PR DESCRIPTION
**Pull request by ashis2004**
#856 resolved

### CODE REVIEW

**Comment by ashis2004** [comment]
pls check it @abhisheks008

**Comment by abhisheks008** [comment]
- Project name: 
- 
Info about the related issue (Aim of the project) :
- Name: 
- GitHub ID:
- Email ID: 
- Idenitfy yourself: (Mention in which program you are contributing in. Eg. For a JWOC 2022 participant it's, JWOC Participant) GSSoC'24
- Closes: 

Mention all these details first @ashis2004

**Comment by ashis2004** [comment]
> * Project name: Sudoku Solver using Deep learning 
> * Info about the related issue (Aim of the project) :In this project, we explored the use of CNN, RNN, and GAN models for solving Sudoku puzzles. The RNN model achieved the highest accuracy at 97.10%, making it the most effective model for this task. The CNN model also performed well, with an accuracy of 80.30%. The GAN model showed promising results in generating and solving puzzles, with a discriminator accuracy of 98.44%.
> * Name: Ashish Kumar Patel
> * GitHub ID:https://github.com/ashis2004
> * Email ID:ap550083@gmail.com
> * Idenitfy yourself: (Mention in which program you are contributing in. Eg. For a JWOC 2022 participant it's, JWOC Participant) GSSoC'24 contributor
> * Closes: #856 
> 
> Mention all these details first @ashis2004

**Comment by ashis2004** [comment]
@abhisheks008 pls check it

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
This issue was not even assigned to you.

**Comment by ashis2004** [comment]
> This issue was not even assigned to you.

Screenshot_2024-07-27-10-08-53-239_com android chrome
pls check it you've assigned and also ask for make changes pls check it

**Comment by abhisheks008** [comment]
Scroll down a bit and you can see that I have unassigned that issue from you. I've also shared the reason afterwards.

**Pull request closed without merging**
