### PR TITLE
Disaster Tweets Sentiment Analysis

### PR DESCRIPTION
**Pull request by mehak1309**
# Pull Request for DL-Simplified 💡

## Issue Title : 

- **Info about the related issue (Aim of the project)** :  The goal of the project was to 
-    predict if the given tweet is about a real disaster or not. If so, predict a 1. If not, predict a 0.
- **Name:** Mehak
- **GitHub ID:** https://github.com/mehak1309
- **Email ID:** mehaksingal13@gmail.com
- **Idenitfy yourself: (Mention in which program you are contributing in. Eg. For a JWOC 2022 participant it's, `JWOC Participant`)** GSSOC 2023

Closes: #293

### Describe the add-ons or changes you've made 📃

I have completed my project.

## Type of change ☑️

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## How Has This Been Tested? ⚙️

Describe how it has been tested
Describe how have you verified the changes made

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
1. The folder name should be same as the Issue name. Please update that.
2. Inside the Model folder put the README.md file with proper documentation. You can find the template of the README.md file in the Assets folder.
3. Try to implement some EDA and Visualization on the dataset before implementing the actual model.
4. While creating the models, try to use 2-3 deep learning methods, based on the accuracy scores you can finalize the best fitted method.

@mehak1309

**Comment by abhisheks008** [comment]
@mehak1309 any updates on this pull request?

**Comment by mehak1309** [comment]
@abhisheks008 I had exams. Only hyperparameter tuning is left for 1 model. I will give it by tomorrow. Thanks.

**Comment by abhisheks008** [comment]
@mehak1309 thanks for the update. No issues.

**Comment by mehak1309** [comment]
I have updated the files.

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
You have used two finest models for this project, but the accuracy scores are not upto the mark. Try to achieve 90% accuracy for at least one model.

@mehak1309

**Pull request closed without merging**
