### PR TITLE
Adding the Railway Track Fault Detection Model

### PR DESCRIPTION
**Pull request by pandey-ankit-22**
# Pull Request for DL-Simplified 💡

## Issue Title: Railway Track Fault Detection

- **Info about the related issue (Aim of the project):** To predict whether the given Rail Track is Defective or Not.
- **Name:** Ankit Pandey
- **GitHub ID:** pandey-ankit-22
- **Email ID:** pandeyankit222003@gmail.com
- **Idenitfy yourself:** Contributor (SSOC)

Closes: #issue number that will be closed through this PR

### Describe the add-ons or changes you've made 📃

Give a clear description of what have you added or modifications made

## Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? ⚙️

Describe how it has been tested
Describe how have you verified the changes made

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by pandey-ankit-22** [comment]
@abhisheks008 I have created the PR. Please check !!

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
You have developed the `CNN` model, which is good. Using a single model you can't make a comparison of different models, to find the best fitted one. You should try atleast 2-3 more models, and based on their accuracy scores make a comparison, and then conclude the best fitted model for this project.
@pandey-ankit-22

**Comment by pandey-ankit-22** [comment]
@abhisheks008 I have made the requested changes in the PR. Please check it.

**Review by abhisheks008 — APPROVED** [review]
Looks good to me.

Your PR is approved and ready to be merged.
@pandey-ankit-22

**Pull request merged**
