### PR TITLE
[Model Enhancement]: American Sign Language Detection Model

### PR DESCRIPTION
**Pull request by Adhivp**
# Pull Request for DL-Simplified 💡

## Issue Title : [Model Enhancement]: American Sign Language Detection Model

- **Info about the related issue (Aim of the project)** : To enhance the current ASL model
- **Name:** Adhithyan vp
- **GitHub ID:** @Adhivp 
- **Email ID:** adhivp910@gmail.com
- **Idenitfy yourself:** GSSOC'24

Closes: #574 

### Describe the add-ons or changes you've made 📃

New performance metrics
#### 📈 **Performance of the Models based on the Accuracy Scores**

| Rank | Model Name       | Test Accuracy | Trained Model Size | Training Accuracy | Training Loss |
|------|------------------|---------------|--------------------|-------------------|---------------|
| 1    | MobileNetV3Small | 100.0%        | 19.1MB             | 96.97%            | 0.1574        |
| 2    | NASNetMobile     | 100.0%        | 67.1MB             | 97.96%            | 0.1058        |
| 3    | MobileNetV3Large | 100.0%        | 48.6MB             | 97.98%            | 0.1026        |
| 4    | InceptionV3      | 100.0%        | 287.8MB            | 98.65%            | 0.0712        |
| 5    | ResNet50V2       | 100.0%        | 308.6MB            | 98.67%            | 0.0625        |
| 6    | ResNet101V2      | 100.0%        | 537.5MB            | 98.74%            | 0.0605        |

- ranking based on Trained Model size

## Type of change ☑️

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? ⚙️

Describe how it has been tested
Describe how have you verified the changes made

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by Adhivp** [comment]
ok sure

**Comment by Adhivp** [comment]
Have done the changes as requested @abhisheks008

**Comment by abhisheks008** [comment]
Will review this by EOD.

**Comment by Adhivp** [comment]
@abhisheks008 after Reviewing, please wait for some time web app is also ready, so i will give the PR to that too, I hope we can finish both PR by EOD

**Review by abhisheks008 — APPROVED** [review]
Approved

**Comment by abhisheks008** [comment]
> @abhisheks008 after Reviewing, please wait for some time web app is also ready, so i will give the PR to that too, I hope we can finish both PR by EOD

Create a separate PR for the Web App

**Pull request merged**
