### PR TITLE
BP Monitor Reading using DL

### PR DESCRIPTION
**Pull request by itspallavi20**
# Pull Request for DL-Simplified 💡

## Issue Title : BP Monitor Reading using DL(modified)

- **Info about the related issue (Aim of the project)** : Create a DL model, which will monitor the reading given in the images and identify them.
- **Name:** Pallavi Patil
- **GitHub ID:** https://github.com/itspallavi20
- **Email ID:** pallavigpatil2003@gmail.com
- **Idenitfy yourself: (Mention in which program you are contributing in. Eg. For a JWOC 2022 participant it's, `JWOC Participant`)** I am contributing in GSSOC(GirlScript Summer of Code)-2024

Closes: Initially the issue number was #245, after submitting previous PR which needed update, now it is #891.

### Describe the add-ons or changes you've made 📃

(required corrections have been done ) I have created a DL model by implementing 3 algorithms-1.Custom CNN, 2.Resnet50, 3.RNN with CNN features and compared their accuracies and losses by training on medical dataset. Also updated by creating a single proper project folder consisting of subfolders containing Dataset, Images, Model-(DL model and README.md) and requirements.txt 

## Type of change ☑️

What sort of change have you made:

- [x ] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ x] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] This change requires a documentation update

## How Has This Been Tested? ⚙️

The algorithms are compared on the basis of accuracy score and loss score. Graphs and visualizations are shown which reflect the scores for accuracy for each of the algorithm on the medical dataset for comparisons to find out the best algorithm for BP Monitor Reading dataset.

## Checklist: ☑️

- [ x] My code follows the guidelines of this project.
- [x ] I have performed a self-review of my own code.
- [ x] I have commented my code, particularly wherever it was hard to understand.
- [x ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ x] I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
image

Why you need so many project folders? Create a single project folder and add the sub folders accordingly. Remove the other project folders which are not required.

**Comment by itspallavi20** [comment]
Required changes are updated in the single dedicated directory for BP Monitor Reading. Kindly review the changes, (PR #891)

**Comment by itspallavi20** [comment]
I have updated the single dedicated project directory with proper sub
folders as per the requested changes. Kindly review and sorry for the
inconvenience.

**Comment by abhisheks008** [comment]
Please fix these typing mistakes, the heading tags are not working properly.
image

@itspallavi20

**Comment by itspallavi20** [comment]
The corrections are fixed. Kindly review them.

**Comment by abhisheks008** [comment]
`## Hello` use this syntax only. Your markdown scripts are not working properly as the heading tags are not aligned.
@itspallavi20

**Pull request closed without merging**
