### PR TITLE
Classification of Cyber Bulling using NLP

### PR DESCRIPTION
**Pull request by UtkarshTrivedi2934**
# Pull Request for DL-Simplified 💡

## Issue Title : 

- **Info about the related issue (Aim of the project)** : 
- **Name:** 
- **GitHub ID:** 
- **Email ID:** 
- **Idenitfy yourself: (Mention in which program you are contributing in. Eg. For a JWOC 2022 participant it's, `JWOC Participant`)** 

Closes: #issue number that will be closed through this PR

### Describe the add-ons or changes you've made 📃

Give a clear description of what have you added or modifications made

## Type of change ☑️

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## How Has This Been Tested? ⚙️

Describe how it has been tested
Describe how have you verified the changes made

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
1. Create Images folder and put all the EDA results/outputs there.
2. Use deep learning methods like ResNet, MobileNet, VGG and so on models for this project. This project repo mainly focuses on deep learning projects, machine learning models won't work here.

@UtkarshTrivedi2934

**Comment by abhisheks008** [comment]
> # Pull Request for DL-Simplified 💡
> ## Issue Title :
> * **Info about the related issue (Aim of the project)** :
> * **Name:**
> * **GitHub ID:**
> * **Email ID:**
> * **Idenitfy yourself: (Mention in which program you are contributing in. Eg. For a JWOC 2022 participant it's, `JWOC Participant`)**
> 
> Closes: #issue number that will be closed through this PR
> 
> ### Describe the add-ons or changes you've made 📃
> Give a clear description of what have you added or modifications made
> 
> ## Type of change ☑️
> What sort of change have you made:
> 
> * [x]  Bug fix (non-breaking change which fixes an issue)
> * [x]  New feature (non-breaking change which adds functionality)
> * [x]  Code style update (formatting, local variables)
> * [x]  Breaking change (fix or feature that would cause existing functionality to not work as expected)
> * [x]  This change requires a documentation update
> 
> ## How Has This Been Tested? ⚙️
> Describe how it has been tested Describe how have you verified the changes made
> 
> ## Checklist: ☑️
> * [x]  My code follows the guidelines of this project.
> * [x]  I have performed a self-review of my own code.
> * [x]  I have commented my code, particularly wherever it was hard to understand.
> * [x]  I have made corresponding changes to the documentation.
> * [x]  My changes generate no new warnings.
> * [x]  I have added things that prove my fix is effective or that my feature works.
> * [x]  Any dependent changes have been merged and published in downstream modules.

**Please fill up the details while submitting your PR.**

**Comment by UtkarshTrivedi2934** [comment]
Created a model using XlNet

**Comment by abhisheks008** [comment]
1. Project structure should be followed.
2. Need to do a certain amount of EDA.
3. One model implementation will not work, you need to implement atleast 2-3 models for this project.

@UtkarshTrivedi2934

**Pull request closed without merging**
