### PR TITLE
[Model and README Enhancement] Glass Bangle Defects Detection

### PR DESCRIPTION
**Pull request by Arihant-Bhandari**
# Pull Request for DL-Simplified 💡

## Issue Title : #589 [Model and README Enhancement] Glass Bangle Defects Detection

- **Info about the related issue (Aim of the project)** : Enhancing the project Glass Bangle Defects Detection
- **Name:** Arihant Bhandari
- **GitHub ID:** https://github.com/Arihant-Bhandari
- **Email ID:** arihant.bhandari.2004@gmail.com
- **Idenitfy yourself:** GSSoC Contributor 2024

Closes: #589 [Model and README Enhancement] Glass Bangle Defects Detection

### Describe the add-ons or changes you've made 📃

Added a CNN model based on Keras, Added a CNN model with Attention mechanism, enhanced README.md, added necessary images and doc updates
## Type of change ☑️

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

### CNN-Keras

**Accuracy**: 0.8148148148148148
**Precision**: 0.8084067536295051
**Recall**: 0.7887957990213629
**F1 Score**: 0.7965163842984425

**Loss**: 0.5013639330863953 

### CNN with Attention mechanism

**Loss**: 

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by Arihant-Bhandari** [comment]
hi @abhisheks008 , due to certain circumstances in my college, my exams have been postponed and hence, i have started working on this issue again. this is part one of my issue, CNN using Keras, please see this, i will update CNN with attention soon and then redo README as well.

**Comment by abhisheks008** [comment]
One more thing, you have used ResNet and GoogleNet again? The models were already implemented.

**Comment by Arihant-Bhandari** [comment]
no i havent i have added on to the previous work, at the bottom, the previous owner's work has been kept as is.

**Comment by Arihant-Bhandari** [comment]
hi @abhisheks008 i have added all things necessary for this project. please check and if there are any suggestions or changes to be done, let me know, i would be glad to do them. thank you for the oppurtunity,

**Comment by abhisheks008** [comment]
Can you rename the project folder as `Glass Bangle Defects Detection` by removing the hyphens.

**Comment by Arihant-Bhandari** [comment]
Sure , should I be changing the name on the project itself and so on or just the .ipynb file ?

**Comment by Arihant-Bhandari** [comment]
Sure , should I be changing the name on the project itself and so on or just the .ipynb file ?

**Comment by Arihant-Bhandari** [comment]
Also , @abhisheks008 I wanted to know how we can contribute an entire project to the repo ? Like following similar procedures for enhancements would be fine right ? I had a project in mind which can be considered novel.

If yes , I would like to put this as my next issue.

**Comment by abhisheks008** [comment]
> Sure , should I be changing the name of the project itself and so on or just the .ipynb file ?

Project folder name

**Comment by abhisheks008** [comment]
> Also , @abhisheks008 I wanted to know how we can contribute an entire project to the repo ? Like following similar procedures for enhancements would be fine right ? I had a project in mind which can be considered novel.
> 
> If yes , I would like to put this as my next issue.

Go ahead. Follow the issue template and create your issue.

**Comment by Arihant-Bhandari** [comment]
hi @abhisheks008 , i have done things requested as much as i can, unfortunately i couldnt change the folder name since i am on a sparse checkout of this repo, so only the folder i am working on is displayed at my end and sparse checkout has had me in a twist with renaming the folder , i will try my best to do so but the files are ready to be pushed for issue completion.

**Comment by Arihant-Bhandari** [comment]
@abhisheks008 hi, i ahve tweaked the folder name as required from GitHub VSC , pls check and if there are any suggestion i would be glad to make necessary changes. thank you for your time and patience.

**Review by abhisheks008 — APPROVED** [review]
Approved @Arihant-Bhandari

**Pull request merged**
