### PR TITLE
Submission for Chatgpt Reddit Comment Analysis using NLP and DL for SWOC 2024

### PR DESCRIPTION
**Pull request by lakshmipriya-ragupathi**
# Pull Request for DL-Simplified 💡

## Issue Title : ChatGPT Reddit Comments Analysis using NLP #410

- **Info about the related issue (Aim of the project)** :The aim of this project is to analyze the reddit comments on ChatGPT using NLP and DL methods.

- **Name:** Lakshmipriya Ragupathi
- **GitHub ID:** lakshmipriya-ragupathi
- **Email ID:** lakshmi190803@gmail.com
- **Idenitfy yourself: (Mention in which program you are contributing in.** SWOC 2024 

Closes: #410

### Describe the add-ons or changes you've made 📃

Give a clear description of what have you added or modifications made

## Type of change ☑️

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## How Has This Been Tested? ⚙️

Describe how it has been tested
Describe how have you verified the changes made

## Checklist: ☑️

- [X] My code follows the guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly wherever it was hard to understand.
- [X] I have made corresponding changes to the documentation.
- [X] My changes generate no new warnings.
- [X] I have added things that prove my fix is effective or that my feature works.
- [X] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by abhisheks008** [comment]
This will not work. Follow the project structure and push your files accordingly.

**Comment by lakshmipriya-ragupathi** [comment]
> This will not work. Follow the project structure and push your files accordingly.

Sir, could you please guide me through? 

Thanking you,
Yours sincerely,
Lakshmipriya

**Comment by abhisheks008** [comment]
Project structure will be like this,

**Dummy Project (Same as issue name)**
- Dataset
  - dataset.csv
  - README.md (details about the dataset)
- Images (Include the EDA results and visualization part of the project)
  - img1.png
  - img2.png
  - img3.png
- Model
  - dummy_project.ipynb
  - README.md (Follow the template, https://github.com/abhisheks008/DL-Simplified/blob/main/.github/readme_template.md)
- requirements.txt

**Comment by lakshmipriya-ragupathi** [comment]
Dear Sir, 

I have made the necessary changes, as per your requirements, please kindly review. 

Thanking you,
Yours sincerely,

Lakshmipriya

**Pull request closed without merging**
