### PR TITLE
Musical Instrument Chord Classification 

### PR DESCRIPTION
**Pull request by achrekarom12**
# Pull Request for DL-Simplified 💡

## Issue Title : Musical Instrument Chord Classification 

- **Info about the related issue (Aim of the project)** : To identify major or minor chords from the given audio.
- **Name:** Om Achrekar
- **GitHub ID:** achrekarom12
- **Email ID:** achrekarom@gmail.com
- **Idenitfy yourself: (Mention in which program you are contributing in. Eg. For a JWOC 2022 participant it's, `JWOC Participant`)** SSoC '23 Contributor

Closes: #324

### Describe the add-ons or changes you've made 📃

1. Data collection: From the link of the dataset given above. 
2. Data preprocessing: Preprocessed the audios and created their spectograms in order to make predictions.
3. Model selection: Chose traditional CNN along with ANN and MLP.
4. Comparative analysis: Compared the accuracy score of all the models.

## Type of change ☑️

What sort of change have you made:
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? ⚙️
The evaluation metrics I used to assess the models:

- Accuracy 
- Loss

## Checklist: ☑️
- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by abhisheks008** [comment]
It will be better if you can increase the accuracy scores like other projects.
@achrekarom12

**Comment by achrekarom12** [comment]
There are only 850 available samples which is quite low and that could be the reason for low accuracy. Still I will try  to augment the samples and increase the accuracy upto 80%.
@abhisheks008

**Comment by achrekarom12** [comment]
@abhisheks008 
Things I have done:
1. Found another dataset with different sounds so bootstrapped it with the existing one.
2. Added one more Dense layer in ANN.
3. Added one more Dense layer in MLP.
4. Tried 60-40 split but it didn't improve the accuracy so sticked with 80-20 split.

Previous results:
| Model      | Accuracy | Loss    |
|------------|----------|---------|
| CNN    | 0.669     | 0.63   |
| ANN    | 0.756     | 0.621    |
| MLP    | 0.692     | 0.612    |

New results:
| Model      | Accuracy | Loss    |
|------------|----------|---------|
| CNN    | 0.663 (-0.9%)     | 0.572 (-9.5%)   |
| ANN    | 0.810 (+6.3%)     | 0.916 (-32.2%)    |
| MLP    | 0.707 (+2.1%)     | 0.651 (-5.7%)    |

**Comment by achrekarom12** [comment]
Please let me know if there any further changes are required..

**Review by abhisheks008 — APPROVED** [review]
Your PR is approved and ready to be merged.
@achrekarom12

**Pull request merged**
