### PR TITLE
Loan Approval Prediction Issue #167

### PR DESCRIPTION
**Pull request by Gaurav8604**
# Pull Request for DL-Simplified 💡

## Issue Title : Loan Approval Prediction

- **Info about the related issue (Aim of the project)** :  To predict whether a person is eligible for loan or not.
- **Name:** Gaurav Patil
- **GitHub ID:** Gaurav-8604
- **Email ID:** gauravpatil8604@gmail.com
- **Idenitfy yourself: `SWOC 2023 Contributor` or `SWOC S3 Contributor`

Closes: #167 

### Describe the add-ons or changes you've made 📃
Added a folder Loan Approval Prediction with 3 subfolders Data, Images and Model respective to your template provided.

## Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? ⚙️

Being a small project with a limited dataset, I have checked it manually and tested if each block works fine.

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
Can you use 2 suitable deep learning algorithms for this dataset. And also the accuracies are below 85-90 mark, try to improve the accuracies too.
@Gaurav-8604

**Review by 072arushi — CHANGES_REQUESTED** [review]
You can do pre-processing of the dataset before applying the model, and in case there are no much improvements in results, then you can also apply certain deep learning algorithms as well.

**Comment by abhisheks008** [comment]
@Gaurav-8604 any updates on this pull request, otherwise this will be marked as `wontfix`.

**Comment by Gaurav-8604** [comment]
@abhisheks008 Sorry to say I have my exams running. Will it be fine if I upload in a week or two?

**Comment by abhisheks008** [comment]
It's okay, thanks for the update.

**Comment by Gaurav-8604** [comment]
@abhisheks008 and @072arushi Please check my PR.
All the changes are done according to your requirements.
Thank You.

**Review by 072arushi — APPROVED** [review]
Good contribution

**Review by abhisheks008 — APPROVED** [review]

**Comment by abhisheks008** [comment]
Your PR is approved and ready to be merged.
Thanks for your contribution and time!
@Gaurav-8604

**Pull request merged**
