### PR TITLE
AI Resume Analyzer #975

### PR DESCRIPTION
**Pull request by Niraj1608**
# Pull Request for DL-Simplified 💡

## Issue Title : #975 
**AI Resume Analyzer and ATS Resume Expert** 
- **Info about the related issue (Aim of the project)** : This project aims to leverage machine learning techniques to help job seekers optimize their resumes for specific job applications. We are excited to have contributors who are interested in improving the job application process through AI
- **Name:** Parmar Niraj
- **GitHub ID:** @Niraj1608
- **Email ID:** nirajprmr1608@gmail.com
- **Idenitfy yourself: (Mention in which program you are contributing in. Eg. For a JWOC 2022 participant it's, `JWOC Participant`)**  GSSOC

Closes: #975 

### Describe the add-ons or changes you've made 📃
**Features**
    **Upload Resume PDF:** Allows users to upload a resume file in PDF format.
    **Analyze Resume:** Automatically analyzes the uploaded resume to generate insights on:
          Resume Summary
          Resume Strengths
          Resume Weaknesses
          Suggested Job Titles
    **Interactive UI:** The user can select between different analysis options (Summary, Strengths, Weaknesses, and Suggested Job 
Titles) using a radio button.
    **Generative AI Integration:** Utilizes Gemini Generative AI for analyzing and generating insights based on the resume content.

**ATS Resume Expert** is a Streamlit-based web application that uses Google's Generative AI (Gemini) model to analyze resumes in PDF format against specific job descriptions. The application evaluates the resume content, providing insights and match percentages to help users understand how well their resume aligns with job requirements.

**Features**
**Resume Analysis:** Upload a PDF resume, and the AI evaluates it based on a provided job description.
**Job Match Scoring:** The AI provides a match percentage between the resume and job description, highlighting strengths, weaknesses, missing keywords, and more.
**Streamlit UI:** User-friendly interface with text input for job description and resume upload capability.

## Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist: ☑️

- [X] My code follows the guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly wherever it was hard to understand.
- [X] I have made corresponding changes to the documentation.
- [X] My changes generate no new warnings.
- [X] I have added things that prove my fix is effective or that my feature works.
- [X] Any dependent changes have been merged and published in downstream modules.

outputs are added in results directory

### CODE REVIEW

**Comment by Niraj1608** [comment]
@abhisheks008 i added resume analyzer with ats system its a dual project also im adding the second pr without gemini tho.

**Comment by Niraj1608** [comment]
@abhisheks008 i added resume-analyzer-sentence-transformers file to check please too its also configure without gemini ai 
output are also in results directory . and could you please increase the level of the pr

**Comment by Niraj1608** [comment]
@abhisheks008 pls review my pr

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
Quick changes are required.
1. Rename the project folder as `AI Resume Analyzer` (no hyphens are required).
2. Rename the sub project folder names with the above mentioned naming convention ie. no hyphens in betweeen the words.

@Niraj1608

**Comment by Niraj1608** [comment]
> Quick changes are required.
> 
> 1. Rename the project folder as `AI Resume Analyzer` (no hyphens are required).
> 2. Rename the sub project folder names with the above mentioned naming convention ie. no hyphens in betweeen the words.
> 
> @Niraj1608

@abhisheks008 DONE

**Review by abhisheks008 — APPROVED** [review]
Approved!!
@Niraj1608

**Comment by Niraj1608** [comment]
@abhisheks008 can you increase the level of issue i done hard work on this issue and built it

**Comment by abhisheks008** [comment]
As this is already assigned, couldn't help it right now. Already another issue is assigned to you, that'll help you to increase your points.
@Niraj1608

**Comment by Niraj1608** [comment]
> As this is already assigned, couldn't help it right now. Already another issue is assigned to you, that'll help you to increase your points. @Niraj1608
yeah ohk

**Pull request merged**
