### PR TITLE
Sugarcane Leaf Disease Detection 

### PR DESCRIPTION
**Pull request by atharv1707**
# Pull Request for DL-Simplified 💡

## Issue Title : Sugarcane Leaf Disease Detection

- **Info about the related issue (Aim of the project)** : The main goal of this project is to develop a machine learning model capable of accurately classifying different diseases in sugarcane leaves.
- **Name:** Atharv Pal
- **GitHub ID:** atharv1707
- **Email ID:** atharvpal17@gmail.com
- **Idenitfy yourself:** GSSoC'24 Contributor

Closes: #456

Description:

In this pull request, I have thoroughly analyzed and processed the dataset through the following steps:

**Exploratory Data Analysis (EDA):**

- Conducted EDA to gain a comprehensive understanding of the dataset.
- Utilized data visualization techniques to uncover patterns and insights.
- Applied data augmentation to enhance the diversity of the training data.

**Data Pipeline:**

- Built a robust data pipeline to streamline the data preprocessing and preparation process, essential for training the models.

**Model Training:**

Trained multiple models to compare their performance based on accuracy metrics:

-   VGG16
-   InceptionV3
-   MobileNetV2
-   Custom CNN model

**Ensemble Learning:**

- Implemented an ensemble learning approach to combine the strengths of different models. This approach significantly improved the overall performance and accuracy.

**Evaluation:**

-   Evaluated the models using classification reports and confusion matrices to ensure the quality of the results.

This comprehensive approach has resulted in improved model performance and accuracy. I hope that these contributions are valuable to the project.

## Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? ⚙️

The dataset was split into three parts with a 60:20:20 ratio for training, validation, and testing. Separate data generators were created for each subset. After training each model, I evaluated its performance against the testing dataset to ensure accurate training and robust performance. This approach confirmed that the models were correctly trained and capable of performing well on unseen data.

## Checklist: ☑️

- [ x] My code follows the guidelines of this project.
- [ x] I have performed a self-review of my own code.
- [ x] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
1. Remove the Dataset/Model folder, not useful here.
2. Rename the dataset.MD file to README.md
3. Rename the readme.md file to README.md

**Comment by atharv1707** [comment]
Hey @abhisheks008! I've implemented the changes based on your suggestions. Could you please review them? Thanks!

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
1. 
image
Fix this indentation issue.

2. Remove the model.txt file, it's empty.

**Comment by atharv1707** [comment]
hey @abhisheks008  I have deleted the file. Though the indentation seemed fine, I have edited the file suitably so that the issue doesn't come up again. Please review the changes

**Pull request merged**
