### PR TITLE
Indian Medicinal Plants Classification

### PR DESCRIPTION
**Pull request by aaradhyasinghgaur**
# Pull Request for DL-Simplified 💡

## Issue Title : Indian Medicinal Plants Classification 

- **Info about the related issue (Aim of the project)** : To detect and classify between 99 different Indian medicinal leaves and plants. 
- **Name:** Aaradhya Singh 
- **GitHub ID:** https://github.com/kyra-09
- **Email ID:** aaradhyasinghgaur@gmail.com 
- **Idenitfy yourself: (Mention in which program you are contributing in. Eg. For a JWOC 2022 participant it's, `JWOC Participant`)**  GSSOC-2024 Contributor

Closes: #738

### Describe the add-ons or changes you've made 📃

1.) Utilized 5 differnt models on the mini batch of the dataset and modified it to give exceptional accuracy even when the models are trained on only 10% of the dataset.
2.) Did EDA analysis on the dataset to find out the data/image distribution among different classes.
3.) used data-aumenation techniques to enhance the complexity of the dataset so as to increase accuracy of models.

## Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? ⚙️

Describe how it has been tested
Describe how have you verified the changes made

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by kyra-09** [comment]
@abhisheks008 kindly review my pr for any changes and assign me a new issue if possible.

**Comment by aaradhyasinghgaur** [comment]
@abhisheks008 kindly review my pr and assign other 3 issues to me too so that I can make PRs for them as well as possible please if you could do this.

**Comment by abhisheks008** [comment]
> @abhisheks008 kindly review my pr and assign other 3 issues to me too so that I can make PRs for them as well as possible please if you could do this.

One by one. If you are trying to violet the code of conduct your contributions will be considered as spam.

**Review by abhisheks008 — APPROVED** [review]
Approved @aaradhyasinghgaur

**Pull request merged**
