### PR TITLE
Rick and Morty Character Image Detection

### PR DESCRIPTION
**Pull request by aaradhyasinghgaur**
# Pull Request for DL-Simplified 💡

## Issue Title :  Rick and Morty Character Image Detection #462  

- **Info about the related issue (Aim of the project)** : To train and predict the images from Rick and Morty dataset
- **Name:** - Aaradhya Singh
- **GitHub ID:** - kyra-09
- **Email ID:** - aaradhyasinghgaur@gmail.com
- **Idenitfy yourself: (Mention in which program you are contributing in. Eg. For a JWOC 2022 participant it's, `JWOC Participant`)** - Contributor/ GSSOC-2024

Closes: #462 

### Describe the add-ons or changes you've made 📃

To train and predict the dataset Containing characters of Rick and Morty i've trained various different models and compared them for better accuracy , the models are mentioned below :- 
1.) InceptionV3
2.)VGG16
3.)MobileNetV2

## Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## How Has This Been Tested? ⚙️

It has been tested on test dataset from the mentioned Rick and Morty dataset from kaggel .
I have varified and shown the prediction of few of the random chosen images from testset....although the accuarcy of it may differ on testset given the fewer set I took to train the models considering the time it was taking for training.

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
1. Please create a single `.ipynb` file and collab all the models including some EDA into it.
2. Follow the README template. Here is the [template](https://github.com/abhisheks008/DL-Simplified/blob/main/.github/readme_template.md).
3. Include the EDA results in the README as per the template and also include them in the Images folder.

These changes are required. @kyra-09

**Comment by abhisheks008** [comment]
> 1. Please create a single `.ipynb` file and collab all the models including some EDA into it.
> 2. Follow the README template. Here is the [template](https://github.com/abhisheks008/DL-Simplified/blob/main/.github/readme_template.md).
> 3. Include the EDA results in the README as per the template and also include them in the Images folder.
> 
> These changes are required. @kyra-09

Please update the above mentioned changes.

**Comment by kyra-09** [comment]
@abhisheks008 , I've made the necessary changes , kindly review them .
PS - Sorry for the delay , Got stuck with some personal issues.

**Review by abhisheks008 — APPROVED** [review]
Approved @kyra-09 

I'll merge this PR by EOD.

**Comment by kyra-09** [comment]
Thanks @abhisheks008 , looking forward to contribute in more projects . This time in a bit consistent manner .

**Comment by abhisheks008** [comment]
> Thanks @abhisheks008 , looking forward to contribute in more projects . This time in a bit consistent manner .

No issues with that!

**Comment by sanjay-kv** [comment]
@aaradhyasinghgaur Same for this 
image

**Pull request merged**
