### PR TITLE
Diabetes Prediction using DL

### PR DESCRIPTION
**Pull request by Sgvkamalakar**
# Pull Request for DL-Simplified 💡

## Issue Title: Diabetes Prediction using DL #285

- Info about the related issue (Aim of the project) : Diabetes Prediction using Deep Learning Models
- Name: S G V Kamalakar
- GitHub ID: [Sgvkamalakar](https://github.com/Sgvkamalakar)
- Email ID: [sgvkamalakar@gmail.com](mailto:sgvkamalakar@gmail.com)
- Identify yourself: GSSOC '24

----

Closes: #285 

----

### Describe the add-ons or changes you've made 📃

Give a clear description of what have you added or modifications made

- Added Deep Learning Models and Streamlit Application for Diabetic Prediction

- This PR  introduces Deep Learning models trained on diabetic data for diabetic prediction. It includes the implementation of artificial neural network (ANN), long short-term memory (LSTM), and recurrent neural network (RNN) models using TensorFlow.

- A Streamlit application has been developed to provide a user-friendly interface for predicting diabetes based on user input. The application allows users to input various parameters, such as glucose level, blood pressure, BMI, etc. and predicts the likelihood of diabetes using the trained models.

----

## Type of change ☑️

What sort of change have you made:

- [x] New feature (non-breaking change which adds functionality)

----

## How Has This Been Tested? ⚙️

Describe how it has been tested
Describe how have you verified the changes made
Conducted a thorough code review to ensure that the changes align with the project goals and coding standards. You can run the [notebook](https://github.com/Sgvkamalakar/DL-Simplified/blob/main/Diabetes%20Predictor/Notebook/Diabetes%20Prediction.ipynb) 

----

### Performance comparison
image

----

### Streamlit application page
image

----

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my code.
- [x] I have commented on my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
Follow this project structure, 
```
Project Dummy
|- Dataset
  |- dataset.csv
  |- README.md
|- Images
  |- img1.png
  |- img2.png
  |- img3.png
|- Model
  |- project_dummy.ipynb
  |- README.md
|- Web App
  |- app.py
  |- templates
  |- demo.mp4
  |- README.md
|- requirements.txt
```

For your reference you can have a look at an existing web app project, [Brain Tumor Detection](https://github.com/abhisheks008/DL-Simplified/tree/main/Brain%20Tumor%20Detection)

**Comment by Sgvkamalakar** [comment]
The repo and readme have been modified as mentioned.

**Review by abhisheks008 — APPROVED** [review]
Fantastic work done! Your PR is approved and ready to be merged.

I'll merge the PR by EOD.

@Sgvkamalakar

**Comment by abhisheks008** [comment]
Hi @Sgvkamalakar  need a minor change. Can you represent the demo video like this, 
image

For your reference you can have a look at this project, [Brain Tumor Detection/Web App](https://github.com/abhisheks008/DL-Simplified/tree/main/Brain%20Tumor%20Detection/Web%20App)

**Comment by Sgvkamalakar** [comment]
Got it! The modification has been implemented.

**Comment by abhisheks008** [comment]
> Got it! The modification has been implemented.

Can you share the same technique with @aindree-2005. As Aindree is also trying to do the same embedded video in the README but couldn't find out a perfect solution for it.

**Pull request merged**
