### PR TITLE
Enhancement of Loan approval prediction model

### PR DESCRIPTION
**Pull request by kumar8074**
# Pull Request for DL-Simplified 💡

## Issue Title : Enhancement of Bank Loan Approval Prediction #473

- **Info about the related issue (Aim of the project)** :  To Enhance the existing loan approval prediction model
- **Name:** Lalan Kumar 
- **GitHub ID:** https://github.com/kumar8074
- **Email ID:** lalan.k8977@gmail.com
- **Idenitfy yourself: ** GSSoC 2024 Contributor

Closes: #473 

### Describe the add-ons or changes you've made 📃

I've Enhanced the existing project by writing simpler beginner friendly code and added lots of model and ran lots of experiments to make sure that the model performs accurately.

## Type of change ☑️

- [ ] My code follows the beginner friendly code style in  this project.

## How Has This Been Tested? ⚙️

I've ran a lot of experiments and after careful evaluations i have concluded that this is the best performance of the model

## Checklist: ☑️
- [ ] My code follows the guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added things that prove my fix is effective or that my feature works.

### CODE REVIEW

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
Please do not remove all the existing files of the previous project folder. Instead update the existing files and add your codes there.

@kumar8074

**Comment by kumar8074** [comment]
@abhisheks008  should i just place my notebook inside the existing folder or should i write my codes in the existing notebook itself?

**Comment by abhisheks008** [comment]
> @abhisheks008 should i just place my notebook inside the existing folder or should i write my codes in the existing notebook itself?

Add up your code in the existing files/folder. No need to remove the existing files.

**Comment by abhisheks008** [comment]
You have used the same dataset right? Then download the notebook file, run the existing codes, put your model after the existing code, update the file.

**Comment by kumar8074** [comment]
> You have used the same dataset right? Then download the notebook file, run the existing codes, put your model after the existing code, update the file.

No as I've asked you earlier i have used the different dataset you can see it in the chat of issue #473 
Seems like you have assigned the same project to 2 persons...

**Comment by abhisheks008** [comment]
> @abhisheks008 But it's a complete notebook (ipynb) right and both the notebooks are completely different how can i just add my codes in the existing notebook??

My bad. If you completely remove the existing project then what about the contributor who contributed earlier that's against my ethics. It's better to put your files as well as the existing files together. In the README update your contributions along with the existing project.

**Comment by kumar8074** [comment]
> > @abhisheks008 But it's a complete notebook (ipynb) right and both the notebooks are completely different how can i just add my codes in the existing notebook??
> 
> My bad. If you completely remove the existing project then what about the contributor who contributed earlier that's against my ethics. It's better to put your files as well as the existing files together. In the README update your contributions along with the existing project.

got it

**Comment by kumar8074** [comment]
> > > @abhisheks008 But it's a complete notebook (ipynb) right and both the notebooks are completely different how can i just add my codes in the existing notebook??
> > 
> > 
> > My bad. If you completely remove the existing project then what about the contributor who contributed earlier that's against my ethics. It's better to put your files as well as the existing files together. In the README update your contributions along with the existing project.
> 
> got it

@abhisheks008 should i close this pull request and make a new one with updates??? or is there any way to update things in this pull request only???

**Comment by abhisheks008** [comment]
> > > > @abhisheks008 But it's a complete notebook (ipynb) right and both the notebooks are completely different how can i just add my codes in the existing notebook??
> > > 
> > > 
> > > My bad. If you completely remove the existing project then what about the contributor who contributed earlier that's against my ethics. It's better to put your files as well as the existing files together. In the README update your contributions along with the existing project.
> > 
> > 
> > got it
> 
> @abhisheks008 should i close this pull request and make a new one with updates??? or is there any way to update things in this pull request only???

Create a fresh PR for this.

**Pull request closed without merging**
