### PR TITLE
[README Enhancement]: Chocolate Classification using DL #526

### PR DESCRIPTION
**Pull request by mahi13singh2004**
# Pull Request for DL-Simplified 💡

## Issue Title : [README Enhancement]: Chocolate Classification using DL #526

- **Info about the related issue (Aim of the project)** : The aim is to enhance the README file and make it eye pleasing, well documented using the given README template.
- **Name:** Mahi Singh
- **GitHub ID:** mahi13singh2004
- **Email ID:** mahi13singh2004@gmail.com
- **Idenitfy yourself:** GSSoC'24 Contributor
Closes: #526 

### Describe the add-ons or changes you've made 📃
I've enhanced the README by incorporating visually appealing emoticons and providing concise explanations of the content. 

## Type of change ☑️
What sort of change have you made:
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## How Has This Been Tested? ⚙️
**Visual Inspection:** Ensured correct formatting and working links.
**Markdown Preview:**  Verified layout and appearance.

## Checklist: ☑️
- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by mahi13singh2004** [comment]
There is some error with 'visualisation' section, it says the image is no longer available!
error

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
Hi @mahi13singh2004 extract the images from the `ipynb` file, and put them together in the Images file. Then use them into the README file, this will work in this case.

**Comment by mahi13singh2004** [comment]
@abhisheks008 , Kindly check once. I found the image in /images section so directly used its link.

**Review by abhisheks008 — APPROVED** [review]
Approved! @mahi13singh2004

**Pull request merged**
