### PR TITLE
Myntra Fashion Product Analysis

### PR DESCRIPTION
**Pull request by CoderOMaster**
# Pull Request for DL-Simplified 💡

## Issue Title : 

- **Info about the related issue (Aim of the project)** : Image classficiation of clothes
- **Name:**  Keshav Arora
- **GitHub ID:** CoderOMaster
- **Email ID:** keshavarorasci@gmail.com
- **Idenitfy yourself: (Mention in which program you are contributing in. Eg. For a JWOC 2022 participant it's, `JWOC Participant`)** GSSOC 2024

Closes: #issue number that will be closed through this PR 413

### Describe the add-ons or changes you've made 📃

Give a clear description of what have you added or modifications made

## Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? ⚙️

Describe how it has been tested
Describe how have you verified the changes made

## Checklist: ☑️

- [ ] My code follows the guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
1. Put the accuracy graphs in the README file.
2. Inside Dataset folder the file name should be `README.md` instead of `dataset.md`. Also give a brief about the dataset there, not just putting the URL of the dataset.
3. Add more EDA results in the Images folder as well as in the README.

@CoderOMaster

**Comment by CoderOMaster** [comment]
@abhisheks008 I don't think so eda would be decent here since we have 36 classes..and imagine having 36 classes on pie or bar graph.it will be too conjested.

**Comment by CoderOMaster** [comment]
I did it anyways

**Comment by CoderOMaster** [comment]
@abhisheks008

**Review by abhisheks008 — APPROVED** [review]
Approved @CoderOMaster

**Pull request merged**
