### PR TITLE
Leukaemia Classification using DL

### PR DESCRIPTION
**Pull request by achrekarom12**
# Pull Request for DL-Simplified 💡

## Issue Title : Leukaemia Classification using DL

- **Info about the related issue (Aim of the project)** : To classify normal from abnormal cell images of Leukaemia.
- **Name:** Om Achrekar
- **GitHub ID:** achrekarom12
- **Email ID:** achrekarom@gmail.com
- **Idenitfy yourself: (Mention in which program you are contributing in. Eg. For a JWOC 2022 participant it's, `JWOC Participant`)** SSoC '23

Closes: #314 

### Describe the add-ons or changes you've made 📃

- Data collection: From the link of the dataset given above.
- Data preprocessing: Preprocessed the image in order to have all images in equal shape.
- Model selection: Chose three Image detection architecture VGG16, ResNet50 and Inception for Image detection.
- Comparative analysis: Compared the accuracy score of all the models.

## Type of change ☑️

What sort of change have you made:
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? ⚙️
The evaluation metrics I used to assess the models:

- Accuracy
- Loss

## Checklist: ☑️
- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by achrekarom12** [comment]
@abhisheks008 
I definitely agree that the approaches I used have quite a low accuracy between 65-70. This is because I have use only 1/3rd of the available data. The image processing were little difficult here because it was exhausting the whole RAM available. There were over a 10K images to be processed. In the notebook I have also mentioned the approach while taking whole dataset into consideration but commented it out. Please let me know if there's anything more I can do.
Thankyou!

**Comment by abhisheks008** [comment]
Anything else you can apply on this dataset? Accuracy of 70% is not less, but the standard you have fixed for the contributions, it seems below PAR accuracy.

Try to fix the accuracy atleast to 85-90 mark.
@achrekarom12

**Comment by achrekarom12** [comment]
I hope it would be good enough. Although I couldn't get near to 85 but overall the accuracy has been improved remarkably. Please let me know if any further improvements you need in this. Thankyou!

**Review by abhisheks008 — APPROVED** [review]
Your PR is approved and ready to be merged.
@achrekarom12

**Pull request merged**
