### PR TITLE
Emergency Fire detection

### PR DESCRIPTION
**Pull request by ADITYADAS1999**
# Pull Request for DL-Simplified 💡

## Issue Title : Emergency Fire detection #325

- **Info about the related issue (Aim of the project)** : Having a fire detection system can significantly reduce damages and maximize fire control efforts. It is also one of the most fundamental steps we can take for fire safety measures. Even if we are sleeping or in a busy working, area
- **Name:** Aditya Das
- **GitHub ID:** https://github.com/ADITYADAS1999
- **Email ID:** adityamca123@gmail.com
- **Idenitfy yourself: (Mention in which program you are contributing in. Eg. For a JWOC 2022 participant it's, `JWOC Participant`)** GSSOC 2023  participant 

Closes: #325 

### Describe the add-ons or changes you've made 📃

Give a clear description of what have you added or modifications made

## Type of change ☑️

What sort of change have you made:

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [X] Code style update (formatting, local variables)
- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] This change requires a documentation update

## How Has This Been Tested? ⚙️

Describe how it has been tested
Describe how have you verified the changes made

## Checklist: ☑️

- [X] My code follows the guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly wherever it was hard to understand.
- [X] I have made corresponding changes to the documentation.
- [X] My changes generate no new warnings.
- [X] I have added things that prove my fix is effective or that my feature works.
- [X] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by abhisheks008** [comment]
Please follow the project structure. Folder names should be given properly.
```
Dataset
Images
Model
requirements.txt
```

@ADITYADAS1999

**Comment by ADITYADAS1999** [comment]
> Please follow the project structure. Folder names should be given properly.
> 
> ```
> Dataset
> Images
> Model
> requirements.txt
> ```
> 
> @ADITYADAS1999

That's cool thanks for reviewing the PR. I will update all of them ASAP

**Comment by ADITYADAS1999** [comment]
> Please follow the project structure. Folder names should be given properly.
> 
> ```
> Dataset
> Images
> Model
> requirements.txt
> ```
> 
> @ADITYADAS1999

file_str


Hey @abhisheks008 

I did the request changes, can you review this a bit.

**Comment by ADITYADAS1999** [comment]
> 

🎉🎊

**Pull request merged**
