### PR TITLE
[Model Enhancement]: Leukaemia Classification using DL

### PR DESCRIPTION
**Pull request by Arihant-Bhandari**
# Pull Request for DL-Simplified 💡

## Issue Title : #569 Leukaemia Classification using DL

- **Info about the related issue (Aim of the project)** : adding CNN-Attention model for Leukaemia Classification
- **Name:** Arihant Bhandari
- **GitHub ID:** Arihant-Bhandari https://github.com/Arihant-Bhandari
- **Email ID:** arihant.bhandari.2004@gmail.com
- **Idenitfy yourself:** GSSoC 2024 Contributor

Closes: #569 Leukaemia Classification using DL
### Describe the add-ons or changes you've made 📃

Added the CNN-Attention model, added the Accuracy-Loss plot, enhanced README file, changed typos in Chocolate Classififcation using DL README alongside this project.

## Type of change ☑️

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## How Has This Been Tested? ⚙️

Accuracy: 85.8%
Loss: 0.39

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by Arihant-Bhandari** [comment]
hi @abhisheks008 please review this PR, thank you for your time and patience as always.

as required, changes have been made.

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
Add some headings with bullet points for listing the EDA images/accuracy graphs. It's difficult to understand which image is representing which model.

@Arihant-Bhandari

**Comment by Arihant-Bhandari** [comment]
hi @abhisheks008 pls review, made requested changes.

**Review by abhisheks008 — APPROVED** [review]
Approved and ready to be merged.
@Arihant-Bhandari

**Pull request merged**
