### PR TITLE
James Webb space telescope image analysis

### PR DESCRIPTION
**Pull request by Rohith2202**
# Pull Request for DL-Simplified 💡

## Issue Title : James Webb Space Telescope Image analysis 

- **Info about the related issue (Aim of the project)** : Image analysis using different libraries
- **Name:** Rohith
- **GitHub ID:** (https://github.com/Rohith2202)
- **Email ID:** 20bcs081@iiitdwd.ac.in
- **Idenitfy yourself: SSOC 2022

Closes: Issue no: 45

### Describe the add-ons or changes you've made 📃

Finished Image analysis using opencv and scikit image. Performed data extraction from image using sklearn and used opencv to find the laplacian derivatives of the image and to find the edges.

## Type of change ☑️

What sort of change have you made:

Example how to mark a checkbox:-
- [x] My code follows the code style of this project.
-->
- [] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? ⚙️

Describe how it has been tested
Describe how have you verified the changes made

## Checklist: ☑️

- [ x] My code follows the guidelines of this project.
- [ x] I have performed a self-review of my own code.
- [x ] I have commented my code, particularly wherever it was hard to understand.
- [x ] I have made corresponding changes to the documentation.
- [x ] My changes generate no new warnings.
- [x ] I have added things that prove my fix is effective or that my feature works.
- [ x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
Follow the pattern for representing the projects. You can check other projects here in this repo, how they have been arranged and all.

@Rohith2202

**Comment by Rohith2202** [comment]
Sir I wasn't able to follow the given format because file sizes were greater than 100MB. So i could upload only the code and dataset obtained from my image analysis

**Comment by abhisheks008** [comment]
There are three major folders in each of the projects,
1. Model - consists the `.ipynb` file and the README.md file.
2. Images - consists the visualization related images.
3. Dataset - consists the dataset of the project. If it exceeds 100MB put the URL in the README.md file.

Apart from these three, `requirements.txt` file is there, which stores the information related to the libraries used in this project.

In your case you are facing in uploading your visualization images, then take the screenshots of the visualization images and upload them one by one. This will work definitely. 

Remove all the unnecessary files and follow the pattern.
@Rohith2202

**Comment by Rohith2202** [comment]
Pls check it now

**Comment by abhisheks008** [comment]
@Rohith2202 Update the README.md using the following template, https://github.com/abhisheks008/DL-Simplified/blob/main/.github/readme_template.md

Otherwise it's a perfect project. Good job done 💯

**Comment by Rohith2202** [comment]
Changed the format of readme.md. Pls check now

**Review by abhisheks008 — APPROVED** [review]
Great work done by you @Rohith2202. Really appreciated your efforts for this project. Kudos to you on your first contribution in Deep Learning Simplified project repo.

Your PR is approved and merged ✅ 🎉

**Pull request merged**
