### PR TITLE
[Project Addition]: Computed Tomography Analysis Using DL project

### PR DESCRIPTION
**Pull request by Jaya-Prakash-17**
# Pull Request for DL-Simplified 💡

## Issue Title: Computed Tomography Analysis using DL #468 

- **Info about the related issue (Aim of the project)**: The goal of the project is to analyze CT scan images using DL techniques. 
- **Name:** Jaya Prakash Sangem
- **GitHub ID:** #122619482
- **Email ID:** 21211a7253@bvrit.ac.in
- **Identify yourself:** GsSOC 2024 Contributor

Closes: #468

### Describe the add-ons or changes you've made 📃

I have implemented the VGG16, ResNet50, and EfficientNetB7 models for CT image classification. 

## Type of change ☑️

What sort of change have you made:
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## How Has This Been Tested? ⚙️

I have tested the implementation using a separate test dataset and verified the classification accuracy of each model. Additionally, I have compared the results with the expected outcomes to ensure accuracy.

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by abhisheks008** [comment]
Hi @Jaya-Prakash-17 the models you have implemented are overfitted. 100% accuracy for all the three models is really phishy. Try to split the dataset into 60:40 parameter.

**Comment by Jaya-Prakash-17** [comment]
The dataset is too small i guess that is also the reason. Anyways I'll try using data augmentation. Thanks @abhisheks008 and is there anything else that i can try?

**Comment by abhisheks008** [comment]
> The dataset is too small i guess that is also one of the reasons. Anyways I'll try using data augmentation. Thanks @abhisheks008 and is there anything else that i can try?

Accuracy scores are bit catching the eyes! I mean you understand what I mean to say.

**Comment by Jaya-Prakash-17** [comment]
yeah sure! I'll definitly look into it!
ill take some more time and come back with better content.
Thank you @abhisheks008

**Comment by Jaya-Prakash-17** [comment]
# Pull Request for DL-Simplified 💡

## Issue Title: Computed Tomography Analysis using DL

- **Info about the related issue (Aim of the project)**: The aim of this project is to accurately classify medical diseases including tumors, cancer, and aneurysms from CT scan images by applying deep learning algorithms. The goal is to make it easier for medical practitioners to diagnose and treat patients.
- **Name:** Jaya Prakash Sangem
- **GitHub ID:** Jaya-Prakash-17
- **Email ID:** 21211a7253@bvrit.ac.in
- **Identify yourself:** GsSOC 2024 Contributor

Closes: #557

### Describe the add-ons or changes you've made 📃

I have developed deep learning models to analyze CT scan images of the brain and classify them into specific categories based on medical conditions detected. The project includes:
- Data collection and preprocessing.
- Exploratory data analysis to gain insights into the dataset.
- Implementation of deep learning models, including VGG16, ResNet50, and EfficientNetB7.
- Evaluation of model performance on training, validation, and test datasets.
- Comparison of model accuracies and selection of the best-performing model.

## Type of change ☑️

What sort of change have you made:
- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested? ⚙️

The models have been tested using training, validation, and test datasets. Performance metrics including accuracy, precision, recall, and F1-score were used to evaluate the models. Additionally, confusion matrices were generated to assess the classification performance.

## Checklist: ☑️
- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

**Pull request merged**
