### PR TITLE
README Enhancement - Cats vs Dogs Audio Classification using DL #488

### PR DESCRIPTION
**Pull request by Jeba-Rachel-Nesica**
# Pull Request for DL-Simplified 💡

## Issue Title : README Enhancement - Cats vs Dogs Audio Classification using DL #488 

- **Info about the related issue (Aim of the project)** : The aim is to enhance the README file and make it eye pleasing, well documented using the given README template.
- **Name:** JEBA RACHEL NESICA
- **GitHub ID:** 129723273
- **Email ID:** jebarachelnesica@gmail.com
- **Idenitfy yourself:** GSSoC'24 Contributor

Closes: #488

### Describe the add-ons or changes you've made 📃

Give a clear description of what have you added or modifications made

## Type of change ☑️

What sort of change have you made:
### Additions and Modifications

1. **Introduction Section**: Added an engaging introduction to provide an overview of the project.
2. **Table of Contents**: Included for improved navigation.
3. **Emoticons**: Added throughout the document to enhance visual appeal and engagement.
4. **Project Workflow**: Detailed the steps for better clarity, including data collection, preprocessing, model selection, and comparative analysis.
5. **Libraries Needed**: Provided installation commands and listed with emoticons.
6. **Visualization Section**: Added a brief description of what the spectrograms represent, along with a sample image.
7. **Future Work**: Suggested improvements and extensions, including data augmentation, hyperparameter tuning, and exploring additional models.
8. **Acknowledgements**: Added to give credit to the dataset source and library developers, and to foster community rapport.
9. **Engaging Closing**: Included a friendly closing statement encouraging interaction and contributions.

Example how to mark a checkbox:-
- [x] My code follows the code style of this project.
-->
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

### How Has This Been Tested?

- **Visual Inspection**: Ensured correct formatting and working links.
- **Markdown Preview**: Verified layout and appearance.

### How Have You Verified the Changes Made?

- **Consistency Check**: Ensured original information is retained.
- **Functional Verification**: Tested links and installation commands.

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
image

Image is not showing properly.
@Jeba-Rachel-Nesica

**Comment by abhisheks008** [comment]
> > Hi @Jeba-Rachel-Nesica any update on the requested changes?
> 
> I have pasted the image given in the original README to be enhanced as is to ensure no details are lost. What should I do?

Maybe there is some issue with the URL you are hyperlinking for the README.

**Comment by Jeba-Rachel-Nesica** [comment]
> > > Hi @Jeba-Rachel-Nesica any update on the requested changes?
> > 
> > 
> > I have pasted the image given in the original README to be enhanced as is to ensure no details are lost. What should I do?
> 
> Maybe there is some issue with the URL you are hyperlinking for the README.


> > > Hi @Jeba-Rachel-Nesica any update on the requested changes?
> > 
> > 
> > I have pasted the image given in the original README to be enhanced as is to ensure no details are lost. What should I do?
> 
> Maybe there is some issue with the URL you are hyperlinking for the README.

Checked the page is not found. Can I just remove that part alone?

**Comment by abhisheks008** [comment]
> > > > Hi @Jeba-Rachel-Nesica any update on the requested changes?
> > > 
> > > 
> > > I have pasted the image given in the original README to be enhanced as is to ensure no details are lost. What should I do?
> > 
> > 
> > Maybe there is some issue with the URL you are hyperlinking for the README.
> 
> > > > Hi @Jeba-Rachel-Nesica any update on the requested changes?
> > > 
> > > 
> > > I have pasted the image given in the original README to be enhanced as is to ensure no details are lost. What should I do?
> > 
> > 
> > Maybe there is some issue with the URL you are hyperlinking for the README.
> 
> Checked the page is not found. Can I just remove that part alone?

Okay

**Comment by Jeba-Rachel-Nesica** [comment]
> > > > > Hi @Jeba-Rachel-Nesica any update on the requested changes?
> > > > 
> > > > 
> > > > I have pasted the image given in the original README to be enhanced as is to ensure no details are lost. What should I do?
> > > 
> > > 
> > > Maybe there is some issue with the URL you are hyperlinking for the README.
> > 
> > 
> > > > > Hi @Jeba-Rachel-Nesica any update on the requested changes?
> > > > 
> > > > 
> > > > I have pasted the image given in the original README to be enhanced as is to ensure no details are lost. What should I do?
> > > 
> > > 
> > > Maybe there is some issue with the URL you are hyperlinking for the README.
> > 
> > 
> > Checked the page is not found. Can I just remove that part alone?
> 
> Okay

Done.

**Review by abhisheks008 — APPROVED** [review]
Approved @Jeba-Rachel-Nesica

**Pull request merged**
