### PR TITLE
Web Application for Alzheimers Detection

### PR DESCRIPTION
**Pull request by aindree-2005**
# Pull Request for DL-Simplified 💡

## Issue Title : Web Application for Alzheimers Detection #539 

- **Info about the related issue (Aim of the project)** : Web Application for Alzheimers Detection
- **Name:** Aindree
- **GitHub ID:** aindree2005
- **Email ID:** 
- **Idenitfy yourself: (Mention in which program you are contributing in. Eg. For a JWOC 2022 participant it's, `JWOC Participant`)**  GSSOC 2024

Closes: #539 
### Describe the add-ons or changes you've made 📃

Give a clear description of what have you added or modifications made

## Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## How Has This Been Tested? ⚙️

Describe how it has been tested
Describe how have you verified the changes made

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
Looks good to me. Add the video in the README file of the Web App folder, just like reference project given in the issue template.

For that, firstly upload a thumbnail for the video, then use this markdown script by putting thumbnail and video URL. Here is the script, `[](uploaded_video_url)`.

@aindree-2005

**Comment by aindree-2005** [comment]
> Looks good to me. Add the video in the README file of the Web App folder, just like reference project given in the issue template.
> 
> For that, firstly upload a thumbnail for the video, then use this markdown script by putting thumbnail and video URL. Here is the script, `[](uploaded_video_url)`.
> 
> @aindree-2005

@abhisheks008 made the change. Is it ok now? Had uploaded the demo.mp4 already

**Review by abhisheks008 — APPROVED** [review]
Looks good to me! Your PR is approved and ready to be merged.

I'll merge the PR by EOD.

@aindree-2005

**Comment by abhisheks008** [comment]
HI @aindree-2005 need a minor change. Can you represent the demo video like this, 
image

For your reference you can have a look at this project, [Brain Tumor Detection/Web App](https://github.com/abhisheks008/DL-Simplified/tree/main/Brain%20Tumor%20Detection/Web%20App)

**Comment by aindree-2005** [comment]
> Hi @aindree-2005 need a minor change. Can you represent the demo video like this, image
> 
> For your reference you can have a look at this project, [Brain Tumor Detection/Web App](https://github.com/abhisheks008/DL-Simplified/tree/main/Brain%20Tumor%20Detection/Web%20App)

I used the same syntax as here, but the preview is looking different in mine. If I embed the video as before thumbnail is no longer appearing

**Comment by abhisheks008** [comment]
Have you tried this syntax `[](<put the whole URL of the video>)`

**Comment by aindree-2005** [comment]
> Have you tried this syntax `[](<put the whole URL of the video>)`

Yes tried that with the permalink

**Comment by abhisheks008** [comment]
> > Have you tried this syntax `[](<put the whole URL of the video>)`
> 
> Yes tried that with the permalink

Still not getting the desired output?

**Comment by abhisheks008** [comment]
Hi @theiturhs sorry to bother you here. Can you help @aindree-2005 for getting the desired way to represent the demo video in the README, just like you did it in your pull request. Aindree is not getting the desired output after several tries with the markdown.

**Comment by Sgvkamalakar** [comment]
Hi @aindree-2005,

` Drag and drop` / `Copy-paste`  the video from your PC to the GitHub readme where you wish to paste it as a thumbnail.

**Comment by theiturhs** [comment]
@abhisheks008 Sure I can try

@aindree-2005 you can check this screenshot how I tried this

image

If nothing is working, 

Open your web browser and go to the GitHub repository where you want to edit the README file. Open it for editing. Try to drag the video from your local folder to README area and drop it into the README editing area. When you drop the video, some text representing the file path or URL might appear in the README. Adjust the markdown to properly embed the video (adjust the brackets). This is the easiest way. I hope this method will help you.

**Comment by aindree-2005** [comment]
> @abhisheks008 Sure I can try
> 
> @aindree-2005 you can check this screenshot how I tried this
> 
> image
> 
> If nothing is working,
> 
> Open your web browser and go to the GitHub repository where you want to edit the README file. Open it for editing. Try to drag the video from your local folder to README area and drop it into the README editing area. When you drop the video, some text representing the file path or URL might appear in the README. Adjust the markdown to properly embed the video (adjust the brackets). This is the easiest way. I hope this method will help you.

Thanks a lot! Trying that method rn

**Comment by aindree-2005** [comment]
> @abhisheks008 Sure I can try
> 
> @aindree-2005 you can check this screenshot how I tried this
> 
> image
> 
> If nothing is working,
> 
> Open your web browser and go to the GitHub repository where you want to edit the README file. Open it for editing. Try to drag the video from your local folder to README area and drop it into the README editing area. When you drop the video, some text representing the file path or URL might appear in the README. Adjust the markdown to properly embed the video (adjust the brackets). This is the easiest way. I hope this method will help you.

None of these worked, as video is not running in the markdown, it is always redirecting to concerned site

**Comment by aindree-2005** [comment]
Nvm fixed it. No idea why same glitch was showing for Github.dev but not on VS Code. @abhisheks008 is this fine now?

**Comment by abhisheks008** [comment]
> Nvm fixed it. No idea why same glitch was showing for Github.dev but not on VS Code. @abhisheks008 is this fine now?

Let me check.

**Comment by abhisheks008** [comment]
Nopes @aindree-2005 it's not working like the way others did.

**Comment by aindree-2005** [comment]
> Nopes @aindree-2005 it's not working like the way others did.

No idea why. It's working on VS Code Readme preview. I searched on google and it states that video src is the way but it doesn't work on all browsers. What should I do?

**Comment by Sgvkamalakar** [comment]
> > @abhisheks008 Sure I can try
> > @aindree-2005 you can check this screenshot how I tried this
> > image
> > If nothing is working,
> > Open your web browser and go to the GitHub repository where you want to edit the README file. Open it for editing. Try to drag the video from your local folder to README area and drop it into the README editing area. When you drop the video, some text representing the file path or URL might appear in the README. Adjust the markdown to properly embed the video (adjust the brackets). This is the easiest way. I hope this method will help you.
> 
> None of these worked, as video is not running in the markdown, it is always redirecting to concerned site

Hi @aindree-2005,

 Drag and drop / Copy-paste the video from your PC to the GitHub readme where you wish to paste it as a thumbnail.

**Comment by aindree-2005** [comment]
> > > @abhisheks008 Sure I can try
> > > @aindree-2005 you can check this screenshot how I tried this
> > > image
> > > If nothing is working,
> > > Open your web browser and go to the GitHub repository where you want to edit the README file. Open it for editing. Try to drag the video from your local folder to README area and drop it into the README editing area. When you drop the video, some text representing the file path or URL might appear in the README. Adjust the markdown to properly embed the video (adjust the brackets). This is the easiest way. I hope this method will help you.
> > 
> > 
> > None of these worked, as video is not running in the markdown, it is always redirecting to concerned site
> 
> Hi @aindree-2005,
> 
> Drag and drop / Copy-paste the video from your PC to the GitHub readme where you wish to paste it as a thumbnail.

Does this redirect to the video in the markdown? Not working for me. It always opens video separately

**Comment by Sgvkamalakar** [comment]
> > > > @abhisheks008 Sure I can try
> > > > @aindree-2005 you can check this screenshot how I tried this
> > > > image
> > > > If nothing is working,
> > > > Open your web browser and go to the GitHub repository where you want to edit the README file. Open it for editing. Try to drag the video from your local folder to README area and drop it into the README editing area. When you drop the video, some text representing the file path or URL might appear in the README. Adjust the markdown to properly embed the video (adjust the brackets). This is the easiest way. I hope this method will help you.
> > > 
> > > 
> > > None of these worked, as video is not running in the markdown, it is always redirecting to concerned site
> > 
> > 
> > Hi @aindree-2005,
> > Drag and drop / Copy-paste the video from your PC to the GitHub readme where you wish to paste it as a thumbnail.
> 
> Does this redirect to the video in the markdown? Not working for me. It always opens video separately

The video will be played within the markdown file and it worked. Check out the video below

https://github.com/abhisheks008/DL-Simplified/assets/103712713/67330ffa-b2a6-4535-89bf-45ae4d4bdb2f

**Comment by aindree-2005** [comment]
I tried this way. Is it working?
## Video Demo📽️
alt text

[Watch Video Demo](https://github.com/aindree-2005/DL-Simplified/blob/09981913e1373a30b62b5acd3ce79301f5900041/Alzheimers%20Detection/Web-App/demo.mp4)

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
Nopes it's just hyperlinking the video file, this way it can't be played inside the README.

**Comment by abhisheks008** [comment]
Hi @aindree-2005 fixed that issue regarding the demo video. You need to drag and drop the recorded video from your system to GitHub README file directly. That's all you have to do. You can try this in your forked repo.

**Pull request merged**
