### PR TITLE
[Project Addition]:Traffic Sign Recognition

### PR DESCRIPTION
**Pull request by aaradhyasinghgaur**
# Pull Request for DL-Simplified 💡

## Issue Title :  Traffic Sign Recognition 

- **Info about the related issue (Aim of the project)** : To detect Traffic signs using DL models
- **Name:** Aaradhya Singh
- **GitHub ID:** https://github.com/kyra-09
- **Email ID:** aaradhyasinghgaur@gmail.com
- **Idenitfy yourself: (Mention in which program you are contributing in. Eg. For a JWOC 2022 participant it's, `JWOC Participant`)** : GSSOC-2024 Contributor

Closes: #597 

### Describe the add-ons or changes you've made 📃
1.) Used Transfer learning and trained  and analysed models such as  VGG16 , ResNet50 etc. for the specified dataset.
2.) used data_augmentation techniques to increase accuracy and the performance of models.
3.)Perfromed EDA to understand dataset.
4.) compared accuracy scores of models using accuarcy score and graph visualization.

Give a clear description of what have you added or modifications made

## Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? ⚙️

Describe how it has been tested
Describe how have you verified the changes made

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by kyra-09** [comment]
@abhisheks008 kindly review my pr

**Comment by abhisheks008** [comment]
image

All the three models are having indentation errors in README.

**Comment by kyra-09** [comment]
Requested changes are done @abhisheks008

**Review by abhisheks008 — APPROVED** [review]
Approved @kyra-09

**Pull request merged**
