### PR TITLE
[Project Addition] Rock Formation Classification using DL

### PR DESCRIPTION
**Pull request by Arihant-Bhandari**
# Pull Request for DL-Simplified 💡

## Issue Title : #729 Rock Formation Classification using DL 

- **Info about the related issue (Aim of the project)**: Classifying rock formations into Igneous, Metamorphic and sedimentary types.
- **Name:** Arihant Bhandari
- **GitHub ID:** https://github.com/Arihant-Bhandari
- **Email ID:** arihant.bhandari.2004@gmail.com
- **Idenitfy yourself:** GSSoC 2024 Contributor

Closes: #729 Rock Formation Classification using DL

### Describe the add-ons or changes you've made 📃

Wrote code for preprocessing and loading images from Dataset, turned labels into probability distributions, created models including custom CNN as well as pre-trained models, like ResNet-50, VGG16 and so on.

## Type of change ☑️

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## How Has This Been Tested? ⚙️

| Models | Accuracy | Loss |
|--------|---------------------|--------------------------|
| ResNet-50 | 27.73% | 11.6480 |
| InceptionV3 | 56.09%  | 0.9833 | 
| CNN | 54.76% | 0.9459 |
| VGG16 | 59.73% | 0.9362 |
| EfficientNetB7 | 37.51% | 1.0937 |
| DenseNet-121 | 61.87% | 0.8813 |
| Xception | 58.76% | 0.9247 |

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by Arihant-Bhandari** [comment]
hi @abhisheks008 pls check this PR, if any changes to be made, will gladly do them over.

thank you for your time and patience.

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
Accuracy scores are not up to the mark. Need to implement at least one model with an accuracy score to more than 90%.

@Arihant-Bhandari

**Comment by Arihant-Bhandari** [comment]
hi @abhisheks008 i have tried out various strategies, and unfortunately couldnt come up with a suitable result. i hope this issue can be sidelined for now, i will try other things on this dataset like vision transformers and stuff, but for now i hope this issue can be sidelined.

i have completed the other project , about arabic dates, and i can hand that in today. i hope you can allow me this switch.

**Comment by abhisheks008** [comment]
> hi @abhisheks008 i have tried out various strategies, and unfortunately couldnt come up with a suitable result. i hope this issue can be sidelined for now, i will try other things on this dataset like vision transformers and stuff, but for now i hope this issue can be sidelined.
> 
> i have completed the other project , about arabic dates, and i can hand that in today. i hope you can allow me this switch.

Okay!

**Comment by Arihant-Bhandari** [comment]
hi @abhisheks008 , wanted to update you on this, i have implemented a MoCo model on it for self supervised learning technique, and i am straightening out rough parts, i hope this implementation of MoCo can be regarded as USP of this project.

**Comment by Arihant-Bhandari** [comment]
hi @abhisheks008 , i wanted to talk abt this project's current progress: so the model has been trained, with a updation priority queue format under Momentum Contrast technique, but there isnt an increase in the accuracy score, i am getting a score of about 52% accuracy thru it. 

i wanted to ask for your opinion on this: would u allow submission of this project as it stands considering the MoCo implementation as a USP, or do we shut it down becuase there isnt that much variability for a CNN to properly capture features as far as i have seen. whatever you think i am ok with it, pls let me know your thoughts on it

**Comment by abhisheks008** [comment]
> hi @abhisheks008 , i wanted to talk abt this project's current progress: so the model has been trained, with a updation priority queue format under Momentum Contrast technique, but there isnt an increase in the accuracy score, i am getting a score of about 52% accuracy thru it.
> 
> i wanted to ask for your opinion on this: would u allow submission of this project as it stands considering the MoCo implementation as a USP, or do we shut it down becuase there isnt that much variability for a CNN to properly capture features as far as i have seen. whatever you think i am ok with it, pls let me know your thoughts on it



> hi @abhisheks008 , i wanted to talk abt this project's current progress: so the model has been trained, with a updation priority queue format under Momentum Contrast technique, but there isnt an increase in the accuracy score, i am getting a score of about 52% accuracy thru it.
> 
> i wanted to ask for your opinion on this: would u allow submission of this project as it stands considering the MoCo implementation as a USP, or do we shut it down becuase there isnt that much variability for a CNN to properly capture features as far as i have seen. whatever you think i am ok with it, pls let me know your thoughts on it

Yes getting an accuracy of 52% is not enough for this problem statement. Closing this issue as not reaching the threshold of accuracy score.

**Pull request closed without merging**
