### PR TITLE
Track fault detection using DL

### PR DESCRIPTION
**Pull request by the-silent-geek**
# Pull Request for DL-Simplified 💡

## Issue Title :  Track fault detection using DL

- **Info about the related issue (Aim of the project)** : To create deep learning models for railway track fault detection.
- **Name:** Dammala Uday Kiran
- **GitHub ID:** the-silent-geek
- **Email ID:** udaykir3911@gmail.com
- **Idenitfy yourself: (Mention in which program you are contributing in. Eg. For a JWOC 2022 participant it's, `JWOC Participant`)** : contributor SWOC 24

Closes: #224 

### Describe the add-ons or changes you've made 📃

Added dataset, accuracy plots, and 5 models for fault detection.

## Type of change ☑️

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? ⚙️

Describe how it has been tested
Describe how have you verified the changes made

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
image

If I merge this PR, it will remove all these files.

**Comment by the-silent-geek** [comment]
Sorry, I think the other folder with the same name has been deleted. I will add it to the PR.

**Comment by the-silent-geek** [comment]
I have added the previous folder and all its components

**Review by abhisheks008 — APPROVED** [review]
Nice work. Your PR is approved and ready to be merged.
@the-silent-geek

**Pull request merged**
