### PR TITLE
README Enhancement - CCTV Human Detection

### PR DESCRIPTION
**Pull request by aindree-2005**
# Pull Request for DL-Simplified 💡

## Issue Title :  #486 Update Readme for CCTV Human Detection

- **Info about the related issue (Aim of the project)** : 
- **Name:**   Aindree Chatterjee
- **GitHub ID:**  aindree2005
- **Email ID:** 
- **Idenitfy yourself: ** `GSSOC 2024`

Closes: #486 

### Describe the add-ons or changes you've made 📃
Worked to change markdown and linked everything properly

## Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## How Has This Been Tested? ⚙️
Markdown preview

## Checklist: ☑️

- [x]  My code follows the guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly wherever it was hard to understand.
- [x]  I have made corresponding changes to the documentation.
- [x]  My changes generate no new warnings.
- [x]  I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
1. Please put the added images inside the Images folder.
2. Need to fix the following indentation,
image
3. Also can you please change the project name from `CCTV-HUMAN-DETECTION` to `Human Detection using CCTV Footages`.

**Comment by aindree-2005** [comment]
@abhisheks008 fixed these in the recent commits. Please let me know if this is ok

**Comment by abhisheks008** [comment]
Remove the dot (.) from the project name.

**Comment by aindree-2005** [comment]
> Remove the dot (.) from the project name.

Removed it. Sorry about that.

**Review by abhisheks008 — APPROVED** [review]
Looks good to me. Your PR is approved and ready to be merged @aindree-2005.

**Pull request merged**
