### PR TITLE
Twitter Sentiment Analysis using NLP

### PR DESCRIPTION
**Pull request by aindree-2005**
# Pull Request for DL-Simplified 💡

## Issue Title : 
#221 
- **Info about the related issue (Aim of the project)** : 
- **Name:**  Aindree Chatterjee
- **GitHub ID:**  aindree-2005
- **Email ID:**  aindree2005@gmail.com
- **Idenitfy yourself: (Mention in which program you are contributing in. Eg. For a JWOC 2022 participant it's, `JWOC Participant`)**  CodePeak 2023

Closes: #221 

### Describe the add-ons or changes you've made 📃

Give a clear description of what have you added or modifications made
Added Project for twitter sentiment analysis
## Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? ⚙️

Describe how it has been tested
Describe how have you verified the changes made

On kaggle, code isn't breaking anything

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
Well @aindree-2005 the models you have put in for this project are good enough to do the job. I'll prefer having a model with accuracy score more than 85%. Can you find out some models which are having 85% score?

**Comment by aindree-2005** [comment]
Sure let me retry with bert

**Comment by aindree-2005** [comment]
@abhisheks008 added BERT. 87% Accuracy.

So, final round up is BERT- 87%, LSTM- 78%, Sequential Model- 72%

**Review by abhisheks008 — APPROVED** [review]
Looks perfect now. Your PR is approved and ready to be merged.
@aindree-2005

**Pull request merged**
