### PR TITLE
[Enhancement] Railway Track Fault Detection using Deep Learning

### PR DESCRIPTION
**Pull request by PiyushBL45t**
# Pull Request for DL-Simplified 💡

## Issue Title : [Enhancement] Railway Track Fault Detection
- **Info about the related issue (Aim of the project)** : To detect the faults in the railway tracks using Deep Learning Algorithms
- **Name:** Piyush Bhujbal
- **GitHub ID:** https://github.com/PiyushBL45t
- **Email ID:** bhujbalpiyush@gmail.com
- **Idenitfy yourself:**  Contributor at social Sumer of Code

Closes: #278 
### Describe the add-ons or changes you've made 📃
1. The dataset was not properly built. So,  created a script that renamed and annotated the images and then converted them into NumPy arrays for model training.
2.  Performed visualizations on the images using scikit-image library, OpenCV and Matplotlib.
3.  Performed image preprocessing and reshaping for training purposes.

## Type of change ☑️

What sort of change have you made:

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [X] Code style update (formatting, local variables)
- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] This change requires a documentation update

## How Has This Been Tested? ⚙️
1. Implemented three algorithms for the model training purposes.
    - Normal CNN
    - EfficientNet50
    - InceptionV3
2. Checked their accuracy and training time.
3. Plotted all the loss and accuracy graphs of all three algorithms.
4. Performed detection for testing the images for each model.

## Checklist: ☑️

- [X] My code follows the guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly wherever it was hard to understand.
- [X] I have made corresponding changes to the documentation.
- [X] My changes generate no new warnings.
- [X] I have added things that prove my fix is effective or that my feature works.
- [X] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
You have enhanced the performance of the existing project or, have created a new project based on a new dataset?

@PiyushBL45t

**Comment by PiyushBL45t** [comment]
I have enhanced the existing project.

**Comment by abhisheks008** [comment]
Please update the files in the existing project then, no need to create a separate project folder for this. Enhancement means you are enhancing the existing project by increasing the accuracy, so you can just re-configure the existing project.

@PiyushBL45t

**Comment by PiyushBL45t** [comment]
Okay will do

**Pull request closed without merging**
