### PR TITLE
Hand Navigation Landmarks Detection

### PR DESCRIPTION
**Pull request by utsabsamadder**
# Pull Request for DL-Simplified 💡

## Issue Title : Hand Navigation Landmarks Detection

- **Info about the related issue (Aim of the project)** : Hand Navigation Landmark Detection Using YOLOv8
- **Name:** Utsab Samadder
- **GitHub ID:** https://github.com/utsabsamadder
- **Email ID:** utsab.samadder@gmail.com
- **Idenitfy yourself: (Mention in which program you are contributing in. Eg. For a JWOC 2022 participant it's, `JWOC Participant`)** I am participating in GSSoC 2024 and i was contributing to issue #523

Closes: #523 

### Describe the add-ons or changes you've made 📃

Give a clear description of what have you added or modifications made

I have used YOLOv8 to address the change. First, it was necessary to make a dataset as the dataset given in the issue is Vectorized but YOLO can't work on that. Once the dataset has been created I had to annotate it and then use Google Colab to create best.pt. Using best.pt we need to write a python program with data.yaml file to classify various instances. The .py file program has been put in the readme section.

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? ⚙️

To test simply follow the process given in the readme file

## Checklist: ☑️

- [ x] My code follows the guidelines of this project.
- [ x] I have performed a self-review of my own code.
- [x ] I have commented my code, particularly wherever it was hard to understand.
- [ x] I have made corresponding changes to the documentation.
- [x ] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by abhisheks008 — COMMENTED** [review]
image

Due to this technical glitch I am not able to review the PRs. Let's wait for sometime and hope this issue will fix ASAP.
@utsabsamadder

**Comment by utsabsamadder** [comment]
No worries at all :)

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
1. Follow the project structure and manage your files, folders accordingly.
2. Update the project folder name as per the Issue name. Eg. `Hand Navigation Landmarks Detection`
3. Please follow the README template and update the same.
4. In the issue's comment section you have mentioned that you'll implement different models/methods and showcase the accuracy scores of the models, based on that you'll conclude which model is the best fitted one.
5. Need to do some EDA with the dataset.
6. Add a folder as `Images` and put all the EDA results, accuracy graphs, confusion matrices there.

Need major changes in the project structure. Please look in to it.
@utsabsamadder

**Comment by utsabsamadder** [comment]
@abhisheks008 where can I get the Readme template?

**Comment by abhisheks008** [comment]
> @abhisheks008 where can I get the Readme template?

https://github.com/abhisheks008/DL-Simplified/tree/main/.github

**Comment by abhisheks008** [comment]
image
Fix this documentation error

image
Image not showing

Only YOLO is used, no other architectures are not implemented here.

**Comment by utsabsamadder** [comment]
Wait I still had to add other models 🥹
But thnx anyways

**Comment by abhisheks008** [comment]
Ahhhhhh! I thought you are done with this.

**Pull request merged**
