### PR TITLE
Chocolate Classification using DL

### PR DESCRIPTION
**Pull request by Arihant-Bhandari**
# Pull Request for DL-Simplified 💡

## Issue Title : #553 [Model Enhancement]: Chocolate Classification using DL

- **Info about the related issue (Aim of the project)** : Enhancing the CNN model with Attention mechanism
- **Name:** Arihant Bhandari
- **GitHub ID:** Arihant-Bhandari https://github.com/Arihant-Bhandari
- **Email ID:** arihant.bhandari.2004@gmail.com
- **Idenitfy yourself:** GSSoC 2024 Contributor

Closes: #553 [Model Enhancement]: Chocolate Classification using DL
### Describe the add-ons or changes you've made 📃

introduced a new CNN architecture incorporating NADAM and ELU as optimizer and activation respectively, attention mechanism on overall model, changed data loading mechanism, introduced true image-extension checking allowing removal of unwanted images based on extensions like .webp, increased metrics. To prevent overfitting L2 regularizer or Ridge Regression is introduced to the model.

## Type of change ☑️

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## How Has This Been Tested? ⚙️

Following metrics were used to evaluate the performance of the model:

Testing metrics on model:

**Accuracy**: 0.9696969696969697
**Precision**: 0.9090909090909091
**Recall**: 1.0
**F1 Score**: 0.9523809523809523
**Confusion Matrix**:
 [[22  1]
 [ 0 10]]
**AUC**: 0.9782608695652174

**Testing Loss**: 0.3878534436225891

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by Arihant-Bhandari** [comment]
@abhisheks008 hi, i have started the PR, pls check codebase, if any issues, discrepancies or errors, i would be more than glad to correct. if any suggestions regarding commenting and all, i would be glad to hear them. Thank you for your time reviewing.

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
Have you removed the existing `.ipynb` file? Please add your code into the existing file and enhance the project. No need to remove the existing project. Please update the notebook file.

@Arihant-Bhandari

**Comment by Arihant-Bhandari** [comment]
@abhisheks008 hi, as told, i have updated things into the original file, updated README with metrics and image, as well as enhanced readability of the README, mentioned enhancers with name and GITHUB-ID. the model, the .ipynb file and README have been sent as part of evaluation, pls check. thank you for your time and patience.

**Comment by Arihant-Bhandari** [comment]
ahh finally got what you talked abt on editing OG file, so sorry for this i guess i must have set outputs back to nill, i will correct this followup , extremely sorry for this mixup.

**Comment by abhisheks008** [comment]
> ahh finally got what you talked abt on editing OG file, so sorry for this i guess i must have set outputs back to nill, i will correct this followup , extremely sorry for this mixup.

No problem.

**Comment by Arihant-Bhandari** [comment]
hi @abhisheks008 as told, re-did things, re-did README, enhanced README, added acc image, added saved model. file is the original with my work as well as graph code for just poltting accuracy. i also added signatures with ID's for both readme and model enhancement.

also i wanted to ask if you could edit the README on both this as well as Colour Detection using DL, the attached images have not been configured to display CNN Attention acc graph, pls edit both README.md files.

thank you for your time and patience.

**Comment by abhisheks008** [comment]
> hi @abhisheks008 as told, re-did things, re-did README, enhanced README, added acc image, added saved model. file is the original with my work as well as graph code for just poltting accuracy. i also added signatures with ID's for both readme and model enhancement.
> 
> also i wanted to ask if you could edit the README on both this as well as Colour Detection using DL, the attached images have not been configured to display CNN Attention acc graph, pls edit both README.md files.
> 
> thank you for your time and patience.

If you wish you can do the changes, this will help you get an upgradation in the level of the issue. It's an opportunity for you to make this contribution as Level 3.
@Arihant-Bhandari

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
image

Please fix this issue.

**Comment by Arihant-Bhandari** [comment]
> > hi @abhisheks008 as told, re-did things, re-did README, enhanced README, added acc image, added saved model. file is the original with my work as well as graph code for just poltting accuracy. i also added signatures with ID's for both readme and model enhancement.
> > also i wanted to ask if you could edit the README on both this as well as Colour Detection using DL, the attached images have not been configured to display CNN Attention acc graph, pls edit both README.md files.
> > thank you for your time and patience.
> 
> If you wish you can do the changes, this will help you get an upgradation in the level of the issue. It's an opportunity for you to make this contribution as Level 3. @Arihant-Bhandari

hi so the thing is, when i originally pushed the file, the link in the Colour Detection README was for the bin in my own repo, on pusing the link changed to DL-Simplified bin, so if i want to add changes to that i would have to be issuing a README Enhancement issue for it. similarly for Chocolate detection, thats the issue with image you have tagged as change. my code file is ready i have made all the necessary changes for this issue's completion.


hence i would like to know your opinion on the grading scheme for these PRs, would you allow another issue to be raised  for both project's README enhancements for images at same time in single issue ?


thanks for listening

**Comment by Arihant-Bhandari** [comment]
the image bin link is not updated dynamically on push to this repo's image directory, so if you go back to Colour Detection using DL folder, the README would have CNN-Attention image missing since the link is set on my cloned repo, which is not getting picked due to different repos.

**Comment by Arihant-Bhandari** [comment]
i was checking up on things in the repo and noticed this, hence leaving the Chocolate classification README with empty link so that a new issue can be raised and committed to setting link properly

**Comment by Arihant-Bhandari** [comment]
would you accept raising this issue to level3 if i were to say, update that README in this PR ? so this PR would finally include edited .ipynb file with CNN-ATTENTION, model for this, readme file with missing picture link whcih i will update in the next proeject i had asked you for , and finally the image file for this project.

**Comment by abhisheks008** [comment]
If you can do the changes in this PR itself then only it can be raised to Level 3. If you are planning to enhance the READMEs by creating separate issues then, you'll get 1 point each for every README enhancement. Project admins had a clear discussion with the core team regarding the README enhancment issues, as many are using generative scripts and making changes in the README. That's why I am not accepting any README enhancement issues from the contributors.

**Comment by Arihant-Bhandari** [comment]
Ohhhh , cool then , I will edit the colour detection README , push in this PR and let you know , thanks for replying @abhisheks008

**Comment by Arihant-Bhandari** [comment]
@abhisheks008 i have edited the files as required, kindly review and approve the PR, thank you for your time and patience in guiding me ❤️.

**Comment by Arihant-Bhandari** [comment]
@abhisheks008 i have changed the README so that it can pick up the image from your end as soon as this PR is merged, i just configured the paths pointing towards your file which is currently nonexistent but will start existing on PR merge. the image is one of the commits i am pushing in this PR.

**Comment by abhisheks008** [comment]
> image
> 
> Please fix this issue.

Hi @Arihant-Bhandari this issue is not fixed yet! :(

**Comment by Arihant-Bhandari** [comment]
Hi, the issue is coming up because the link is the future repo's link , the moment this PR is pushed , the link will be active to be displayed on the README

**Comment by Arihant-Bhandari** [comment]
If I were to add the link on my repo and push it will not be able to trace back the link to pushed files, that's why I have made things so that the moment this PR is pushed , things start working on the README.md end.

**Comment by abhisheks008** [comment]
No need to put that, use the existing/current URL, GitHub will automatically fix that once that is merged in the main repo.

**Comment by Arihant-Bhandari** [comment]
@abhisheks008 hi , I have fixed the all issues , pls check

Appropriate files have been added , README for colour detection has been corrected , README for chocolate detection has been enhanced , best model for CNN-Attention has been added as part of submission along side original code and ACCURACY graph for CNN-Attention

**Review by abhisheks008 — APPROVED** [review]
Phew! Your PR is approved and ready to be merged.
@Arihant-Bhandari 

Show some love and support by starring this repository 🌟

**Comment by Arihant-Bhandari** [comment]
thank you for your time and patience for this project, really glad to work on this

**Pull request merged**
