### PR TITLE
Sudoku Solver added

### PR DESCRIPTION
**Pull request by ashis2004**
#856 resolved

### CODE REVIEW

**Comment by ashis2004** [comment]
pls @abhisheks008 check it

**Comment by abhisheks008** [comment]
Follow the pull request template and create a fresh PR.

**Comment by ashis2004** [comment]
other things are good.. right?

**Comment by abhisheks008** [comment]
You need to follow the project structure as well. Here is the structure you should follow,
```
Project Folder
|- Dataset
   |- dataset.csv (dataset used for the particula project)
   |- README.md (brief about the dataset)
|- Images
   |- img1.png
   |- img2.png
   |- img3.png
|- Model
   |- project_folder.ipynb
   |- README.md
|- Web App (Web App is optional)
   |- templates
   |- static
   |- app.py
   |- demo.mp4
   |- README.md
|- requirements.txt
```

**Pull request closed without merging**
