### PR TITLE
README Enhancement - Avocados Classification

### PR DESCRIPTION
**Pull request by mariam7084**
# Pull Request for DL-Simplified 💡

## Issue Title : README Enhancement - Avocados Classification

- **Info about the related issue (Aim of the project)** : readme modification according to template
- **Name:** Mariam
- **GitHub ID:** github.com/mariam7084
- **Email ID:** mariammanaullah1503@gmail.com
- **Idenitfy yourself: ** DWoC 2023

Closes: #472 

### Describe the add-ons or changes you've made 📃

Give a clear description of what have you added or modifications made

## Type of change ☑️

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## How Has This Been Tested? ⚙️
 checked the preview of the modified readme to ensure better and appealing look
## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by abhisheks008** [comment]
Hi @mariam7084 can you add some EDA results from the project and put them in the README file. Also try out the new README template, use emojis to make it attractive, https://github.com/abhisheks008/DL-Simplified/blob/main/.github/readme_template.md

**Comment by mariam7084** [comment]
@abhisheks008 
added emojis and images of evaluation metrics of the models implemented as no images as a result of EDA were found.

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
image

Please fix the orientation.

**Comment by mariam7084** [comment]
@abhisheks008 
orientation fixed.

**Review by abhisheks008 — APPROVED** [review]
Approved @mariam7084 under DWOC.

**Pull request merged**
