### PR TITLE
GAN-based Art Generator using Deep learning

### PR DESCRIPTION
**Pull request by alo7lika**
# Pull Request for DL-Simplified 💡

## Issue Title : GAN-based Art Generator using Deep Learning

- **Info about the related issue (Aim of the project)** : The aim is to implement a Generative Adversarial Network (GAN) to generate synthetic artistic images that resemble real artworks.
- **Name:** Alolika Bhowmik
- **GitHub ID:** https://github.com/alo7lika
- **Email ID:** alolikabhowmik72@gmail.com
- **Identify yourself:** GSSOC Contributor Ext 24

Closes: #954

### Describe the add-ons or changes you've made 📃

Added a complete GAN-based Art Generator implementation, including the generator and discriminator architectures, training process, and usage instructions in the README.

## Type of change ☑️

What sort of change have you made:
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? ⚙️

The GAN was trained on a synthetic dataset of artistic images, and the generated outputs were visually inspected for quality and uniqueness.

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
1. Can you mention the URL of the dataset you are using here?
2. Remove the `Images/Image` file.
3. Please follow the `README.md` template and update the `README` accordingly.
4. You have mentioned that you'll be using 3-4 GAN based models for this project while taking this issue, can you please put some light on it.

@alo7lika

**Comment by alo7lika** [comment]
> 1. Can you mention the URL of the dataset you are using here?
> 2. Remove the `Images/Image` file.
> 3. Please follow the `README.md` template and update the `README` accordingly.
> 4. You have mentioned that you'll be using 3-4 GAN based models for this project while taking this issue, can you please put some light on it.
> 
> @alo7lika

Done @abhisheks008

**Comment by alo7lika** [comment]
> > 1. Can you mention the URL of the dataset you are using here?
> > 2. Remove the `Images/Image` file.
> > 3. Please follow the `README.md` template and update the `README` accordingly.
> > 4. You have mentioned that you'll be using 3-4 GAN based models for this project while taking this issue, can you please put some light on it.
> > 
> > @alo7lika
> 
> Done @abhisheks008

@abhisheks008

**Comment by alo7lika** [comment]
> > 1. Can you mention the URL of the dataset you are using here?
> > 2. Remove the `Images/Image` file.
> > 3. Please follow the `README.md` template and update the `README` accordingly.
> > 4. You have mentioned that you'll be using 3-4 GAN based models for this project while taking this issue, can you please put some light on it.
> > 
> > @alo7lika
> 
> Done @abhisheks008

@abhisheks008 kindly check the PR ASAP

**Comment by alo7lika** [comment]
@abhisheks008 kindly check the PR

**Comment by alo7lika** [comment]
> 1. Can you mention the URL of the dataset you are using here?
> 2. Remove the `Images/Image` file.
> 3. Please follow the `README.md` template and update the `README` accordingly.
> 4. You have mentioned that you'll be using 3-4 GAN based models for this project while taking this issue, can you please put some light on it.
> 
> @alo7lika

Solved all the conflicts. Kindly Check the PR

**Comment by Scholarscribe** [comment]
@alo7lika please add hacktober fest tag to this PR.

**Comment by alo7lika** [comment]
> @alo7lika please add hacktober fest tag to this PR.

I cant add labels only @abhisheks008  can

**Comment by alo7lika** [comment]
> @abhisheks008 kindly check the PR AND MERGE IT AND ALSO ADD LABELS

@sanjay-kv Kindly review the task since @abhisheks008 is not reviewing the task

**Review by abhisheks008 — APPROVED** [review]
Approved.

**Pull request merged**
