### PR TITLE
Spam Vs Ham Mail Classification [With Streamlit GUI] 

### PR DESCRIPTION
**Pull request by dipayan22**
# Pull Request for DL-Simplified 💡

## Issue Title : Spam Vs Ham Mail Classification [With Streamlit GUI] #329

- **Info about the related issue (Aim of the project)** : ML project with a Streamlit GUI that will predict whether the Mail received from some source is a Spam Mail or not
- **Name:** Dipayan Majumder
- **GitHub ID:** dipayan22
- **Email ID:** majumderd007@gmail.com
- **Idenitfy yourself: (Mention in which program you are contributing in. Eg. For a JWOC 2022 participant it's, `JWOC Participant`)** SWOC 24

Closes: #issue number that will be closed through this PR

### Describe the add-ons or changes you've made 📃

Give a clear description of what have you added or modifications made

## Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? ⚙️

Describe how it has been tested
Describe how have you verified the changes made

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by abhisheks008** [comment]
Hi @dipayan22 the project is working fine. Need to upgrade the README file by adding the EDA results under the Visualization tag, use `<heading>` tags for the topics, create a table consisting all the accuracy scores of the models, find a brief conclusion of the project.

**Comment by dipayan22** [comment]
Yes i have used Streamlit GUI . In every notebook file at the last i made a Streamlit GUI for this project.

**Comment by dipayan22** [comment]
Do I have to make a separate .py file for making the Streamlit GUI in the Model folder?

**Comment by abhisheks008** [comment]
> Do I have to make a separate .py file for making the Streamlit GUI in the Model folder?

That will be better.

**Comment by dipayan22** [comment]
File updated .

**Comment by abhisheks008** [comment]
image

I think you missed to add the EDA results (images) under the EDA tag.
Accuracy scores of the models will be showcased after the EDA results.
@dipayan22

**Comment by dipayan22** [comment]
@abhisheks008 You can check now . REABME.md file is updated.

**Comment by abhisheks008** [comment]
I couldn't find the Streamlit file in the model folder with `.py` extension.
Can you update that?

**Pull request closed without merging**
