### PR TITLE
Heart Disease Prediction using Deep Learning

### PR DESCRIPTION
**Pull request by KamakshiOjha**
# Pull Request for DL-Simplified 💡

## Issue Title : [Project Addition]: Heart Disease Prediction using Deep Learning #567

- **Info about the related issue (Aim of the project)** : Compare neural network and random forest algorithms to determine the best model for heart disease prediction using accuracy scores.
- **Name:** Kamakshi Ojha
- **GitHub ID:** KamakshiOjha
- **Email ID:** kkamakshiojha@gmail.com
- **Idenitfy yourself: (Mention in which program you are contributing in. Eg. For a JWOC 2022 participant it's, `JWOC Participant`)** GSSOC 2024 contributor

Closes: #567

### Describe the add-ons or changes you've made 📃

The neural network architecture:

Input Layer:

Shape: (None, 12, 1)
Explanation: This specifies that the input data has a shape of (batch_size, 12, 1), where each input sample has 12 time steps and 1 feature.
Convolutional Blocks:

The model consists of several convolutional blocks, each containing:
Conv1D layer with ReLU activation.
Additional Conv1D layer with ReLU activation.
Add layer that performs element-wise addition of the output of the first Conv1D layer and the output of the second Conv1D layer.
These blocks progressively increase the number of filters from 32 to 256, capturing increasingly complex patterns in the data.
Global Average Pooling Layer:

This layer computes the average of the feature maps across the time dimension, resulting in a fixed-length vector regardless of the input sequence length. This helps in capturing global information from the entire sequence.
Dense Layers:

Several Dense layers follow the Global Average Pooling layer, reducing the dimensionality of the feature space.
Each Dense layer is followed by a ReLU activation function.
Output Layer:

The final Dense layer with 2 units and a sigmoid activation function produces the output of the model.
This architecture is suitable for binary classification tasks, where the model predicts the probability of belonging to each class.

### CODE REVIEW

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
Please follow the project structure and update the project folder accordingly.
@KamakshiOjha

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
Follow the [README template](https://github.com/abhisheks008/DL-Simplified/blob/main/.github/readme_template.md) and create a README file for your project.

@KamakshiOjha

**Comment by abhisheks008** [comment]
Can you implement 2-3 more models other than the existing one?

**Comment by KamakshiOjha** [comment]
can you please check

**Review by abhisheks008 — APPROVED** [review]
Great work! Your PR is approved and ready to be merged.
@KamakshiOjha 

Show some love and support by starring this repository 🌟

**Pull request merged**
