### PR TITLE
New EDA to Amazon Reviews Sentiment Analysis

### PR DESCRIPTION
**Pull request by SimranShaikh20**
# Pull Request for DL-Simplified 💡
Issue no - #915 

## Issue Title : 
Adding some charts for better understanding 
- **Info about the related issue (Aim of the project)** : Easy to understand
- **Name:** Simran Shaikh
- **GitHub ID:** @SimranShaikh20

- **Idenitfy yourself: (Mention in which program you are contributing in. Eg. For a JWOC 2022 participant it's, `JWOC Participant`)** GSSOC ' 24 extd

### Describe the add-ons or changes you've made 📃
add notebook file to main branch 
Give a clear description of what have you added or modifications made

## Type of change ☑️

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)

## How Has This Been Tested? ⚙️

Describe how it has been tested
Describe how have you verified the changes made

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by SimranShaikh20** [comment]
@abhisheks008  if there is conflicts let me know !

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
Please put the file in the designated project folder, it should not be in the main repository's home page!!

@SimranShaikh20

**Comment by SimranShaikh20** [comment]
> Please put the file in the designated project folder, it should not be in the main repository's home page!!
> 
> @SimranShaikh20

Okay I will make new PR

**Comment by SimranShaikh20** [comment]
@abhisheks008 i had added file in to particular pls review it .
And is there any confilcts then let me know

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
Put the file inside the Model folder.

**Review by SimranShaikh20 — COMMENTED** [review]
added file in model folder

**Review by abhisheks008 — APPROVED** [review]
Looks good to me. Approved!
@SimranShaikh20

**Comment by SimranShaikh20** [comment]
@abhisheks008 can you please change level! 
Is as I implement entire eda concept in it

**Comment by abhisheks008** [comment]
> @abhisheks008 can you please change level! Is as I implement entire eda concept in it

Model implementations will carry Level 2 and above. You can try out another issue for model implementations and get the desired level.

**Comment by SimranShaikh20** [comment]
> > @abhisheks008 can you please change level! Is as I implement entire eda concept in it
> 
> Model implementations will carry Level 2 and above. You can try out another issue for model implementations and get the desired level.
> 
> Please share your email address for further communications.

yeah sure

shaikhsimran20.2003@gmail.com

**Comment by SimranShaikh20** [comment]
@abhisheks008  points updated level meaning i had not understand can you pls ellobrate it !

**Comment by abhisheks008** [comment]
> @abhisheks008 points updated label meaning i had not understand can you pls ellobrate it !

I always track an excel sheet for having a count on the PRs merged and the points assigned to the contributors along with their emails for further communications.

`Points Updated` signifies that your points have been recorded to my excel sheet.

**Pull request merged**
