### PR TITLE
Research Topic Prediction using DL #986

### PR DESCRIPTION
**Pull request by SimranShaikh20**
# Pull Request for DL-Simplified 💡

Issue no - #986 

## Issue Title :Research Topic Prediction using DL 

- **Info about the related issue (Aim of the project)** : 
- **Name:** Simran Shaikh
- **Idenitfy yourself: GSSOC 24 Extd

Closes: #986 

### Describe the add-ons or changes you've made 📃
Added new folder with mandatory file .

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## How Has This Been Tested? ⚙️

Describe how it has been tested
Describe how have you verified the changes made

## Checklist: ☑️

@abhisheks008 kindly review my PR and is there any conflicts let me know !

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by abhisheks008 — COMMENTED** [review]
Adding level 1 label as this project is not completed at all. README needs to be updated, `.ipynb` file needs to be well documented. I don't think this will be a good contribution from an open source point of view.

Tell me what should I do? I don't even know this will be considered by the leaderboard as that should have been freezed as of now.
@SimranShaikh20

**Comment by SimranShaikh20** [comment]
> Adding level 1 label as this project is not completed at all. README needs to be updated, `.ipynb` file needs to be well documented. I don't think this will be a good contribution from an open source point of view.
> 
> Tell me what should I do? I don't even know this will be considered by the leaderboard as that should have been freezed as of now. @SimranShaikh20

wait i will update file

**Comment by SimranShaikh20** [comment]
@abhisheks008 i have updated readme.md file
pls check it !

**Review by abhisheks008 — APPROVED** [review]
Approved!

**Comment by SimranShaikh20** [comment]
@abhisheks008 thanks!

**Comment by abhisheks008** [comment]
@SimranShaikh20 please inform @MastanSayyad for adding the points as the leaderboard might not automatically fetch this pull request's points.

**Comment by SimranShaikh20** [comment]
> @SimranShaikh20 please inform @MastanSayyad for adding the points as the leaderboard might not automatically fetch this pull request's points.

yeah i will inform him about it

**Pull request merged**
