### PR TITLE
AI Vs Human Text Classification

### PR DESCRIPTION
**Pull request by Karthik110505**
# Pull Request for DL-Simplified 💡

## Issue Title : [Project Addition] AI Vs Human Text Classification

- **Info about the related issue (Aim of the project)** : To classify the given text either written by a human or an AI using DL
- **Name:** Veera Venkata Karthik Barrenkala
- **GitHub ID:**  [Karthik110505](https://github.com/Karthik110505)
- **Email ID:** [bvvkarthik1155@gmail.com](mailto:bvvkarthik1155@gmail.com)
- **Identify yourself:** GSSoC'24 Participant

Closes: #655 

### Describe the add-ons or changes you've made 📃

I have added a new project named "AI Vs Human Text Classification" to the repository.

## Type of change ☑️

What sort of change have you made:

- [x] Project Addition (Adding a Project to the directory without any issues)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? ⚙️

The project has been tested locally on a sample dataset to ensure functionality and accuracy.

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by Karthik110505** [comment]
@abhisheks008  Please check this PR.

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
Need to do some EDA before jumping into the model creation part.
Also add the EDA results/data visualization images inside the Images folder as well as add them in the README.md file.

@Karthik110505

**Comment by Karthik110505** [comment]
@abhisheks008  Can you please check it now and let me know, if any further changes required.

**Comment by Karthik110505** [comment]
@abhisheks008 @thevirengarg  Someone please check this pr and let me know for any further improvements. 

I am ready with other pr for the issue #660 . So if this pr gets merged then I could make another pr for the issue #660

**Review by abhisheks008 — APPROVED** [review]
Approved @Karthik110505

**Pull request merged**
