### PR TITLE
Indian Food Recognition & Portuguese Meals Classification

### PR DESCRIPTION
**Pull request by adithya-s-k**
# Pull Request for DL-Simplified 💡

## Issue Title : 

- **Info about the related issue (Aim of the project)** :  Indian Food Images Recognition
- **Name:** Adithya S Kolavi
- **GitHub ID:** [adithya-s-k](https://github.com/adithya-s-k)
- **Email ID:** adithyaskolavi@gmail.com
- **Idenitfy yourself:  SSOC participant 2022

Closes: #44 
### Describe the add-ons or changes you've made 📃

First I imported all the required libraries and dataset for this project. Then I imported the dataset and split it into training, validation and testing sets in the ratio 70:20:10. Then I proceeded to build the model. I have developed deep learning model to classify the images.I used a CNN with MaxPooling layers and got a satisfactory accuracy score. But as there is lack of data in the dataset the validation accuracy is quite low.

## Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? ⚙️

Describe how it has been tested
Describe how have you verified the changes made

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
You have used only one algorithm, try to implement 2 more to get a comparison and eventually find out the best fitted one. Also mention all the models in the README.md file.
@adithya-s-k

**Comment by adithya-s-k** [comment]
ok will do that 

I also want to create my own issue. It is a real-time yoga detection model which uses your camera to detect which yoga pose you are doing. So can I create an issue regarding the above mentioned idea @abhisheks008

**Comment by abhisheks008** [comment]
Yeah ofcourse you are free to raise your own issue here. But before that complete this one first then try other ones, otherwise it'll left as incomplete.
@adithya-s-k

**Comment by adithya-s-k** [comment]
@abhisheks008 i have added the other models as well please look into it

**Review by abhisheks008 — APPROVED** [review]
Nicely done both the projects.
@adithya-s-k

**Pull request merged**
