### PR TITLE
Changes committed to Add Dataset to the Repository

### PR DESCRIPTION
**Pull request by utsabsamadder**
# Pull Request for DL-Simplified 💡

## Issue Title : 

- **Info about the related issue (Aim of the project)** : 
- **Name:** 
- **GitHub ID:** 
- **Email ID:** 
- **Idenitfy yourself: (Mention in which program you are contributing in. Eg. For a JWOC 2022 participant it's, `JWOC Participant`)** 

Closes: #issue number that will be closed through this PR

### Describe the add-ons or changes you've made 📃

Give a clear description of what have you added or modifications made

## Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? ⚙️

Describe how it has been tested
Describe how have you verified the changes made

## Checklist: ☑️

- [ ] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by utsabsamadder** [comment]
@abhisheks008 Could you merge this into your Repository?

**Comment by utsabsamadder** [comment]
I have added the dataset here. Now  I will add the best.py file and other python files

**Comment by abhisheks008** [comment]
Hi @utsabsamadder no need to push the datapoints, this is huge in size. Instead you can create a folder as `Dataset` inside that create a `README.md` file and paste the URL/source of the dataset. This will be efficient enough.

Also, complete the whole project and then create the PR, it'll be better for me to check the codebase.

**Comment by utsabsamadder** [comment]
Okay i got it

**Comment by utsabsamadder** [comment]
I have made my Custom dataset and labeling it at the moment. YOLO does not work on vectorized Datasets.

**Comment by abhisheks008** [comment]
> I have made my Custom dataset and labeling it at the moment. YOLO does not work on vectorized Datasets.

No problem. Whatever the dataset you have used if it is huge in size just create a README inside the Dataset folder and put the source of the dataset. You can also share a brief about the dataset.

**Pull request closed without merging**
