### PR TITLE
Urban Sound Analysis - Sound Classification 

### PR DESCRIPTION
**Pull request by SimranShaikh20**
# Pull Request for DL-Simplified 💡

 Issue no -#963

## Issue Title : 

- **Info about the related issue (Aim of the project)** : 
- **Name:** Simran Shaikh
- **GitHub ID:** https://github.com/SimranShaikh20
- **Email ID:** shaikhsimran20.2003@gmail.com
- **Idenitfy yourself:  GSSOC Extd 2024

### Describe the add-ons or changes you've made 📃
I have added folder with all mandatory files to main branch 
Give a clear description of what have you added or modifications made

## Type of change ☑️
Add project for urban sound analysis and classification

Example how to mark a checkbox:-
- [x] My code follows the code style of this project.
-->
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? ⚙️

Describe how it has been tested
Describe how have you verified the changes made

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by SimranShaikh20** [comment]
@abhisheks008  kindly review my PR and merged !
if there is any conflicts let me know about it .

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
Please re-arrange the files according to the project structure,
```
Project Folder
|- Dataset
   |- dataset.csv (dataset used for the particula project)
   |- README.md (brief about the dataset)
|- Images
   |- img1.png
   |- img2.png
   |- img3.png
|- Model
   |- project_folder.ipynb
   |- README.md
|- Web App
   |- templates
   |- img3.png
|- Model
   |- project_folder.ipynb
   |- README.md
|- requirements.txt
```

@SimranShaikh20

**Comment by SimranShaikh20** [comment]
@abhisheks008  added entire project based on above formet !
kindly review it and merged !

**Comment by SimranShaikh20** [comment]
> Please re-arrange the files according to the project structure,
> 
> ```
> Project Folder
> |- Dataset
>    |- dataset.csv (dataset used for the particula project)
>    |- README.md (brief about the dataset)
> |- Images
>    |- img1.png
>    |- img2.png
>    |- img3.png
> |- Model
>    |- project_folder.ipynb
>    |- README.md
> |- Web App
>    |- templates
>    |- img3.png
> |- Model
>    |- project_folder.ipynb
>    |- README.md
> |- requirements.txt
> ```
> 
> Project folder name should be, `Urban Sound Classification using Deep Learning`
> 


Suggestion for above format you must include this format in repo so that new contributor  able to know how to add file with particular format 

this will save your time as well as contributor time becoz once we upload file then again we have to change entire format this take more time !

@abhisheks008 if you permits i will create new for this 
Issue description - Format to contribute in project

**Comment by SimranShaikh20** [comment]
@abhisheks008  for that you have to provide my format for all type contirbution !

**Comment by SimranShaikh20** [comment]
@abhisheks008 !

**Comment by abhisheks008** [comment]
Cool then create a new issue and put the project structure in the project repository's README.

For this pull request give me some time, I'll review it ASAP.

@SimranShaikh20

**Comment by abhisheks008** [comment]
> @abhisheks008  for that you have to provide me format for all type contirbution !

For every contribution here in this project repository contributors have to follow the same project structure as the issues are mainly project based.

**Review by abhisheks008 — APPROVED** [review]
Looks good to me. Models are correctly implemented hence upgrading the level of the issue and pull request.

@SimranShaikh20

**Pull request merged**
