### PR TITLE
Groundwater Arsenic Content Detection

### PR DESCRIPTION
**Pull request by Stuti333**
# Pull Request for DL-Simplified 💡

## Issue Title : Addition of Groundwater arsenic content detection 

- **Info about the related issue (Aim of the project)** : To detect arsenic content of groundwater and detect whether it is useful or harmful
- **Name:** Stuti Sharma
- **GitHub ID:**  https://github.com/Stuti333
- **Email ID:** stutiemailbox@gmail.com
- **Idenitfy yourself: (Mention in which program you are contributing in. Eg. For a JWOC 2022 participant it's, `JWOC Participant`)** GSSOC'EXT Participant

Closes: #960 

### Describe the add-ons or changes you've made 📃
Added a new model with 3 methods to detect groundwater quality

## Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? ⚙️

Describe how it has been tested: Tested on sample datas and calculated accuracy of the algorithms used

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
1. Project folder name should be, `Groundwater Arsenic Content Detection`.
2. Follow the README template and update the README.md file. For your reference, https://github.com/abhisheks008/DL-Simplified/blob/main/.github/readme_template.md
3. Change the `.py` files in to `ipynb` files (mandatory required).

@Stuti333

**Comment by abhisheks008** [comment]
Do let me know once you are done with the update.
@Stuti333

**Comment by Stuti333** [comment]
I have made all the required changes kindly review it

**Review by abhisheks008 — APPROVED** [review]
Approved!!
@Stuti333

**Pull request merged**
