### PR TITLE
Handwriting Recognition Project

### PR DESCRIPTION
**Pull request by SHAY2407**
# Pull Request for DL-Simplified 💡

Handwriting Recognition Project

- **Info about the related issue (Aim of the project)** : The aim is to create a deep learning project which will recognize the handwritings and detect them with an accuracy of more than 85%
- **Name:** Yashwardhan Khanna
- **GitHub ID:** https://github.com/SHAY2407
- **Email ID:** yashwardhan2407@gmail.com
- **Idenitfy yourself**: SSOC 20222

Closes: #9 

### Describe the add-ons or changes you've made 📃

Made 3 folder namely Model, Dataset, Images and a requirements text file
1. Model: Contains a DL model for handwriting recognition and a README file.
2.  Dataset: Provides link to the dataset
3. Images: Contains the images which are used in README for visualization/EDA
4. requirements: contains the names of the libraries/packages used

## Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? ⚙️

The code was tested in kaggle notebook after getting the required libraries and the accuracy is 82%

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by SHAY2407** [comment]
Ok will check and let you know

**Comment by SHAY2407** [comment]
> @SHAY2407 the cells in the jupyter notebook have not run properly, can you check that.

The code is working properly, do you want the outputs also with every code block, if so, how do I save the outputs in kaggle and also show the outputs in GitHub?

**Comment by abhisheks008** [comment]
You can use Google Colab for that @SHAY2407

**Comment by abhisheks008** [comment]
Hey @SHAY2407 any updates?

**Comment by SHAY2407** [comment]
> Hey @SHAY2407 any updates?

Yup saved the model with the output, is it visible?

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
Please remove the `.ipynb` file which you have pushed directly inside the `DL-Simplified` repo, outside the `Handwriting Recognition Project` folder

**Comment by SHAY2407** [comment]
> Please remove the `.ipynb` file which you have pushed directly inside the `DL-Simplified` repo, outside the `Handwriting Recognition Project` folder

done

**Review by abhisheks008 — APPROVED** [review]
Nice representation of your project. Kudos to your dedication and efforts @SHAY2407

**Pull request merged**
