### PR TITLE
Knee Ossteoarthritis Prediction

### PR DESCRIPTION
**Pull request by devarshh08**
# Pull Request for DL-Simplified 💡

## Issue Title :  Knee Osteoarthritis Prediction

- **Info about the related issue (Aim of the project)** :  Predicting whether the person has osteoarthritis or not
- **Name:**  Devarsh Shah
- **GitHub ID:**  @devarshh08 
- **Email ID:**  devarshh.s9521@gmail.com
- **Idenitfy yourself: (Mention in which program you are contributing in. Eg. For a JWOC 2022 participant it's, `JWOC Participant`)**  GSSoC 2024 Contributor

Closes: #752

### Describe the add-ons or changes you've made 📃

Give a clear description of what have you added or modifications made

## Type of change ☑️

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## How Has This Been Tested? ⚙️

This code has been tested by plotting the accuracy and loss and all the metrics are specified in the readme file

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by abhisheks008 — COMMENTED** [review]
Complete the whole project and then send the pull request.

**Comment by devarshh08** [comment]
@abhisheks008 I am very sorry sir, I had forgotten to push the code. I have completed the project and I am commiting right away.

**Comment by devarshh08** [comment]
@abhisheks008 The model has ben commited, so has the images of the metrics I used to evaluate. Thank you very much for your patience and thank you for understanding.

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
As per the comments in the issue, you are supposed to create 3-4 models for this project. But I have seen only one model implemented for this dataset. Need to implement all the mentioned models.

Also follow the README template and update the same by adding the visualization of the dataset, EDA results, conclusion for the best model as per the accuracy scores and so on. Rename the Readme.md as `README.md`

@devarshh08 need to fix these changes as of now.

**Comment by devarshh08** [comment]
@abhisheks008 Ok I'll work on it. Thank you.

**Pull request closed without merging**
