### PR TITLE
Added PII Document Classification model

### PR DESCRIPTION
**Pull request by nk-droid**
# Pull Request for DL-Simplified 💡

## Issue Title : 

- **Info about the related issue (Aim of the project)** : 
- **Name:** Nidhish Kumar
- **GitHub ID:** nk-droid
- **Email ID:** nidhish.22k@gmail.com
- **Idenitfy yourself:** SSoC 2023 Contributor

Closes: #244 

### Describe the add-ons or changes you've made 📃

I've added PII document classification model in the format suggested while assigning the task.

## Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? ⚙️

I've added new files and tested them on GitHub before making the pull request.

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
Hi @nk-droid remove the images from the Dataset folder. Instead of putting all the data point images, put a README.md file and mention the URL of the dataset. That will work. Otherwise this huge amount of dataset will affect the project repository while merging.

**Comment by nk-droid** [comment]
I've made the changes. Could you please merge and assign me the next project?

**Review by abhisheks008 — APPROVED** [review]
Nicely represented the project. Really appreciated your efforts and enthusiasm. Your PR is approved and ready to be merged.

Keep Contributing in open source.
@nk-droid

**Comment by nk-droid** [comment]
Thanks :)

**Pull request merged**
