### PR TITLE
Poem Generator using DL

### PR DESCRIPTION
**Pull request by Madhusri02**
# Pull Request for DL-Simplified 💡

Deep Learning Simplified Repository (Proposing new issue)
🔴 Project Title : Poem generator
🔴 Aim : To generate poem from a dataset of poems
🔴 Dataset : Poems.txt
🔴 Approach : Using LSTM and 3 layers of neural networks.

Closes:   Poem Generator using DL #607

- [ x] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ x] Code style update (formatting, local variables)
- [ x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ x] This change requires a documentation update

## How Has This Been Tested? ⚙️

This application is tested with various inputs given with starting word of the User input. Got best result from the input give. Also expecting any changes to be done in this poem generator using Neural network.

## Checklist: ☑️

- [ x] My code follows the guidelines of this project.
- [ x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x ] I have made corresponding changes to the documentation.
- [ x] My changes generate no new warnings.
- [ x] I have added things that prove my fix is effective or that my feature works.
- [ x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
Please follow the project structure and re-structure your files accordingly.

@Madhusri02

**Comment by Madhusri02** [comment]
Okay @abhisheks008

**Comment by abhisheks008** [comment]
Hi @Madhusri02 please follow the project structure.

Here it is,
```
Project Folder
|- Dataset
   |- dataset.csv (dataset used for the particula project)
   |- README.md (brief about the dataset)
|- Images
   |- img1.png
   |- img2.png
   |- img3.png
|- Model
   |- project_folder.ipynb
   |- README.md
|- Web App
   |- templates
   |- static
   |- app.py
   |- demo.mp4
   |- README.md
|- requirements.txt
```

**Comment by abhisheks008** [comment]
@Madhusri02 why have you made changes in the Bone Fracture Detection project?
Also please follow the above mentioned project structure and make the sub folders accordingly.

> Hi @Madhusri02 please follow the project structure.
> 
> Here it is,
> 
> ```
> Project Folder
> |- Dataset
>    |- dataset.csv (dataset used for the particula project)
>    |- README.md (brief about the dataset)
> |- Images
>    |- img1.png
>    |- img2.png
>    |- img3.png
> |- Model
>    |- project_folder.ipynb
>    |- README.md
> |- Web App
>    |- templates
>    |- static
>    |- app.py
>    |- demo.mp4
>    |- README.md
> |- requirements.txt
> ```

**Pull request closed without merging**
