### PR TITLE
Smile Recognition Using Deep Learning

### PR DESCRIPTION
**Pull request by aindree-2005**
# Pull Request for DL-Simplified 💡

## Issue Title : #213 
- **Info about the related issue (Aim of the project)** : Smiling Face Recognition
- **Name:**  Aindree Chatterjee
- **GitHub ID:**  aindree-2005
- **Email ID:** aindree2005@gmail.com
- **Idenitfy yourself: (Mention in which program you are contributing in. Eg. For a JWOC 2022 participant it's, `JWOC Participant`)**  CodePeak

Closes: #213

### Describe the add-ons or changes you've made 📃

Give a clear description of what have you added or modifications made

## Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? ⚙️

Describe how it has been tested
Describe how have you verified the changes made
On Kaggle

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
Need to do some EDA before working with the actual models.
@aindree-2005

**Comment by aindree-2005** [comment]
@abhisheks008 added more eda

**Comment by abhisheks008** [comment]
Please update your `.ipynb` file along with the EDAs. I didn't find the newly added EDA images in your notebook.

**Comment by aindree-2005** [comment]
> Please update your `.ipynb` file along with the EDAs. I didn't find the newly added EDA images in your notebook.

Oh my bad. Forgot to replace the notebook. Give me 5 mins. I'll upload them

**Comment by abhisheks008** [comment]
> > Please update your `.ipynb` file along with the EDAs. I didn't find the newly added EDA images in your notebook.
> 
> Oh my bad. Forgot to replace the notebook. Give me 5 mins. I'll upload them

Sure

**Comment by aindree-2005** [comment]
@abhisheks008 done. Changed the notebook

**Review by abhisheks008 — APPROVED** [review]
Your PR is approved and ready to merged.
@aindree-2005

**Pull request merged**
