### PR TITLE
[Project Addition]: Waste Classification using DL

### PR DESCRIPTION
**Pull request by Karthik110505**
# Pull Request for DL-Simplified 💡

## Issue Title : [Project Addition]: Waste Classification using DL

- **Info about the related issue (Aim of the project)** : Classification of the waste into Organic and Recyclable waste using DL.
- **Name:** Veera Venkata Karthik Barrenkala
- **GitHub ID:**  https://github.com/karthik110505
- **Email ID:** [bvvkarthik1155@gmail.com](mailto:bvvkarthik1155@gmail.com)
- **Idenitfy yourself:** GSSoC'24 Participant

Closes: #615

### Describe the add-ons or changes you've made 📃

I have added a Project named  'Waste Classification using DL' 

## Type of change ☑️

What sort of change have you made:

- [x] Project Addition (Adding a Project to the directory without any issues)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
Why have you deleted Crop Pest detection project's file?
@Karthik110505

**Comment by Karthik110505** [comment]
@abhisheks008 Bro, While I was making a pr for this project, I don't know why the .ipynb file of previous file is also getting added. So I thought of deleting it and deleted. What should I do now?

**Comment by Karthik110505** [comment]
@abhisheks008  Bro, I Reverted it. Now is it ok? Next time I will not repeat this.

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
image

@Karthik110505

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
image

None of the uploaded images are showing up. Please check these.
@Karthik110505

**Comment by Karthik110505** [comment]
@abhisheks008  Bro please check it once again, because I am getting the images. 


Screenshot from 2024-05-23 09-20-15

**Review by abhisheks008 — APPROVED** [review]
Approved @Karthik110505

**Pull request merged**
