### PR TITLE
ChatGPT Based Tweets Sentiment Analyis Using DL

### PR DESCRIPTION
**Pull request by vrinda-vritti**
# Pull Request for DL-Simplified 💡

## Issue Title : Fix issue #345: ChatGPT Based Tweets Sentiment Analysis Using DL

- **Info about the related issue (Aim of the project)** :  Analysing the Tweets about ChatGPT and the performing the Sentiment Analysis and then performing LSTM and BiLSTM on it
- **Name: Vrinda Vritti** 
- **GitHub ID:  https://github.com/vrinda-vritti** 
- Email ID: [vrinda.v0221@gmail.com](mailto:vrinda.v0221@gmail.com)  
- **Idenitfy yourself: Social Summer Of Code Season 2** 

Closes: #345 

### Describe the add-ons or changes you've made 📃
Sentiment analysis on ChatGPT tweets involves using NLP to analyze emotions and attitudes expressed in tweets by the language model. It categorizes tweets as positive, negative, or neutral, providing insights into the overall emotional tone of the content. I have done data processing, data visualisation and then finally applied LSTM and BiLSTM on the dataset.

## Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? ⚙️

Describe how it has been tested
Describe how have you verified the changes made

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
1. Remove the `.idea` folder, `inspectionProfiles` folder, `misc.xml`, `modules.xml`, `vcs.xml` files. As these are unnecessary files for this project as well for this project folder.
2. Add Images folder and put the visualization resultant images there.
3. The accuracies for both of these models are really low. Try to improve the scores to 80% at least.

@vrinda-vritti

**Comment by vrinda-vritti** [comment]
> 1. Remove the `.idea` folder, `inspectionProfiles` folder, `misc.xml`, `modules.xml`, `vcs.xml` files. As these are unnecessary files for this project as well for this project folder.
> 2. Add Images folder and put the visualization resultant images there.
> 3. The accuracies for both of these models are really low. Try to improve the scores to 80% at least.
> 
> @vrinda-vritti

Okay, will update it !

**Comment by vrinda-vritti** [comment]
I have added the Images folder with visualisation and updated the model and got a accuracy of 68 after running 500 epochs. 
But I cant find the .idea folder, inspectionProfiles folder, misc.xml, modules.xml, vcs.xml files.

**Review by abhisheks008 — APPROVED** [review]
Your PR is approved and ready to be merged.
@vrinda-vritti

**Pull request merged**
