### PR TITLE
[README Enhancement]: Children vs Adults Classification

### PR DESCRIPTION
**Pull request by vanshikab52**
# Pull Request for DL-Simplified 💡

## Issue Title : [README Enhancement]: Children vs Adults Classification

- **Info about the related issue (Aim of the project)** : Enhanced requested README files
- **Name:** -  Vanshika Bisht
- **GitHub ID:** - https://github.com/vanshikab52
- **Email ID:**  - vanshikabisht777@gmail.com
- **Idenitfy yourself - Contributer in GSSoC'24

Closes: #525 

### Describe the add-ons or changes you've made 📃

Improved the README.md  after understanding the project idea along with upscaled the results images and aligned them.

## Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## How Has This Been Tested? ⚙️

Describe how it has been tested
Describe how have you verified the changes made

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by abhisheks008** [comment]
Hi @vanshikab52 you did a great job. Can you enhance the `Dataset/README.md` file too of this project?

**Comment by vanshikab52** [comment]
> Hi @vanshikab52 you did a great job. Can you enhance the `Dataset/README.md` file too of this project?

Yes sir I can modify it aswell. It's my pleasure to contribute to your project sir!

**Comment by vanshikab52** [comment]
> > Hi @vanshikab52 you did a great job. Can you enhance the `Dataset/README.md` file too of this project?
> 
> Yes sir I can modify it aswell. It's my pleasure to contribute to your project sir!

@abhisheks008 is there any template you want the dataset README like to be or any changes you would suggest.

**Review by abhisheks008 — APPROVED** [review]
Good to go! Your PR is approved and ready to be merged.

**Pull request merged**
