### PR TITLE
Pothole Detection System

### PR DESCRIPTION
**Pull request by mattiaferrarini**
# Pull Request for DL-Simplified 💡

## Issue Title : Pothole detection system

- **Info about the related issue (Aim of the project)** :  To create a DL model that would detect potholes on road
- **Name:**  Mattia Ferrarini 
- **GitHub ID:**  https://github.com/MattiaFerrarini 
- **Email ID:**  mattiaferrarini22@gmail.com 
- **Idenitfy yourself: (Mention in which program you are contributing in. Eg. For a JWOC 2022 participant it's, `JWOC Participant`)**  SWOC 2024 

Closes: #276

### Describe the add-ons or changes you've made 📃

Added the Pothole Detection System as required by the corresponding issue.

## Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? ⚙️

I have run the whole notebook in kaggle  and verified its correctness.

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by abhisheks008** [comment]
> # Pull Request for DL-Simplified 💡
> ## Issue Title :
> * **Info about the related issue (Aim of the project)** :
> * **Name:**
> * **GitHub ID:**
> * **Email ID:**
> * **Idenitfy yourself: (Mention in which program you are contributing in. Eg. For a JWOC 2022 participant it's, `JWOC Participant`)**
> 
> Closes: #276
> 
> ### Describe the add-ons or changes you've made 📃
> Added the Pothole Detection System as required by the corresponding issue.
> 
> ## Type of change ☑️
> What sort of change have you made:
> 
> * [ ]  Bug fix (non-breaking change which fixes an issue)
> * [x]  New feature (non-breaking change which adds functionality)
> * [ ]  Code style update (formatting, local variables)
> * [ ]  Breaking change (fix or feature that would cause existing functionality to not work as expected)
> * [ ]  This change requires a documentation update
> 
> ## How Has This Been Tested? ⚙️
> I have run the whole notebook in kaggle and verified its correctness.
> 
> ## Checklist: ☑️
> * [x]  My code follows the guidelines of this project.
> * [x]  I have performed a self-review of my own code.
> * [x]  I have commented my code, particularly wherever it was hard to understand.
> * [x]  I have made corresponding changes to the documentation.
> * [x]  My changes generate no new warnings.
> * [x]  I have added things that prove my fix is effective or that my feature works.
> * [x]  Any dependent changes have been merged and published in downstream modules.

Fill up this template every time you create a pull request, this will help us to identify and verify you as a contributor in a better way.

**Review by abhisheks008 — APPROVED** [review]
Looks good to me.

**Comment by MattiaFerrarini** [comment]
Hi, I have modified the PR comment to include the missing details. I'm not very experienced with GitHub: is there anything that I should be doing now that you have approved the changes?

**Comment by abhisheks008** [comment]
Approved! 
@MattiaFerrarini 

> Hi, I have modified the PR comment to include the missing details. I'm not very experienced with GitHub: is there anything that I should be doing now that you have approved the changes?

Approved. Always fill up the pull request template while creating the PRs.
@MattiaFerrarini

**Pull request merged**
