### PR TITLE
Added Colon and Lung Cancer Prediction folder

### PR DESCRIPTION
**Pull request by adi271001**
# Pull Request for DL-Simplified 💡

## Issue Title :  #375  Colon and Lung Cancer Type Prediction using Deep Learning <-- Enter the issue title here -->

- **Info about the related issue (Aim of the project)** : To Predict different classes of lung and colon predicition based on deep cnn networks 
- **Name:** Aditya D 
- **GitHub ID:** adi271001 
- **Email ID:** ibetanibex@gmail.com 
- **Idenitfy yourself:  (Mention in which program you are contributing in. Eg. For a JWOC 2022 participant it's, `JWOC Participant`)** OSEN Participant

Closes: 375 #issue number that will be closed through this PR 

### Describe the add-ons or changes you've made 📃

Give a clear description of what have you added or modifications made
i have added the folder colon and lung cancer prediciton as per the guidelines dataset contains the kaggle dataset link to the dataset which i have used , images have sample image of dataset , classification report , cofusion matrix , training and test
## Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? ⚙️

Describe how it has been tested
the kaggle dataset has been divided into test images 

Describe how have you verified the changes made
i have attached graphs which shows that there is neither underfitting nor overfitting

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by abhisheks008** [comment]
Hi @adi271001 the overall project looks really good to me. You have put all the required files in the correct spot. In the `README.md` file you can add the images under the **Visualization** tag, which will provide an extra edge for this project.

**Comment by adi271001** [comment]
ok will do it

**Comment by adi271001** [comment]
I have attached it

**Review by abhisheks008 — APPROVED** [review]
Your PR is approved and ready to be merged. Congratulations @adi271001 on your first contribution in this project repository.

**Pull request merged**
