### PR TITLE
Added Emotion Based Music Player Project

### PR DESCRIPTION
**Pull request by shanmukhi-developer**
# Pull Request for DL-Simplified 💡

## Issue Title : Emotion Based Music Player

- **Info about the related issue (Aim of the project)**: The emotion-based music player successfully integrates deep learning and computer vision techniques to create a personalized, emotion-driven music experience. The system can detect the user's emotional state in real time by leveraging facial expression and hand gesture recognition through Mediapipe, combined with a pre-trained deep learning model. This allows for dynamic music recommendations that adapt to the user's mood, enhancing the listening experience.<br>

- **Name:** Nadipudi Shanmukhi satya
- **GitHub ID:** https://github.com/shanmukhi-developer
- **Email ID:** shanmukhinadipudi@gmail.com
- **Identify yourself: I'm contributing to GSSoC'24-Extd 

Closes: #903 

### Describe the add-ons or changes you've made 📃

I have added a project called "Emotion Based Music Player" to the repository which is based on Deep Learning Models.

## Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [* ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist: ☑️

- [* ] My code follows the guidelines of this project.
- [ *] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly wherever it was hard to understand.
- [* ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by shanmukhi-developer** [comment]
can you please review my pr and assign me this with gssoc-extd please

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
1. Please update the project structure, 
```
Project Folder
|- Dataset
   |- dataset.csv (dataset used for the particula project)
   |- README.md (brief about the dataset)
|- Images
   |- img1.png
   |- img2.png
   |- img3.png
|- Model
   |- project_folder.ipynb
   |- README.md
|- Web App
   |- templates
   |- static
   |- app.py
   |- demo.mp4
   |- README.md
|- requirements.txt
```

2. `Model/README.md` template: https://github.com/abhisheks008/DL-Simplified/blob/main/.github/readme_template.md
3. `Web App/README.md` template: https://github.com/abhisheks008/DL-Simplified/blob/main/.github/web-app_readme_template.md

**Comment by shanmukhi-developer** [comment]
@abhisheks008 I have done the changes please review the pr

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
I am not able to find out the `ipynb` file for the models implemented. Also creating only one model with such a low accuracy will not work, you need to hit at least an accuracy of 90%.

Sharing an existing project folder, which will help you to figure out the file orientation, https://github.com/abhisheks008/DL-Simplified/tree/main/Brain%20Tumor%20Detection

**Pull request closed without merging**
