### PR TITLE
Hand Gloves Detection

### PR DESCRIPTION
**Pull request by falconcode16**
# Pull Request for DL-Simplified 💡

## Issue Title : 

- **Info about the related issue (Aim of the project)** : 
- **Name:** Rohit Patil
- **GitHub ID:** falconcode16 
- **Email ID:** rohitpatil1625@gmail.com 
- **Idenitfy yourself:SSOC 2022

Closes: #57

### Describe the add-ons or changes you've made 📃

Give a clear description of what have you added or modifications made

## Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [* ] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? ⚙️

Describe how it has been tested
Describe how have you verified the changes made

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
1. `Readme` files do have an extension, which is `.md` (markdown files). Rename them as `README.md`.
2. Create a folder as `Dataset`, inside it create a `README.md` file and write the source of the dataset (provide the URL).
3. Remove all the images from the `Images` folder, as you are mentioning the dataset source in the `Dataset` folder, no need to upload individual data points. `Images` folder is for uploading the resultant images, those are formed while you are doing the project. If you have some of these then put those inside the `Images` folder.
4. Inside the `.ipynb` file, there is nothing about the project. Please take a look at this.
5. All the `README` files are empty. Follow the `README` template and fill those properly.

@falconcode16

**Comment by falconcode16** [comment]
Okay, I'll do the changes

**Comment by abhisheks008** [comment]
@falconcode16 any updates?

**Comment by abhisheks008** [comment]
@falconcode16 please do the needful changes otherwise this PR is not gonna work.

**Pull request closed without merging**
