### PR TITLE
[Feature Addition]: Web App for Dog Breeds Classification

### PR DESCRIPTION
**Pull request by Himanshu8850**
# Pull Request for DL-Simplified 💡

## Issue Title : <Web app for dog breed classifier>

- **Info about the related issue (Aim of the project)** : 

Closes: #551

### Describe the add-ons or changes you've made 📃

-Added a web-app folder
-Added requirements.txt
-Added code for saving best model in .keras file in ResNet50v2(98%).ipynb

## Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? ⚙️

I have tested my web-app on my browser by checking real-time classification and output on page on image input.

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by abhisheks008** [comment]
Can you just drag and drop the demo video from your local system to README file, so that it can be viewed directly in the README.

@Himanshu8850

**Comment by abhisheks008** [comment]
It should be like this, https://github.com/abhisheks008/DL-Simplified/tree/main/Brain%20Tumor%20Detection/Web%20App

**Comment by Himanshu8850** [comment]
is the readme ok now.

**Comment by abhisheks008** [comment]
The Web App's README file should be inside the Web App folder. You have merged both the README files together, that's not the correct way to do it. Please have a look at the reference project carefully and update the README properly.

Also the video is not showing in the README. Just copy the demo video file from using `ctrl+c` and paste it in the README by `ctrl+v`, no need to hyperlink the url of the uploaded video.

@Himanshu8850

**Comment by Himanshu8850** [comment]
Done with the changes, please review them.

**Review by abhisheks008 — COMMENTED** [review]
Hi @Himanshu8850 there is an issue with GitHub since morning as a result I am not able to review the fies. Wait for some time to fix this issue.

**Comment by Himanshu8850** [comment]
Sir, is the issue resolved?

**Review by abhisheks008 — APPROVED** [review]
Approved!
@Himanshu8850

**Pull request merged**
