### PR TITLE
Covid Case Predictor

### PR DESCRIPTION
**Pull request by A-b-i-r-a-m-i-G-S**
# Pull Request for DL-Simplified 💡

## Issue Title : Covid Case Predictor

- **Info about the related issue (Aim of the project)** : Predicting number of COVID cases using time series forecasting
- **Name:** Abirami Gurushanker
- **GitHub ID:** @A-b-i-r-a-m-i-G-S
- **Email ID:** abiramigs21@gmail.com
- **Idenitfy yourself: (Mention in which program you are contributing in. Eg. For a JWOC 2022 participant it's, `JWOC Participant`)** GSSOC contributor

Closes: #422 

### Describe the add-ons or changes you've made 📃

The project focuses on exploring the data on the COVID-19 pandemic and forecast the number of confirmed cases.

## Type of change ☑️
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist: ☑️
- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
Hi @A-b-i-r-a-m-i-G-S the issue was to track the vaccination of Covid-19

**Comment by A-b-i-r-a-m-i-G-S** [comment]
@abhisheks008 since there is no vaccination data in the kaggle dataset you provided, can i work on a dataset of my choice?

**Comment by KumarSampurn** [comment]
> @abhisheks008 Since there is no vaccination data in the Kaggle dataset you provided, can I work on a dataset of my choice?

Hey, https://www.kaggle.com/datasets/gpreda/covid-world-vaccination-progress this is one such dataset you can use in combination with the other dataset mentioned in the issue.

Here is a reference notebook to get the gist of it:
* https://www.kaggle.com/code/joshuaswords/covid-19-vaccination-progress

**Comment by A-b-i-r-a-m-i-G-S** [comment]
@abhisheks008 thank you for your input. I will look into it and get started on the work.

**Comment by A-b-i-r-a-m-i-G-S** [comment]
@abhisheks008 the requested changes have been made

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
Rename the `dataset.md` file to `README.md` inside the Dataset folder.

@A-b-i-r-a-m-i-G-S

**Comment by A-b-i-r-a-m-i-G-S** [comment]
@abhisheks008 I've renamed the file as requested

**Review by abhisheks008 — APPROVED** [review]
Approved @A-b-i-r-a-m-i-G-S

**Pull request merged**
