### PR TITLE
ChatGPT Reddit Comments Analysis using NLP issue solved

### PR DESCRIPTION
**Pull request by Diyaa0313**
**Pull Request for DL-Simplified 💡**

Issue Title: ChatGPT Reddit Comments Analysis using NLP issue solved  https://github.com/abhisheks008/DL-Simplified/issues/410
Info about the related issue (Aim of the project): The goal of the project is to analyze the sentiments of the comments
Name: Diya Sen
GitHub ID: #138043781
Email ID: diyasen2003@gmail.com
Identify yourself: GsSOC 2024 Contributor
Closes: https://github.com/abhisheks008/DL-Simplified/issues/410

Describe the add-ons or changes you've made 📃
I have implemented the LSTM,CNN,CNN+LSTM models for sentiment analysis.

**Type of change ☑️**
What sort of change have you made:

 

- [x] Bug fix (non-breaking change which fixes an issue)
- [x]  New feature (non-breaking change which adds functionality)
- [x]  Code style update (formatting, local variables)
- [x]  Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x]  This change requires a documentation update

**How Has This Been Tested? ⚙️**
I have tested the implementation using a separate test dataset and verified the classification accuracy of each model. Additionally, I have compared the results with the expected outcomes to ensure accuracy.

Checklist: ☑️
 My code follows the guidelines of this project.
 

- [x] I have performed a self-review of my own code.
- [x]  I have commented my code, particularly wherever it was hard to understand.
- [x]  I have made corresponding changes to the documentation.
- [x]  My changes generate no new warnings.
- [x]  I have added things that prove my fix is effective or that my feature works.
- [x]  Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
1. Please follow the pull request template for creating the pull request.
2. In the Model folder update the README.md file name properly. Also follow the readme template for updating the README.md file. Here is the template, https://github.com/abhisheks008/DL-Simplified/blob/main/.github/readme_template.md

@Diyaa0313

**Comment by Diyaa0313** [comment]
I have updated the README.md file using the given template @abhisheks008

**Comment by abhisheks008** [comment]
Please have a look at this README and update yours file according to the project.
https://github.com/abhisheks008/DL-Simplified/blob/main/Age%20and%20Sex%20Prediction/Model/README.md

**Comment by Diyaa0313** [comment]
I have updated it, please check and mention if there are any other changes to be made

**Review by abhisheks008 — APPROVED** [review]
Approved @Diyaa0313

**Pull request merged**
