### PR TITLE
Ethnicity Classification of Asian People 

### PR DESCRIPTION
**Pull request by Subhranil2004**
## Issue Title : Ethnicity Classification of Asian People #507 

- **Info about the related issue (Aim of the project)** : The aim is to apply deep learning methods to find out the ethnicities of the asian faces from the dataset.
- **Name:** Subhranil Nandy
- **GitHub ID:** 69036670
- **Email ID:** iamsubhranil.nandy@gmail.com
- **Idenitfy yourself:** `GSSoC Participant`

Closes: #507 

### Describe the add-ons or changes you've made 📃

Added a folder named `Ethnicity Classification of Asian People` which contains the ipynb file and requirements.txt file along with `Dataset`, `Images` and `Models` directories. 

## Type of change ☑️

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## How Has This Been Tested? ⚙️

I have tested the project by running it on a virtual environment with python 3.11 and the required packages of the `requirements.txt`
The ipynb file ran successfully.

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
Hi @Subhranil2004 looks good to me. But you need to update the project structure. 

Here is the project structure, 
```
Project Dummy
|- Dataset
  |- dataset.csv
  |- README.md
|- Images
  |- img1.png
  |- img2.png
  |- img3.png
|- Model
  |- project_dummy.ipynb
  |- README.md
|- requirements.txt
```

Here's the README template you should follow. Please update the README as well. Click [here](https://github.com/abhisheks008/DL-Simplified/blob/main/.github/readme_template.md) for template.

Need to update the file names from `Readme.md` to `README.md`.

Please update this changes.

**Comment by Subhranil2004** [comment]
> Hi @Subhranil2004 looks good to me. But you need to update the project structure. 
> 
> Here is the project structure, 
> ```
> Project Dummy
> |- Dataset
>   |- dataset.csv
>   |- README.md
> |- Images
>   |- img1.png
>   |- img2.png
>   |- img3.png
> |- Model
>   |- project_dummy.ipynb
>   |- README.md
> |- requirements.txt
> ```
> 
> Here's the README template you should follow. Please update the README as well. Click [here](https://github.com/abhisheks008/DL-Simplified/blob/main/.github/readme_template.md) for template.
> 
> Need to update the file names from `Readme.md` to `README.md`.
> 
> Please update this changes. 

Ok, I will do the changes. 
- Can you clarify which images to include in the Images folder?

And one more thing...I faced some difficulty in pushing the changes from local after cloning the repo. So I had to do the changes from GitHub itself. The errors were like `Upstream closed connection unexpectedly `  I think it's due to the big repo size. 
Again I cloned my fork after doing the changes online, but then I couldn't find my folder in the clone.
Is there some mistake. What would u suggest?

**Comment by abhisheks008** [comment]
> > Hi @Subhranil2004 looks good to me. But you need to update the project structure.
> > Here is the project structure,
> > ```
> > Project Dummy
> > |- Dataset
> >   |- dataset.csv
> >   |- README.md
> > |- Images
> >   |- img1.png
> >   |- img2.png
> >   |- img3.png
> > |- Model
> >   |- project_dummy.ipynb
> >   |- README.md
> > |- requirements.txt
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Here's the README template you should follow. Please update the README as well. Click [here](https://github.com/abhisheks008/DL-Simplified/blob/main/.github/readme_template.md) for template.
> > Need to update the file names from `Readme.md` to `README.md`.
> > Please update this changes.
> 
> Ok, I will do the changes.
> 
> * _**Can you clarify which images to include in the Images folder?**_
> 
> And one more thing...I faced some difficulty in pushing the changes from local after cloning the repo. So I had to do the changes from GitHub itself. The errors were like `Upstream closed connection unexpectedly ` I think it's due to the big repo size. Again I cloned my fork after doing the changes online, but then I couldn't find my folder in the clone. Is there some mistake. What would u suggest? @abhisheks008

You couldn't find your repo because your branch/repo wasn't merged to the main branch.

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
Create a separate folder Images, like you created Dataset, Models and put all the EDA results, accuracy charts inside the Images folder.

I have mentioned the same in the project structure.

**Comment by Subhranil2004** [comment]
> Create a separate folder Images, like you created Dataset, Models and put all the EDA results, accuracy charts inside the Images folder.
> 
> I have mentioned the same in the project structure.

ok I'll do that

**Comment by Subhranil2004** [comment]
> > > Hi @Subhranil2004 looks good to me. But you need to update the project structure.
> > > Here is the project structure,
> > > ```
> > > Project Dummy
> > > |- Dataset
> > >   |- dataset.csv
> > >   |- README.md
> > > |- Images
> > >   |- img1.png
> > >   |- img2.png
> > >   |- img3.png
> > > |- Model
> > >   |- project_dummy.ipynb
> > >   |- README.md
> > > |- requirements.txt
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Here's the README template you should follow. Please update the README as well. Click [here](https://github.com/abhisheks008/DL-Simplified/blob/main/.github/readme_template.md) for template.
> > > Need to update the file names from `Readme.md` to `README.md`.
> > > Please update this changes.
> > 
> > 
> > Ok, I will do the changes.
> > 
> > * _**Can you clarify which images to include in the Images folder?**_
> > 
> > And one more thing...I faced some difficulty in pushing the changes from local after cloning the repo. So I had to do the changes from GitHub itself. The errors were like `Upstream closed connection unexpectedly ` I think it's due to the big repo size. Again I cloned my fork after doing the changes online, but then I couldn't find my folder in the clone. Is there some mistake. What would u suggest? @abhisheks008
> 
> You couldn't find your repo because your branch/repo wasn't merged to the main branch.

but then cant i clone the branch created by me? Afterall it's my fork that I'm cloning...

**Comment by abhisheks008** [comment]
> > > > Hi @Subhranil2004 looks good to me. But you need to update the project structure.
> > > > Here is the project structure,
> > > > ```
> > > > Project Dummy
> > > > |- Dataset
> > > >   |- dataset.csv
> > > >   |- README.md
> > > > |- Images
> > > >   |- img1.png
> > > >   |- img2.png
> > > >   |- img3.png
> > > > |- Model
> > > >   |- project_dummy.ipynb
> > > >   |- README.md
> > > > |- requirements.txt
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > Here's the README template you should follow. Please update the README as well. Click [here](https://github.com/abhisheks008/DL-Simplified/blob/main/.github/readme_template.md) for template.
> > > > Need to update the file names from `Readme.md` to `README.md`.
> > > > Please update this changes.
> > > 
> > > 
> > > Ok, I will do the changes.
> > > 
> > > * _**Can you clarify which images to include in the Images folder?**_
> > > 
> > > And one more thing...I faced some difficulty in pushing the changes from local after cloning the repo. So I had to do the changes from GitHub itself. The errors were like `Upstream closed connection unexpectedly ` I think it's due to the big repo size. Again I cloned my fork after doing the changes online, but then I couldn't find my folder in the clone. Is there some mistake. What would u suggest? @abhisheks008
> > 
> > 
> > You couldn't find your repo because your branch/repo wasn't merged to the main branch.
> 
> but then cant i clone the branch created by me? Afterall it's my fork that I'm cloning...

In the forked repo make the changes. Create a separate Images folder and put the images there.

**Comment by Subhranil2004** [comment]
@abhisheks008 I have updated the directory structure. Can u have a look if it's ok to merge?

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
image

Images are not visible in the README.

**Comment by Subhranil2004** [comment]
> image
> Images are not visible in the README.

Ok I have done the changes now. It's strange as images were showing in VS Code where I was modifying but didn't on github, had to modify the links a bit. @abhisheks008

**Comment by abhisheks008** [comment]
Hi @Subhranil2004 the project structure, README look good to me. Need some time as GitHub is not rendering the `.ipynb` files, which caused a major bug for us. As I can't review your code. Wait for some time, I hope it'll resolve soon.

**Review by abhisheks008 — APPROVED** [review]
Approved @Subhranil2004

**Pull request merged**
