### PR TITLE
Landmark Detection from images

### PR DESCRIPTION
**Pull request by yashksaini-coder**
# Pull Request for DL-Simplified 💡

## Issue Title : Landmark Detection Project

- **Info about the related issue (Aim of the project)** : To add a Landmark detect ML model web app using streamlit
- **Name:** Yash K. Saini
- **GitHub ID:** [yashksaini-coder](https://github.com/yashksaini-coder)
- **Idenitfy yourself: (Mention in which program you are contributing in. Eg. For a JWOC 2022 participant it's, `JWOC Participant`)** GSSOC-ext

Closes: #898 

### Describe the add-ons or changes you've made 📃

This pull request introduces a new feature for landmark detection and includes the necessary setup for a Streamlit web application. The most important changes involve adding a new README file, implementing the main application logic in `app.py`, and updating the requirements.

New feature implementation:

* [`Landmark-Detection/app.py`](diffhunk://#diff-a19ef540eac099f3f4af30a7eef991fb244fe6381915b7779cc8c7a547fc9e2fR1-R43): Added the main application logic for the Landmark Detection web app, including model loading, image classification, and Streamlit UI components.

Documentation:

* [`Landmark-Detection/README.md`](diffhunk://#diff-20a064bc000fbd21ea545e7cc044f8f9eb5b8138eee56965b4375d12d053d16eR1-R2): Added a new README file with a brief description of the Landmark Detection feature.

Dependencies:

* [`Landmark-Detection/requirements.txt`](diffhunk://#diff-0abbdb409bd13c35648e399766ec958f3976552f52941472d1712c6d34a21036R1-R6): Added required dependencies for the Streamlit app and TensorFlow model.

## Type of change ☑️

What sort of change have you made:

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [X] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist: ☑️

- [X] My code follows the guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly wherever it was hard to understand.
- [X] I have made corresponding changes to the documentation.
- [X] My changes generate no new warnings.
- [X] I have added things that prove my fix is effective or that my feature works.
- [X] Any dependent changes have been merged and published in downstream modules.

 ---

@abhisheks008 can you review this PR and add labels to it.

### CODE REVIEW

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
1. Project folder name should be `Landmark Detection` with no hyphen "-".
2. Follow the project structure and put the files according to that.
3. If you are implementing an UI for the users, follow this project structure, this will help you out in keeping files.
```
Project Folder
|- Dataset
   |- dataset.csv (dataset used for the particula project)
   |- README.md (brief about the dataset)
|- Images
   |- img1.png
   |- img2.png
   |- img3.png
|- Model
   |- project_folder.ipynb
   |- README.md
|- Web App
   |- templates
   |- static
   |- app.py
   |- demo.mp4
   |- README.md
|- requirements.txt
```

**Comment by yashksaini-coder** [comment]
Hi @abhisheks008 I have restructured the entire `Landmark Detection` folder as per your requests

image

---

Review the PR & add labels to it.

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
Please create a demonstration video of the working of the UI and attach the same in the Web App/README.md file.

For your reference you can check this project, https://github.com/abhisheks008/DL-Simplified/tree/main/Brain%20Tumor%20Detection/Web%20App

**Comment by yashksaini-coder** [comment]
@abhisheks008 I have added proper video in mp4 format. Also due to my laptop capacity most of the work was done on the web codespace editor, so the video may not properly load so try to refresh few time

**Comment by yashksaini-coder** [comment]
Hi @abhisheks008 here's the demo video of Landmark Detection 


https://github.com/user-attachments/assets/8c1604be-557f-4dab-b5c7-095c62e5a419

**Comment by yashksaini-coder** [comment]
hi @abhisheks008 can you review this PR now.

**Comment by yashksaini-coder** [comment]
@abhisheks008 can you review this PR, add proper labels too.

**Comment by yashksaini-coder** [comment]
@abhisheks008 what's the status of the review.

**Comment by abhisheks008** [comment]
> 1. Project folder name should be `Landmark Detection` with no hyphen "-".
> 2. Follow the project structure and put the files according to that.
> 3. If you are implementing an UI for the users, follow this project structure, this will help you out in keeping files.
> 
> ```
> Project Folder
> |- Dataset
>    |- dataset.csv (dataset used for the particula project)
>    |- README.md (brief about the dataset)
> |- Images
>    |- img1.png
>    |- img2.png
>    |- img3.png
> |- Model
>    |- project_folder.ipynb
>    |- README.md
> |- Web App
>    |- templates
>    |- static
>    |- app.py
>    |- demo.mp4
>    |- README.md
> |- requirements.txt
> ```

@yashksaini-coder please follow the project structure properly. Do not put files apart from the designated folder.

Model/README.md template: https://github.com/abhisheks008/DL-Simplified/blob/main/.github/readme_template.md
Web App/README.md template: https://github.com/abhisheks008/DL-Simplified/blob/main/.github/web-app_readme_template.md

**Pull request closed without merging**
