### PR TITLE
Sudoku Solver added

### PR DESCRIPTION
**Pull request by ashis2004**
#856 resolved

### CODE REVIEW

**Comment by ashis2004** [comment]
@abhisheks008 pls check it

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
1. Follow this README template and update the same, https://github.com/abhisheks008/DL-Simplified/blob/main/.github/readme_template.md
2. Do some EDA before implementing the models.

@ashis2004

**Comment by abhisheks008** [comment]
While creating the pull request use the pull request template already implemented here.
@ashis2004

**Comment by ashis2004** [comment]
can i make another fresh pr @abhisheks008

**Pull request closed without merging**
