### PR TITLE
Market Basket Analysis

### PR DESCRIPTION
**Pull request by vaishnavi-3969**
# Pull Request for DL-Simplified 💡

## Issue Title : Market Basket Analysis #327 

- **Info about the related issue (Aim of the project)** : To implement Market Basket Analysis on a transactional dataset
- **Name:** Vaishnavi Kale
- **GitHub ID:** @vaishnavi-3969
- **Email ID:** vaishnavi.kale3011@gmail.com
- **Idenitfy yourself:** SSoC '23

Closes: #327 

### Describe the add-ons or changes you've made 📃

I have added the code for market basket analysis

## Type of change ☑️

What sort of change have you made:
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? ⚙️

Describe how it has been tested
Using different dataset
Describe how have you verified the changes made
Using different dataset

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
Please follow the project structure @vaishnavi-3969 and put the visualized images in the Images folder. Add a README.md file for better understanding of the project like others have done. Use the README.md template for it.

**Comment by vaishnavi-3969** [comment]
Changes done please check the PR now

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
1. This project repository consists project which are built using deep learning models/methods. Try to use deep learning methods for this project.
2. Follow the README.md template from here, https://github.com/World-of-ML/DL-Simplified/blob/main/.github/readme_template.md

@vaishnavi-3969

**Review by abhisheks008 — APPROVED** [review]
Your PR is approved and ready to be merged.
@vaishnavi-3969

**Pull request merged**
