### PR TITLE
Deepfake Images Detector using DL

### PR DESCRIPTION
**Pull request by zul132**
# Pull Request for DL-Simplified 💡

## Issue Title : Deepfake Videos and Images Detector using DL

- **Info about the related issue (Aim of the project)** : The goal of this project is to develop multiple deep learning models for detecting deepfake images and compare their performance based on accuracy.
- **Name:** Fathima Zulaikha
- **GitHub ID:** zul132
- **Email ID:** fathima3891@gmail.com
- **Idenitfy yourself: GSSoC-Ext 2024 Participant**

Closes: #853

### Describe the add-ons or changes you've made 📃

* First, I loaded the dataset and performed Exploratory Data Analysis (EDA) on the images. 
* Then I trained the CNN, CapsNet and Xception models for detecting deepfake images from the real ones 
* I then evaluated the models using the Test data and computed their accuracies and loss. 
* Based on the accuracy scores, I selected the best fitted model for the deepfake image detector.

## Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? ⚙️

I tested each of the models on the Test data and evaluated their performance based on two metrics - loss and accuracy. 

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by zul132** [comment]
@abhisheks008 kindly review my PR

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
Everything looks good to me. But the images inside the README file are not visible to me.
image

**Comment by zul132** [comment]
I have re-uploaded the EDA images to the README file. Hope the images should be visible now.
image
image

**Comment by zul132** [comment]
@abhisheks008 kindly check if you can view the README images now.

**Review by abhisheks008 — APPROVED** [review]
Looks good to me. Approved!
@zul132

**Comment by zul132** [comment]
@abhisheks008 Thank you so much for merging my PR!! This is my first contribution under GSSoC-Ext and I am really happy that I started with this Repository!

**Pull request merged**
