### PR TITLE
Sports Image Classification

### PR DESCRIPTION
**Pull request by aaradhyasinghgaur**
# Pull Request for DL-Simplified 💡

## Issue Title :  [Project Addition] : Sports Image Classification 

- **Info about the related issue (Aim of the project)** : To classify 100 different Sports Images.
- **Name:** Aaradhya Singh
- **GitHub ID:** https://github.com/kyra-09
- **Email ID:** aaradhyasinghgaur@gmail.com
- **Idenitfy yourself: (Mention in which program you are contributing in. Eg. For a JWOC 2022 participant it's, `JWOC Participant`)** GSSOC-2024 Contributor

Closes: #633 

### Describe the add-ons or changes you've made 📃

Give a clear description of what have you added or modifications made

 1. ) Using various different available network architectures such as Xception , ResNet50 , VGG16 etc. to do catagorical classification for 100 different sports using dataset (mentioned below) .
2.) use data augmentation techniques to improve the accuarcy of models.
3.) Comparing performance and accuracy of models using accuracy score ,loss and accuracy graph , confusion matrix for better understanding.
4.) Perfroming EDA (data analysis) for dataset to understand the structure of data.
5.) Using README file for describing the work I've performed.

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? ⚙️

Describe how it has been tested
Describe how have you verified the changes made

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

**Kindly add suitable label (level-3) for the project as I have used 5 different dl models.**

### CODE REVIEW

**Comment by kyra-09** [comment]
@abhisheks008 kindly review my pr and add suitable label for it .

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
The sub folders names should be,
- ### Images
- ### Models
- ### Dataset

@kyra-09

**Comment by kyra-09** [comment]
@abhisheks008 have done the requested changes.

**Review by abhisheks008 — APPROVED** [review]
Approved @kyra-09

**Pull request merged**
