### PR TITLE
Advance Anime Recommendation System #981

### LINKED ISSUE #981: Advance Anime Recommendation System
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** :Advance Anime Recommendation System </br>
:red_circle: **Aim** :This project implements an Anime Recommendation System using both content-based and collaborative filtering techniques. It provides recommendations based on user preferences and anime content, leveraging deep learning for enhanced collaborative filtering. </br>
:red_circle: **Dataset** : The dataset is available on Kaggle:
- [Anime.csv and Rating.csv - Kaggle Dataset](https://www.kaggle.com/datasets/CooperUnion/anime-recommendations-database) </br>

:red_circle: **Approach** : using Nlp and DL techniques 

## Features

- **Data Preprocessing**: Cleans and preprocesses `anime.csv` and `rating.csv` datasets.
- **Exploratory Data Analysis (EDA)**: Provides an overview of anime types, genres, ratings, and other insights.
- **Content-Based Filtering**: Generates recommendations based on anime genres, type, and average ratings.
- **Collaborative Filtering**: A deep learning-based recommendation model that learns user preferences.
- **Genre-Based Recommendations**: Ensures diverse recommendations by including various genres in top recommendations.
- **New User and New Anime Recommendations**: Customized recommendations for new users and newly added anime.
- 
**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Parmar Niraj
- GitHub Profile Link : @Niraj1608
- Email ID : nirajprmr1608@gmail.com
- Participant ID (if applicable):GSSOC

- What is your participant role? (Mention the Open Source program)GSSOC

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

### PR DESCRIPTION
**Pull request by Niraj1608**
# Pull Request for DL-Simplified 💡

## Issue Title :  Advance Anime Recommendation System #981

- **Info about the related issue (Aim of the project)** : 
- This project implements an Anime Recommendation System using both content-based and collaborative filtering techniques. It provides recommendations based on user preferences and anime content, leveraging deep learning for enhanced collaborative filtering.
- **Name:**  Parmar Niraj
- **GitHub ID:**  @Niraj1608 
- **Email ID:**  nirajprmr1608@gmail,com
- **Idenitfy yourself: (Mention in which program you are contributing in. Eg. For a JWOC 2022 participant it's, `JWOC Participant`)**  GSSOC

Closes: #issue number that will be closed through this PR #981 

## Features

- **Data Preprocessing**: Cleans and preprocesses `anime.csv` and `rating.csv` datasets.
- **Exploratory Data Analysis (EDA)**: Provides an overview of anime types, genres, ratings, and other insights.
- **Content-Based Filtering**: Generates recommendations based on anime genres, type, and average ratings.
- **Collaborative Filtering**: A deep learning-based recommendation model that learns user preferences.
- **Genre-Based Recommendations**: Ensures diverse recommendations by including various genres in top recommendations.
- **New User and New Anime Recommendations**: Customized recommendations for new users and newly added anime.

Give a clear description of what have you added or modifications made

## Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? ⚙️

Describe how it has been tested
Describe how have you verified the changes made

## Checklist: ☑️

- [X] My code follows the guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly wherever it was hard to understand.
- [X] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [X] I have added things that prove my fix is effective or that my feature works.
- [X] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by Niraj1608** [comment]
@abhisheks008 can you review my pr
and i added output in resource directory in a video

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
1. Inside the Model folder put all the notebooks along with the models implemented.
2. Follow the project structure and put your files. For your reference sharing a project folder, https://github.com/abhisheks008/DL-Simplified/tree/main/Brain%20Tumor%20Detection

@Niraj1608

**Comment by Niraj1608** [comment]
@abhisheks008 i created a specific directory for a notebooks

**Comment by abhisheks008** [comment]
Please follow the project folder and update your file arrangements, https://github.com/abhisheks008/DL-Simplified/tree/main/Brain%20Tumor%20Detection

**Comment by Niraj1608** [comment]
@abhisheks008 done

**Review by abhisheks008 — APPROVED** [review]
Approved!!
@Niraj1608

**Pull request merged**
