### PR TITLE
Land use scene classification

### PR DESCRIPTION
**Pull request by Adhivp**
# Pull Request for DL-Simplified 💡

## Issue Title : 

- **Info about the related issue (Aim of the project)** : To create models that can be used to classify  based on Land use
- **Name:** Adhithyan vp
- **GitHub ID:** Adhivp
- **Email ID:** adhivp910@gmail.com
- **Idenitfy yourself: GSSOC'24

Closes: #463 

### Describe the add-ons or changes you've made 📃

Give a clear description of what have you added or modifications made

## Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? ⚙️

Describe how it has been tested
Describe how have you verified the changes made

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
1. Rename the Readme files to `README.md`.
2. In the Dataset/README.md file, please share some brief about the dataset.
3. Create a folder named, Images and put the EDA results, Accuracy graphs there.
4. Please follow the README template and update the Model/README.md file. Here is the template, https://github.com/abhisheks008/DL-Simplified/blob/main/.github/readme_template.md

@Adhivp

**Comment by Adhivp** [comment]
@abhisheks008  Done the changes , please merge my PR fast , so that I can work on other issues

**Comment by abhisheks008** [comment]
Hi @Adhivp sorry for the delay. As Kolkata was hit by a cyclone last night, my internet was cut off yesterday, that's why can't do anything here.

**Review by abhisheks008 — APPROVED** [review]
Approved @Adhivp

**Pull request merged**
