### PR TITLE
[Project Addition]: Breast Cancer Detection using DL - with Web App #554

### PR DESCRIPTION
**Pull request by TechieSamosa**
# Pull Request for DL-Simplified 💡

## Issue Title : <[Project Addition]: Breast Cancer Detection using DL - with Web App #554>

- **Info about the related issue (Aim of the project)**: The aim of this project is to develop a Breast Cancer Detection system using Deep Learning techniques on Ultrasound images. The project includes a web application for easy access and usability.
- **Name:** Aditya Khamitkar
- **GitHub ID:** TheNaiveSamosa
- **Email ID:** thenaivesamosa@gmail.com
- **Identify yourself:** Contributor GSSoC 24

Closes: #554

### Describe the add-ons or changes you've made 📃

I have added a Breast Cancer Detection project using Deep Learning, focusing on ultrasound images. The project includes:
- Model folder with the trained models and Jupyter notebooks for training.
- Webapp folder containing the Flask web application with templates and static files.
- Dataset folder with a README.md.
- Detailed README files in the root and respective folders to guide users through the project.

## Type of change ☑️

What sort of change have you made:
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? ⚙️

The project has been tested by:
- Running the training scripts and verifying the model's performance on the validation dataset.
- Deploying the web application locally and ensuring that it functions correctly.
- Performing EDA on the dataset to ensure it is suitable for training the models.

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
image

Video demonstration is not visible. Please refer to [Brain Tumor Detection](https://github.com/abhisheks008/DL-Simplified/tree/main/Brain%20Tumor%20Detection) project for better understanding. Just drag and drop the video file from your local system to GitHub README. Only this will embed the video file, hyperlinking the video from the folder will not work.

@TheNaiveSamosa

**Comment by TheNaiveSamosa** [comment]
Made the changes. Please do check.

**Comment by TheNaiveSamosa** [comment]
And also reconsider the level of the Issue.

**Review by abhisheks008 — APPROVED** [review]
Approved @TheNaiveSamosa

**Pull request merged**
