### PR TITLE
ADD INTRODUCTION AND OVERVIEW ALONG WITH TABLE OF CONTENT

### PR DESCRIPTION
**Pull request by alo7lika**
# Pull Request for DL-Simplified 💡

## Issue Title: ADD INTRODUCTION AND OVERVIEW ALONG WITH TABLE OF CONTENT

- **Info about the related issue (Aim of the project)**: The aim is to enhance the README file and make it visually appealing and well-documented using the provided README template.
- **Name:** Alolika Bhowmik
- **GitHub ID:** https://github.com/alo7lika
- **Email ID:** alolikabhowmik72@gmail.com
- **Identify yourself:** GSSoC Contributor Ext 24

Closes: #931 

---

### Describe the add-ons or changes you've made 📃

I have updated the README file to include:
1. An **Introduction** to the project to give users a clear understanding of DL-Simplified.
2. An **Overview** section that highlights the project’s main goals and structure.
3. A **Table of Contents** for easy navigation within the README file.

These changes make the documentation more comprehensive and user-friendly.

---

## Type of change ☑️

Please select the type of change you have made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

---

## How Has This Been Tested? ⚙️

The changes were tested by:
- Reviewing the updated README in the GitHub preview to ensure proper formatting.
- Checking all links in the Table of Contents for correct navigation.
- Verifying that all added sections align with the template and maintain readability.

---

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly where it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added necessary elements that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by alo7lika** [comment]
@abhisheks008 kindly check the PR

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
Project repository name should be aligned as Center.
@alo7lika

**Comment by alo7lika** [comment]
> Project repository name should be aligned as Center. @alo7lika

Done @abhisheks008

**Review by abhisheks008 — APPROVED** [review]
Approved! @alo7lika

**Pull request merged**
