### PR TITLE
Snake Breed Identification

### PR DESCRIPTION
**Pull request by the-silent-geek**
# Pull Request for DL-Simplified 💡

## Issue Title :  Snake Breed Identification

- **Info about the related issue (Aim of the project)** : To create deep learning models for snake breed identification.
- **Name:** Dammala Uday Kiran
- **GitHub ID:** the-silent-geek
- **Email ID:** udaykir3911@gmail.com
- **Idenitfy yourself: (Mention in which program you are contributing in. Eg. For a JWOC 2022 participant it's, `JWOC Participant`)** : contributor SWOC 24

Closes: #228   

### Describe the add-ons or changes you've made 📃

Added dataset, accuracy plots, and 3 models for identification.

## Type of change ☑️

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? ⚙️

Describe how it has been tested
Describe how have you verified the changes made

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
1. Add some more EDA in the notebook as well as the resultant images in the README.md file.
2. In the Conclusion, use bullet points, put your EDA results too with the best fitted model.

@the-silent-geek

**Comment by the-silent-geek** [comment]
I have added value counts and breeds images. Could you give me some ideas for EDA on the dataset.

**Comment by abhisheks008** [comment]
You can do this,
1. View in HTML format using csv file.
2. Images from folder - one image at a time
3. Random image generation from a folder
4. Random image based on csv file.

**Comment by the-silent-geek** [comment]
Okay, I will add these in the README file.

**Review by abhisheks008 — APPROVED** [review]
Approved.
@the-silent-geek

**Pull request merged**
