### PR TITLE
Add Hate Speech Detection

### PR DESCRIPTION
**Pull request by adwityac**
# Pull Request for DL-Simplified 💡

## Issue Title :  Add Hate Speech Detection

- **Info about the related issue (Aim of the project)** :  The aim of the project is to develop a Natural Language Processing (NLP) system that can automatically identify and classify hate speech and abusive language in social media posts. By leveraging sentence classification techniques, the project seeks to filter out harmful content, promote a safer online environment, and reduce the spread of hate and controversy on social media platforms. Ultimately, the goal is to enhance user experience and foster positive interactions by mitigating the impact of negative and toxic communication.
- **Name:**  Adwitya Chakraborty
- **GitHub ID:**  adwityac
- **Email ID:**  adwityachakraborty@hotmail.com
- **Idenitfy yourself: (Mention in which program you are contributing in. Eg. For a JWOC 2022 participant it's, `JWOC Participant`)**  GSSoC Extended Participant

Closes: #972 

### Describe the add-ons or changes you've made 📃

Added Hate Speech Detection System with all the required dependencies,images,dataset.

## Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? ⚙️

Describe how it has been tested 

The model was tested by splitting the dataset into training and testing sets, allowing performance evaluation on unseen data. Metrics such as accuracy, precision, recall, and F1-score were used to assess its effectiveness in detecting hate speech.

Describe how have you verified the changes made

The model was tested by splitting the dataset into training and testing sets, allowing performance evaluation on unseen data. Metrics such as accuracy, precision, recall, and F1-score were used to assess its effectiveness in detecting hate speech.
## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by aslams2020** [comment]
This PR has been merged by the GSSoC team 
here - https://github.com/sanjay-kv/Open-source-Practice/pull/1349

 Don't add labels to it now.You'll get the points in the leaderboard update.

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
1. The Model/README.md file is not updated as per the README template.
2. If you are making a GUI for showcasing the features of the project, then you need to create a separate sub folder as `Web App`, and put the files accordingly. Sharing a project folder for your reference, https://github.com/abhisheks008/DL-Simplified/tree/main/Brain%20Tumor%20Detection
image

**Comment by abhisheks008** [comment]
> This PR has been merged by the GSSoC team here - [sanjay-kv/Open-source-Practice#1349](https://github.com/sanjay-kv/Open-source-Practice/pull/1349)
> 
> Don't add labels to it now.You'll get the points in the leaderboard update.

Can you please clarify why is this PR merged without any review? Why the points are allocated? If this is happened due to my inactivity during these days, then I apologize for that. I have been part of this open source event since 2021-22, you can check my past records as a PA. I think you should wait for the last day of the coding period before adding the points. Adding points to a PR and merging them without a review is also violating the code of conduct.

Apologies for the inactivity during this period due to my committments at my organisation.

**Comment by MastanSayyad** [comment]
@abhisheks008 Program Manager here. Yes, We had to give points due to inactivity, as it's understandable that contributors may feel impatient on the last day of GSSoC. However, note that this was a project addition for "Hate Speech Detection," which qualifies for only level 1 (10 points) and the points have been added after the PR review. 

If you are active again Then Please feel free to proceed with reviewing this PR, and we’ll remove the points from the previous one.

**Comment by abhisheks008** [comment]
> @abhisheks008 Program Manager here. Yes, We had to give points due to inactivity, as it's understandable that contributors may feel impatient on the last day of GSSoC. However, note that this was a project addition for "Hate Speech Detection," which qualifies for only level 1 (10 points) and the points have been added after the PR review.
> 
> If you are active again Then Please feel free to proceed with reviewing this PR, and we’ll remove the points from the previous one.

I'll review the PR, please remove the points which has been added.

**Comment by adwityac** [comment]
@abhisheks008 Made the changes you requested, kindly review and let me know if further changes have to be made.

**Comment by abhisheks008** [comment]
Hi @adwityac can you please drop a message in Discord, it'll be helpful for further communications.

**Comment by abhisheks008** [comment]
Hi @MastanSayyad @aslams2020 please remove the points added through `https://github.com/sanjay-kv/Open-source-Practice/pull/1349` as this pull request and issue is being upgraded from Level 1 to 2.

Thanks in advance!

**Comment by MastanSayyad** [comment]
@abhisheks008 already removed

**Pull request merged**
