### PR TITLE
[Project Addition] Cats Breed Classification using DL

### PR DESCRIPTION
**Pull request by Arihant-Bhandari**
# Pull Request for DL-Simplified 💡

## Issue Title : #754 Cats Breed Classification using DL

- **Info about the related issue (Aim of the project)**: Classifying images of Cats into 5 Breeds.
- **Name:** Arihant Bhandari
- **GitHub ID:** https://github.com/Arihant-Bhandari
- **Email ID:** arihant.bhandari.2004@gmail.com
- **Identify yourself:** GSSoC 2024 Contributor

Closes: #754 Cats Breed Classification using DL

### Describe the add-ons or changes you've made 📃

Wrote code for preprocessing and loading images from cat_v1 dataset, turned labels into probability distributions, created models including custom CNN as well as pre-trained models, like ResNet-50, VGG16 and so on.

## Type of change ☑️

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## How Has This Been Tested? ⚙️

| Models | Accuracy | Loss |
|--------|---------------------|--------------------------|
| ResNet-50 | 22.66% | 12.4663 |
| InceptionV3 | 83.59%  | 0.4896 | 
| CNN | 35.94% | 2.2302 |
| VGG16 | 78.12% | 0.6243 |
| MobileNet | 90.62% | 0.3220 |
| DenseNet-121 | 85.16% | 0.5082 |
| Xception | 82.81% | 0.4810 |
| NASNetMobile | 87.50% | 0.4133 |

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by Arihant-Bhandari** [comment]
hi @abhisheks008 this PR is for a look at my current code, i will update as per discussion on accuracy.

**Comment by Arihant-Bhandari** [comment]
hi @abhisheks008 models have been updated, pls change the tags as requested on pomegranate disease issue, and assign things for cats breed for submission of this porject.

Thnak you for your time and attention, and sorry for the changes in tags.

**Comment by abhisheks008** [comment]
`requirements.txt` file is missing.

**Comment by Arihant-Bhandari** [comment]
@abhisheks008 I have added requirements.txt file , pls review

**Review by abhisheks008 — APPROVED** [review]
Approved @Arihant-Bhandari

**Pull request merged**
