### PR TITLE
Brand Sentiment Analysis using NLP

### PR DESCRIPTION
**Pull request by dipayan22**
# Pull Request for DL-Simplified 💡

## Issue Title : Brand Sentiment Analysis using NLP

- **Info about the related issue (Aim of the project)** : The aim of this project is to analyze the sentiment of the brands based on the dataset.
- **Name:** Dipayan Majumder
- **GitHub ID:** [Dipayan Majumder](https://github.com/dipayan22/)
- **Email ID:** majumderd007@gmail.com
- **Idenitfy yourself: (Mention in which program you are contributing in. Eg. For a JWOC 2022 participant it's, `JWOC Participant`)** SWOC 24

Closes: Brand Sentiment Analysis using NLP #445

### Describe the add-ons or changes you've made 📃

Give a clear description of what have you added or modifications made

## Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? ⚙️

Describe how it has been tested
Describe how have you verified the changes made

## Checklist: ☑️

- [ ] My code follows the guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by abhisheks008** [comment]
> Simple machine learning models won't work for this project. This is a NLP project which uses deep learning methods to get the work done. Try to use deep learning methods. You can take help from the mentors in the Discord server, they will guide you. @dipayan22 drop a text in the DL-Simplified channel regarding the same, mentors will help you out.

I have mentioned in the channel, mentors will guide you. Don't worry.

**Comment by dipayan22** [comment]
@abhisheks008 I have created a model using Deep learning . You can see it.

**Comment by abhisheks008** [comment]
Hi @dipayan22 document the README file in the proper manner as mentioned in the README template. Check out the README template, https://github.com/abhisheks008/DL-Simplified/blob/main/.github/readme_template.md

**Comment by dipayan22** [comment]
Hi @abhisheks008 ,

I've revamped the README.md for our Brand Sentiment Analysis Project, aligning it with the template we discussed.

**Comment by abhisheks008** [comment]
image

Use `<br>` tags for the gappings.

**Comment by dipayan22** [comment]
README.md file updated..

**Review by abhisheks008 — APPROVED** [review]
Approved @dipayan22

**Pull request merged**
