### PR TITLE
Global Land Cover Mapping using Image Processing

### PR DESCRIPTION
**Pull request by ArismitaM**
# Pull Request for DL-Simplified 💡

## Issue Title: Global Land Cover Mapping using Image Processing

- **Info about the related issue (Aim of the project)**: The aim is to create a deep-learning model that will detect and classify the different types of land cover.
- **Name:** Arismita Mukherjee
- **GitHub ID:** ArismitaM
- **Email ID:** arismita08.m@gmail.com
- **Idenitfy yourself: (Mention in which program you are contributing in. Eg. For a JWOC 2022 participant it's, `JWOC Participant`)** GSSoC '24

Closes: #503 #issue number that will be closed through this PR

### Describe the add-ons or changes you've made 📃
 I have made a folder containing all the required files and subfolders. I have tried and tested 3 models for this issue, namely YOLOv5, RetinaNet, and VGG16, and added the best model.

Give a clear description of what have you added or modifications made

I have added a new folder to this repo with the same name as that of the issue name which is 'Global Land Cover using Image Processing'.
This was my first time working with .tif images and I have used the DBScan clustering technique to draw bounding boxes and then trained each of the models. 

## Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? ⚙️

Describe how it has been tested
There was a folder that contained images for testing, so, I ran testing on those images, and based on the results I had to re-train some of the models with varying epochs and batch sizes to get the best result.

Describe how have you verified the changes made
I saw the testing on the images where the model was able to classify most of the data correctly. I trained it with 5000 epochs. I verified the testing with the help of the mAP and epoch loss graphs.

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by abhisheks008** [comment]
1. Please upload the `.ipynb` file inside the Model folder. It's the optimum file for this project.
2. Minor rename changes are required, readme should be `README.md`.

**Comment by ArismitaM** [comment]
I have uploaded the .ipynb file inside the model folder and have renamed the README.md file

**Comment by abhisheks008** [comment]
I asked you to upload the whole code inside the notebook, how you implemented all the three models, how you made those graphs, how you implemented the architecture all those codes should be written inside the notebook file. You can check out the existing projects for your reference.

**Comment by ArismitaM** [comment]
I have changed my .ipynb file. I have added the training graphs and the testing.

**Comment by abhisheks008** [comment]
Hi @ArismitaM sorry for the late reply. I have seen your model.ipynb file, I didn't find the other two model implementations apart from YoloV5. Can you explain this to me?

**Comment by ArismitaM** [comment]
> Hi @ArismitaM sorry for the late reply. I have seen your model.ipynb file, I didn't find the other two model implementations apart from YoloV5. Can you explain this to me?

Hello @abhisheks008, I thought we were supposed to add only the best model initially, so I added only the YOLO model. I have added the RetinaNet model too. Coming to VGG16, I realized that it was ideal for detection and not for classification, therefore it cannot detect more than 1 class. But my training has 8 classes so VGG was not ideal. I have mentioned this in the README.md file too.

**Review by abhisheks008 — APPROVED** [review]
Looks good to me. Approved @ArismitaM

**Pull request merged**
