### PR TITLE
[Feature Addition]: Web App for Fake News Detection

### PR DESCRIPTION
**Pull request by AKing-283**
# Pull Request for DL-Simplified 💡

## Issue Title : [Feature Addition]: Web App for Fake News Detection 

- **Info about the related issue (Aim of the project)** : Frontend as gradio
- **Name:** Puspak Dakkata
- **GitHub ID:** AKing-283
- **Email ID:** pushpakreddy283@gmail.com
- **Identify yourself: GSSOC Contributor** 

Closes: #687 

### Describe the add-ons or changes you've made 📃

I have added feature of frontend where user can get predictions through output.
I have used Gradiio for this.
User have to enter the news in input section and can predictions via output section

## Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## How Has This Been Tested? ⚙️

I have tested the model first whether it can predict or not and then made the frontend for that
I have verified changes by entering the news and got the output as real or fake via. output section.
Screenshot 2024-06-13 at 9 26 46 AM

## Checklist: ☑️

- [ ] My code follows the guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
Where is the Web App?

You need to create a subfolder as Web App and put the files there. Also you need to create a README and put a demonstration video of the working of the web app.

@AKing-283

**Comment by AKing-283** [comment]
Okay @abhisheks008  I will work on it 🫡

**Comment by AKing-283** [comment]
@abhisheks008 I have made a folder Web-App and uploaded the required content and made changes and created readme.md file too.

**Comment by abhisheks008** [comment]
Upload the demonstration video inside the Web App folder and attach the same in the README instead of putting a Google Drive link.

**Comment by AKing-283** [comment]
Done Bro 😅 @abhisheks008

**Pull request merged**
