### PR TITLE
Terrain Classification

### PR DESCRIPTION
**Pull request by MohanRocks999**
# Pull Request for DL-Simplified 💡

## Issue Title : Terrain Recognition 

- **Info about the related issue (Aim of the project)** : 
- **Name:** Mohana Krishna
- **GitHub ID:** https://github.com/MohanRocks999
- **Email ID:** www.mohanakrishna123@gmail.com
- **Idenitfy yourself: (Mention in which program you are contributing in. Eg. For a JWOC 2022 participant it's, `JWOC Participant`)** I am Contributing in GSSoC 2024

Closes: #636 

### Add-ons or changes made 📃

Trained a Image Classification using various deep learning algorithms. This include DeepViT (Not just Vision Transformer),  EfficientNet B3, DeiT3 (Data efficient image transformer) and YoloV8 that classifies images on 5 different types of terrains - coast, mountain, glacier, forest and desert.

## Type of change ☑️

- [ X] New feature - A Terrain Classification using the respective neural network architecture using pytorch.

## How Has This Been Tested? ⚙️

The Model have been evaluated extensively with a validation dataset comprising of 2000 images (400 images per class) and a test dataset of 500 images. 

## Checklist: ☑️

- [ X] My code follows the guidelines of this project.
- [ X] I have performed a self-review of my own code.
- [X ] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [ X] My changes generate no new warnings.
- [X ] I have added things that prove my fix is effective or that my feature works.
- [ ]X Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by abhisheks008** [comment]
What's the issue number?

**Comment by MohanRocks999** [comment]
The issue number is 636

**Comment by abhisheks008** [comment]
Hi @MohanRocks999 remove the extra files and follow the project structure for this project.

**Comment by MohanRocks999** [comment]
What files needs to be removed and do you want me to add all the models in one single notebook?

**Comment by abhisheks008** [comment]
It'll be better to have a single notebook file (`.ipynb`) where all the models and EDAs can be implemented together.

**Comment by MohanRocks999** [comment]
The changes has been as per your request. check it out.

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
Hi @MohanRocks999 everything looks good to me. Some minor changes are required,
1. Follow the README template and update the README as per the given points. Here is the template: https://github.com/abhisheks008/DL-Simplified/blob/main/.github/readme_template.md
2. Insert the resulted images inside the Images folder including the confusion matrix, data visualization and so on.
3. Remove the `.gitignore` file.

**Comment by MohanRocks999** [comment]
The requested changes has been done. Please check the changes as soon as you can.

**Review by abhisheks008 — APPROVED** [review]
Looks good to me. Approved ✅ 
@MohanRocks999

**Pull request merged**
