### PR TITLE
CNN YOLO model for Object Tracking Project

### PR DESCRIPTION
**Pull request by ShashwatGaikwad24**
Complete building the model for Object Tracking Project

# Pull Request for DL-Simplified 💡

## Issue Title : Object Tracking Project

- **Info about the related issue (Aim of the project)** : To build an efficient model for Object Tracking
- **Name:** Shashwat Gaikwad
- **GitHub ID:** ShashwatGaikwad24
- **Email ID:** gaikwadshsa19ie@student.mes.ac.in
- **Idenitfy yourself: NA

Closes: #10 

### Describe the add-ons or changes you've made 📃

Created a CNN-based(YOLO) model for the Object Tracking Project

## Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? ⚙️

Describe how it has been tested
Describe how have you verified the changes made

## Checklist: ☑️

- [ ] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
Please follow the project structure @ShashwatGaikwad24

**Comment by Satyawan7** [comment]
@abhisheks008 I am making the suggested changes and will get it done super soon:)

**Comment by abhisheks008** [comment]
@ShashwatGaikwad24 please do the required changes otherwise this will not be counted towards the contribution to this project repository.

**Comment by abhisheks008** [comment]
Closing this PR due to inactivity.

**Pull request closed without merging**
