### PR TITLE
Driving Behavior Identification #65

### PR DESCRIPTION
**Pull request by sid-im**
# Pull Request for DL-Simplified 💡

## Issue Title : 

- **Info about the related issue (Aim of the project)** : 
- **Name:** 
- **GitHub ID:** 
- **Email ID:** 
- **Idenitfy yourself: (Mention in which program you are contributing in. Eg. For a JWOC 2022 participant it's, `JWOC Participant`)** 

Closes: #issue number that will be closed through this PR

### Describe the add-ons or changes you've made 📃

Give a clear description of what have you added or modifications made

## Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? ⚙️

Describe how it has been tested
Describe how have you verified the changes made

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by sid-im** [comment]
#65

**Comment by abhisheks008** [comment]
Check this project, https://github.com/abhisheks008/DL-Simplified/tree/main/Credit%20Card%20Fraud%20Detection. You'll get an idea how to put the files.

**Review by 072arushi — CHANGES_REQUESTED** [review]
Add the code snippets, images of the graphs and accuracy.

**Comment by sid-im** [comment]
i added images section and added code snippets...can u review once @abhisheks008

**Comment by abhisheks008** [comment]
Please follow the project pattern properly. You need to create three separate folders, Dataset, Model and Images inside your project folder. All the files will be put in the folders as per their positions.
@sid-im

**Comment by sid-im** [comment]
Screenshot (129)
i arranged 
dataset
images
model
-->folders in order...still wat should i change?
@abhisheks008

**Comment by abhisheks008** [comment]
I think you need to understand the major difference between the files and the folders. What you have created is having an extension of `.md` which means this is a file, not a folder. Do you have any folder in your system which is having any extension? You have different folders in your system, like `Downloads`, `Pictures`, `Music` etc etc, do they have any extension of `.something`? I don't think so!

I have told you to create a project folder first, named as, `Driving Behavior Identification`, inside that project folder create sub folders named as, Models, Dataset, Images. Inside those sub folders put the designated files. That's all I wanted from you.

@sid-im 

For your reference you can check out other projects which are already done by your fellow contributors.

<a href="https://imgur.com/chYbjOs">
<a href="https://imgur.com/2f5JOKd"></a>
</a> <a href="https://imgur.com/eBdQRvl"></a>
<a href="https://imgur.com/ikyMTD2"></a>

**Comment by sid-im** [comment]
ok sorry for that...ill make these required changes
thank you @abhisheks008

**Comment by abhisheks008** [comment]
Changed approved. Your PR is merged. Thanks for contributing in Deep Learning Simplified.
@sid-im

**Pull request merged**
