### PR TITLE
Brand Sentiment Analysis using NLP

### PR DESCRIPTION
**Pull request by dipayan22**
# Pull Request for DL-Simplified 💡

## Issue Title : Brand Sentiment Analysis using NLP

- **Info about the related issue (Aim of the project)** : The aim of this project is to analyze the sentiment of the brands based on the dataset.
- **Name:** Dipayan Majumder
- **GitHub ID:** https://github.com/dipayan22/
- **Email ID:** majumderd007@gmail.com
- **Idenitfy yourself: (Mention in which program you are contributing in. Eg. For a JWOC 2022 participant it's, `JWOC Participant`)** 

Closes: Brand Sentiment Analysis using NLP #445

### Describe the add-ons or changes you've made 📃

Give a clear description of what have you added or modifications made

## Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? ⚙️

Describe how it has been tested
Describe how have you verified the changes made

## Checklist: ☑️

- [ ] My code follows the guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
Follow the project structure and put your files according to that. You can check out existing projects for your reference.

@dipayan22

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
Images folder is missing.

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
Create a separate project folder as per the issue name and put your project files there. Check out the existing projects.

@dipayan22

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
image


Remove the folder which are outside of the project folder.
@dipayan22

**Comment by dipayan22** [comment]
Sir ,i delete this pull request and create a new pull request with the proper structure.

**Pull request closed without merging**
