### PR TITLE
Real or Fake Job Posting Prediction

### PR DESCRIPTION
**Pull request by Karthik110505**
# Pull Request for DL-Simplified 💡

## Issue Title : [Project Addition] Real or Fake Job Posting Prediction

- **Info about the related issue (Aim of the project)** : To predict whether the given job post description is real or fake using DL
- **Name:** Veera Venkata Karthik Barrenkala
- **GitHub ID:**  [Karthik110505](https://github.com/Karthik110505)
- **Email ID:** [bvvkarthik1155@gmail.com](mailto:bvvkarthik1155@gmail.com)
- **Identify yourself:** GSSoC'24 Participant

Closes: #660 

### Describe the add-ons or changes you've made 📃

I have added a new project named "Real or Fake Job Posting Prediction" to the repository.

## Type of change ☑️

What sort of change have you made:

- [x] Project Addition (Adding a Project to the directory without any issues)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? ⚙️

The project has been tested locally on a sample dataset to ensure functionality and accuracy.

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by Karthik110505** [comment]
@abhisheks008  Please review this pr.

**Comment by abhisheks008** [comment]
Can you implement two more models, as ANN and LSTM are kinda basic models tbh.
@Karthik110505

**Comment by Karthik110505** [comment]
@abhisheks008  Please check it now. I have added cnn and bilstm model. Sorry I haven't  seen your message till today, that's why it took me time.

**Comment by abhisheks008** [comment]
MODELS USED

The models developed are:

Artificial Neural Network (ANN)
Long Short-Term Memory (LSTM)

Please update the README file, you have not updated the README with the newly implemented models for this project.

**Comment by Karthik110505** [comment]
@abhisheks008  Can you please check it now.

**Review by abhisheks008 — APPROVED** [review]
Approved @Karthik110505

**Pull request merged**
