### PR TITLE
High Throughput Algae Cell Detection

### PR DESCRIPTION
**Pull request by ARPIT2128**
# Pull Request for DL-Simplified 💡

## Issue Title : #417 

- **Info about the related issue (Aim of the project)** :  The aim of this project is to detect high throughput Algae cell using Deep Learning and OpenCV methods.
- **Name:** ARPIT SHARMA
- **GitHub ID:** [My Github](https://github.com/ARPIT2128)
- **Email ID:** arpitsharma2128@gmail.com
- **denitfy yourself:** `SWOC 2024 Participant`

Closes: #issue number that will be closed through this PR

### Describe the add-ons or changes you've made 📃

- Created a template based on the information provided in #417 

## Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## How Has This Been Tested? ⚙️

Describe how it has been tested
Describe how have you verified the changes made

Implemented on synced fork from [here](https://github.com/ARPIT2128/DL-Simplified) so less chance to cause issues for main branch of this repo.

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by abhisheks008** [comment]
Update this pull request once you are done with the whole project and put the files according to the project structure.

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
Follow the project structure and put the files according to that.
@ARPIT2128

**Comment by ARPIT2128** [comment]
ok, git pushed here by mistake

**Comment by ARPIT2128** [comment]
🎉 **Completed the Project - Issue #417**

I'm thrilled to announce that the project associated with Issue #417 has been successfully completed! 🚀

[results](https://github.com/ARPIT2128/DL-Simplified/blob/main/High%20Throughput%20Algae%20Cell%20Detection/Images/img_info.MD)

This marks an important milestone for the project, and I'm excited about the progress made. If there are any additional tasks, feedback, or further discussions needed, please feel free to let me know.

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
Can you remove these two files, `.gitattributes` and `.gitignore`.
@ARPIT2128

**Comment by abhisheks008** [comment]
You have pushed 3000+ files!!
You don't have to put all the image datapoints inside the Dataset folder, just the provide the URL of the dataset, that will do.

I request you to create a fresh PR, may be your forked repository is not updated with the main branch.
@ARPIT2128

**Pull request closed without merging**
