### PR TITLE
Dog Face Detection Using DL

### PR DESCRIPTION
**Pull request by Rithish5513U**
# Pull Request for DL-Simplified 💡

## Issue Title : Dog Face Detection using DL

- **Aim of the project** : To detect dog face in the given imge
- **Name:** Rithish S
- **GitHub ID:** Rithish5513U
- **Email ID:** rithish.satish@gmail.com
- **Idenitfy yourself: GSSoc'24 Contributor

Closes: #240

### Describe the add-ons or changes you've made 📃

I have created a Dog Face Detection Model Using YOLOv8 Model
I chose this model because it is best suited for object detection tasks.

Further I didn't use any other model because I face trouble with the amount of time it is taking to train the model. I have waited for a full night for the model to train because of the size of the dataset. Here the task is to detect dog face in the image and make a bounding box for the detected image. So I have trained YOLOv8 model.

## Performance Metrics

Here I have not used Accuracy and Loss function. It is because of the bounding boxes and the problem is not about classification.

The performance metrices used here are :

- Confidence Curve
- Precision-Recall Curve
- Precision-Confidence Curve
- Recall-Confidence Curve

## How Has This Been Tested? ⚙️

I have verified the model prediction with the actual results. I have tested it by the above mentioned metrics and by manually viewing each images.

I have first trained YOLOv8 model and then I have predicted the output and tested it with the original results and gave the results accordingly.

## Checklist: ☑️

- [ x] My code follows the guidelines of this project.
- [ x] I have performed a self-review of my own code.
- [x ] I have commented my code, particularly wherever it was hard to understand.
- [ x] I have made corresponding changes to the documentation.
- [x ] My changes generate no new warnings.
- [ x] I have added things that prove my fix is effective or that my feature works.
- [x ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
I have seen that you have implemented only YOLO for this project. I know this is a goto solution for this kind of dataset. Can you implement other algorithms/methods for this dataset apart from YOLO. I think you have mentioned VGG in the approach for this issue. Try to implement at least two more methods and update the project accordingly.
@Rithish5513U

**Comment by Rithish5513U** [comment]
Can i do the other models in new notebook file or should i do it in the same notebook??

**Comment by abhisheks008** [comment]
> Can i do the other models in new notebook file or should i do it in the same notebook??

You can update the existing notebook and add models one after another.

**Comment by Rithish5513U** [comment]
@abhisheks008 I can't upload my notebook in github. If i upload, it shows only half of the page. What can I do

**Comment by Rithish5513U** [comment]
I actually worked on a different notebook and merged those after u said and i dont know what happenned. Even if i upload, it only uploading half of the file

**Comment by Rithish5513U** [comment]
@abhisheks008 If i download it again from github it shows full code. I'm so confused

**Comment by abhisheks008** [comment]
> @abhisheks008 If i download it again from github it shows full code. I'm so confused

Then put the files separately. But in the README mention all the implemented models and document them all.

**Comment by Rithish5513U** [comment]
@abhisheks008 I dont have loss function metric in YOLO and i have confidence instead of accuracy in Yolo can i provide the confidence as the performance for yolo model and for other 2 models i.e., mobilet ssd and vgg- i will provide accuracy and loss function??

**Comment by abhisheks008** [comment]
> @abhisheks008 I dont have loss function metric in YOLO and i have confidence instead of accuracy in Yolo can i provide the confidence as the performance for yolo model and for other 2 models i.e., mobilet ssd and vgg- i will provide accuracy and loss function??

No issues. Just need a parameter to judge/check which is the best fitted model for this dataset.

**Review by abhisheks008 — APPROVED** [review]
Looks good to me! Your PR is approved and ready to be merged.
@Rithish5513U 

P.S. Show some support and love by starring the repo 🌟

**Comment by Rithish5513U** [comment]
@abhisheks008 A help needed from the mentor. I have used different email of github for doing this project contribution. But my mail while I register for GSSoc'24 is rithish.satish@gmail.com. Pls add the contribution points to this mail. Now i have changed my primary mail address in github to this (rithish.satish@gmail.com)

**Pull request merged**
