### PR TITLE
 Polyp Segmentation in Endoscopy Image

### PR DESCRIPTION
**Pull request by Kaushal-11**
# Pull Request for DL-Simplified 💡

## Issue Title : Polyp Segmentation

- **Info about the related issue (Aim of the project)** : I propose to add a feature for Polyp Segmentation using an endoscopy image dataset. This feature aims to improve the detection and segmentation of polyps in endoscopic images, which is crucial for early diagnosis and treatment of colorectal cancer.

Closes: #626 

## Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by abhisheks008** [comment]
Add a brief conclusion stating that which model is better and why?
@Kaushal-11

**Comment by Kaushal-11** [comment]
Okay, Done it.

Added model evaluation and Conclude with best model

**Review by abhisheks008 — APPROVED** [review]
Looks good to me. Approved @Kaushal-11

**Comment by abhisheks008** [comment]
Please share these details for further communications and scoresheet updation:
Name:
Email Address:

@Kaushal-11

**Comment by Kaushal-11** [comment]
> Please share these details for further communications and scoresheet updation: Name: Email Address:
> 
> @Kaushal-11

Name : Kaushal Bhanderi
Email : kaushalbhanderi34@gmail.com

**Comment by Kaushal-11** [comment]
Hey @abhisheks008,

can you update my points,
because my name is not present in leaderboard

**Pull request merged**
